Updated bash-setup

diff --git a/bash-setup b/bash-setup
--- a/bash-setup
+++ b/bash-setup
@@ -11,13 +11,17 @@ MY1_BASH_PROFILE=$(cat <<SETVAR1
 # ~/.bash_profile - login shells
 
 umask 0022
-export PATH=\$PATH:/usr/sbin:/sbin
 
-DOPATH="/home/share/slackware/slackstuff"
-export PATH=\$DOPATH:\$PATH
+add_path()
+{
+	local that=$1
+	[ -d "\$that" ] && export PATH=\$PATH:\$that
+}
 
-DOPATH="\$HOME/.local/bin"
-export PATH=\$DOPATH:\$PATH
+add_path /usr/sbin
+add_path /sbin
+add_path $MY1PATH
+add_path \$HOME/.local/bin
 
 [ -f ~/.bashrc ] && source ~/.bashrc
 [ -n "\$SSH_CLIENT" ] && export PS1="(SSH) \$PS1"
@@ -29,9 +33,7 @@ MY1_FILE_BASH_PROFILE=".bash_profile"
 MY1_BASHRC=$(cat <<SETVAR2
 # ~/.bashrc: non-login shells
 
-[ "\$(echo \$PS1|sed 's/\\\\u@\\\\h:\\\\w\\\$\\s*//g')" == "\$(echo \$PS1)" ] &&
-	export PS1="\\u@\\h:\\w\$ "
-
+export PS1="\\u@\\h:\\w\$ "
 export VISUAL="\$(which vim 2>/dev/null)"
 export HISTIGNORE="&:[bf]g:exit:[ ]*"
 export LS_OPTIONS="-F -b -T 0 --color=auto"
@@ -54,17 +56,12 @@ CHK_PATH="$HOME"
 GO_WRITE=""
 while [ "$1" != "" ]; do
 	case $1 in
-		--write)
-			GO_WRITE=$1;
+		--write) GO_WRITE=$1; ;;
+		--path) shift
+			[ ! -d $1 ] && echo "Invalid path '$1'!" && exit 1
+			CHK_PATH=`cd $1 ; pwd`
 			;;
-		--path)
-			shift
-			[ ! -d $1 ] && echo "Unknown path '$1'!" && exit 1
-			CHK_PATH=`cd $1 ; pwd`;
-			;;
-		*)
-			echo "Unknown parameter '$1'!" && exit 1
-			;;
+		*) echo "Unknown parameter '$1'!" && exit 1 ;;
 	esac
 	shift
 done
@@ -74,29 +71,25 @@ if [ "$GO_WRITE" == "--write" ]; then
 	echo -n "Writing to $CHK_PATH/$MY1_FILE_BASH_PROFILE..."
 	echo "$MY1_BASH_PROFILE" >$CHK_PATH/$MY1_FILE_BASH_PROFILE
 	echo "done."
+	echo
+	echo -n "Writing to $CHK_PATH/$MY1_FILE_BASHRC..."
+	echo "$MY1_BASHRC" >$CHK_PATH/$MY1_FILE_BASHRC
+	echo "done."
+	echo
+	echo -n "Writing to $CHK_PATH/$MY1_FILE_BASH_LOGOUT..."
+	echo "$MY1_BASH_LOGOUT" >$CHK_PATH/$MY1_FILE_BASH_LOGOUT
+	echo "done."
 else
 	echo "-------------"
 	echo "BASH_PROFILE: ($CHK_PATH/$MY1_FILE_BASH_PROFILE)"
 	echo "-------------"
 	echo "$MY1_BASH_PROFILE"
-fi
-echo
-if [ "$GO_WRITE" == "--write" ]; then
-	echo -n "Writing to $CHK_PATH/$MY1_FILE_BASHRC..."
-	echo "$MY1_BASHRC" >$CHK_PATH/$MY1_FILE_BASHRC
-	echo "done."
-else
+	echo
 	echo "-------"
 	echo "BASHRC: ($CHK_PATH/$MY1_FILE_BASHRC)"
 	echo "-------"
 	echo "$MY1_BASHRC"
-fi
-echo
-if [ "$GO_WRITE" == "--write" ]; then
-	echo -n "Writing to $CHK_PATH/$MY1_FILE_BASH_LOGOUT..."
-	echo "$MY1_BASH_LOGOUT" >$CHK_PATH/$MY1_FILE_BASH_LOGOUT
-	echo "done."
-else
+	echo
 	echo "------------"
 	echo "BASH_LOGOUT: ($CHK_PATH/$MY1_FILE_BASH_LOGOUT)"
 	echo "------------"
