Updated chksum to include sha256/sha512

diff --git a/chksum b/chksum
--- a/chksum
+++ b/chksum
@@ -4,50 +4,67 @@
 # - written by azman@my1matrix.net
 # - create and check MD5 sum hashes
 
-MY1TOOL="$(basename $0 .sh)"
-MY1PATH="$(dirname $0)"
-CURPATH="$(pwd)"
-MD5FILE=${MD5FILE:="check.md5"}
+CURR_PATH=`pwd`
+THAT_NAME=${THAT_NAME:="md5"}
+THAT_EXEC=${THAT_EXEC:="${THAT_NAME}sum"}
+THAT_FILE=${THAT_FILE:="check.${THAT_NAME}"}
 
-# tool & env setup
-MD5SUM_BIN=${MD5SUM_BIN:="$(which md5sum 2>/dev/null)"}
-[ "$MD5SUM_BIN" = "" ] && echo "md5sum binary NOT found! Aborting!" && exit 1
+# check if sha256 requested
+if [ "$(echo $@|grep -- '--sha256')" != "" ]; then
+	THAT_NAME="sha256"
+	THAT_EXEC="${THAT_NAME}sum"
+	THAT_FILE="check.${THAT_NAME}"
+elif [ "$(echo $@|grep -- '--sha512')" != "" ]; then
+	THAT_NAME="sha512"
+	THAT_EXEC="${THAT_NAME}sum"
+	THAT_FILE="check.${THAT_NAME}"
+fi
+
+# find binary
+THAT_FULL=`which $THAT_EXEC 2>/dev/null`
+[ "$THAT_FULL" = "" ] &&
+	echo "$THAT_EXEC binary NOT found! Aborting!" && exit 1
 
 if [ "$(echo $@|grep -- '--create')" != "" ]; then
 	if [ "$(echo $@|grep -- '--bundle')" == "" ]; then
-		CHKLIST=""
+		THAT_LIST=""
 		while [ "$1" != "" ] ; do
-			[ -f "$1" ] && CHKLIST="$CHKLIST $1"
+			[ -f $1 ] && THAT_LIST="$THAT_LIST $1"
 			shift
 		done
-		[ "$CHKLIST" == "" ] && CHKLIST=`find . -maxdepth 1 -type f`
-		for a in ${CHKLIST} ; do
-			a=$(basename $a)
-			[ "$(echo $a|grep ".md5")" != "" ] && continue
-			echo -n "Creating sum for $a... "
-			md5sum $a >${a}.md5
+		[ "$THAT_LIST" == "" ] &&
+			THAT_LIST=`find . -maxdepth 1 -type f`
+		for temp in $THAT_LIST ; do
+			TEMP_FILE=`basename $temp`
+			flag=`echo $TEMP_FILE|grep "$THAT_NAME"`
+			[ "$flag" != "" ] && continue
+			echo -n "Creating checksum for $TEMP_FILE... "
+			$THAT_FULL $TEMP_FILE >$temp.$THAT_NAME
 			echo "done."
 		done
 	else
-		echo -n "" >$MD5FILE
-		for a in $(find . -type f); do
-			a=$(basename $a)
-			[ "$a" == "$MD5FILE" ] && continue
-			md5sum $a >>$MD5FILE
+		echo -n "" >$THAT_FILE
+		for temp in `find . -type f`; do
+			TEMP_FILE=`basename $temp`
+			[ "$TEMP_FILE" == "$THAT_FILE" ] && continue
+			TEMP_PICK=`echo $temp | sed 's|^\./\(.*\)$|\1|'`
+			echo -n "Creating checksum for $TEMP_PICK... "
+			$THAT_FULL $TEMP_PICK >>$THAT_FILE
+			echo "done. ($THAT_FILE)"
 		done
 	fi
 else
-	if [ -r "$MD5FILE" ] ; then
-		$MD5SUM_BIN --check $MD5FILE
+	if [ -r "$THAT_FILE" ] ; then
+		$THAT_FULL --check $THAT_FILE
 		[ $? -ne 0 ] && echo "Checksum error found?!" && exit 1
 	else
-		MD5LIST="$(find . -maxdepth 1 -name "*.md5")"
-		[ "$MD5LIST" == "" ] && echo "Cannot find any MD5 sum file!" && exit 0
-		for a in $MD5LIST; do
-			a=$(basename $a)
+		THAT_LIST=`find $CURR_PATH -maxdepth 1 -name "*.$THAT_NAME"`
+		[ "$THAT_LIST" == "" ] &&
+			echo "Cannot find any $THAT_NAME sum file!" && exit 0
+		for temp in $THAT_LIST; do
 			echo -n "Checking... "
-			$MD5SUM_BIN --check $a
-			[ $? -ne 0 ] && echo "sum error?! ($a)" && continue
+			$THAT_FULL --check $temp
+			[ $? -ne 0 ] && echo "sum error?! ($temp)" && continue
 		done
 	fi
 fi
