Apparently, depstool script is far from being production-ready
- searching package deps is a pill! :p

diff --git a/depstool b/depstool
--- a/depstool
+++ b/depstool
@@ -9,31 +9,6 @@ TOOL_NAME=`basename $0`
 TOOL_PATH=`dirname $0`
 TOOL_PATH=`cd $TOOL_PATH;pwd`
 
-find_exec_fullpath()
-{
-	local func="get_exec_fullpath()"
-	[ ! -z "${exec+x}" ] && echo "$func: Var 'exec' NOT defined!" && exit 1
-	local pick=$1
-	local full=`which $pick 2>/dev/null`
-	[ ! -x "$full" ] && echo "$func: Cannot find executable '$pick'!" && exit 1
-	# check if a link
-	if [ -L "$full" ] ; then
-		full=`readlink -f $full`
-		echo "Executable '$pick' is a link to '$full'!"
-	fi
-	# must be a binary
-	local test=`file -b $full | cut -d' ' -f1`
-	[ "$test" != "ELF" ] && echo "$func: $full is NOT in ELF format!" && exit 1
-	exec=$full
-}
-
-exec_is_static()
-{
-	local exec=$1
-	local test=`file -b $exec | grep "statically linked"`
-	[ "$test" = "" ] && return 1 || return 0
-}
-
 find_package_file()
 {
 	local test find pack full=$1
@@ -44,8 +19,42 @@ find_package_file()
 	echo -n "$find"
 }
 
-# shows package for exec
-show_pack_for()
+# shows package for file - OK
+show_file_pack()
+{
+	local pick=$1
+	echo -n "Looking for package containing '$pick'... "
+	local that=`find_package_file $pick`
+	[ "$that" = "" ] && echo "not found!" && exit 1
+	echo "done."
+	echo "File:'$pick'"
+	echo "Pack:'$that'"
+}
+
+exec_NOT_binary()
+{
+	local test=`file -b $1 | cut -d' ' -f1`
+	[ "$test" != "ELF" ] && return 0 || return 1
+}
+
+find_exec_fullpath()
+{
+	local func="find_exec_fullpath()"
+	[ ! -z "${exec+x}" ] && echo "$func: Var 'exec' NOT defined!" && exit 1
+	local pick=$1
+	local full=`which $pick 2>/dev/null`
+	[ ! -x "$full" ] && echo "$func: Cannot find executable '$pick'!" && exit 1
+	# check if a link
+	if [ -L "$full" ] ; then
+		full=`readlink -f $full`
+		echo "Executable '$pick' is a link to '$full'!"
+	fi
+	exec_NOT_binary $full && echo "$func: $full NOT in ELF format!" && exit 1
+	exec=$full
+}
+
+# shows package for exec - OK
+show_exec_pack()
 {
 	local pick=$1
 	local exec ; find_exec_fullpath $pick
@@ -56,6 +65,32 @@ show_pack_for()
 	echo "done."
 	echo "Binary: '$pick' ($exec)"
 	echo "Package: $that"
+}
+
+list_that_deps()
+{
+	local exec=$1
+	local list=`ldd $exec 2>/dev/null | awk '{print $1}'`
+	[ "$list" = "" ] && return
+	local that test deps
+	for that in $list ; do
+		that=`basename $that`
+		test=${that%%.*}
+		[ "$test" = "linux-vdso" ] && continue
+		[ "${test//ld-linux-/}" != "$test" ] && continue
+		[ "$deps" = "" ] && deps=$that || deps="$deps $that"
+	done
+	echo -n "$deps"
+}
+
+# shows deps list - 4DEBUG - OK
+show_deps_raw()
+{
+	local pick=$1
+	exec_NOT_binary $pick && echo "$pick NOT in ELF format!" && exit 1
+	echo "Binary: '$pick'"
+	echo -n "Deps: "
+	list_that_deps $pick ; echo
 }
 
 show_waiting()
@@ -72,8 +107,10 @@ find_deps_package()
 {
 	local exec=$1
 	local tlib pack libz
+	local temp=`list_that_deps $exec`
+	[ "$temp" = "" ] && return
 	local wait=1
-	for tlib in `ldd $exec 2>/dev/null | awk '{print $1}'` ; do
+	for tlib in $temp ; do
 		show_waiting
 		pack=`find_package_file $tlib`
 		[ "$pack" = "" ] && continue
@@ -88,7 +125,7 @@ find_deps_package()
 }
 
 # shows package for exec, and all package deps
-show_deps_for()
+show_exec_deps()
 {
 	local pick=$1
 	local exec ; find_exec_fullpath $pick
@@ -107,19 +144,23 @@ show_deps_for()
 	for pack in $libs ; do echo -ne "\n  $pack" ; done ; echo
 }
 
-# shows deps for single exec
-show_exec_deps()
+exec_is_static()
 {
-	local func="show_exec_deps()"
+	local test=`file -b $1 | grep "statically linked"`
+	[ "$test" = "" ] && return 1 || return 0
+}
+
+# shows deps for file (single exec)
+show_file_deps()
+{
+	local func="show_file_deps()"
 	local pick=$1
 	[ ! -f "$pick" ] && echo "$func: Cannot find $pick!" && exit 1
 	local base=`basename $pick`
 	local path=`dirname $pick`
 	path=`cd $path;pwd`
 	local full=$path/$base
-	# must be a binary
-	local test=`file -b $full | cut -d' ' -f1`
-	[ "$test" != "ELF" ] && echo "$func: $pick is NOT in ELF format!" && exit 1
+	exec_NOT_binary $full && echo "$func: $pick NOT in ELF format!" && exit 1
 	exec_is_static $full &&  echo "$pick ($full) is a static binary!" && return
 	echo -n "Looking for package(s) '$pick' depends on... "
 	local libs ; find_deps_package $full
@@ -133,10 +174,49 @@ show_exec_deps()
 find_install_name()
 {
 	local name=$1
-	local temp=" ${name}-[^-]*-[^-]*-[^-]*$"
+	local temp="${name}-[^-]*-[^-]*-[^-]*$"
 	local logs="/var/log/packages"
 	local base=`ls $logs | grep -e "$temp"`
 	echo -n "$base"
+}
+
+show_pack_full()
+{
+	local name=$1
+	[ -z "$name" ] && echo "No package name given!" && exit 1
+	local full=`find_install_name $name`
+	echo "Package: '$name' => '$full'"
+}
+
+list_package_shared()
+{
+	local base=$1 # e.g. aaa_base-14.2-x86_64-2
+	local info="/var/log/packages/$base"
+	[ ! -f "$info" ] && return
+	local that full wait=1
+	for that in `cat $info | sed -e '1,/FILE LIST/d'` ; do
+		show_waiting
+		[ "${that//.so./}" = "$that" ] && continue
+		[ "$full" = "" ] && full=$that || full="$full $that"
+	done
+	wait=0 ; show_waiting
+	[ -z "${list+x}" ] && list=$full
+}
+
+show_find_raw()
+{
+	local pick=$1 # can be any name to look for
+
+
+	local name=$1
+	[ -z "$name" ] && echo "No package name given!" && exit 1
+	local full=`find_install_name $name`
+	echo "Package: '$name' => '$full'"
+	echo -n "Looking for shared objects... "
+	local list ; list_package_shared $full
+	[ -z "$list" ] && echo "-- No shared library." && return
+	local that
+	for that in $list ; do echo "-- $that" ; done
 }
 
 list_package_exec()
@@ -201,11 +281,15 @@ THAT_TASK=$1 ; shift
 THAT_PICK=$1 ; shift
 
 case "$THAT_TASK" in
-	pack4exec) show_pack_for $THAT_PICK ;;
-	deps4exec) show_deps_for $THAT_PICK ;;
-	deps4bin) show_exec_deps $THAT_PICK ;;
+	pack4file) show_file_pack $THAT_PICK ;;
+	pack4exec) show_exec_pack $THAT_PICK ;;
+	raw_deps) show_deps_raw $THAT_PICK ;; # 4DEBUG
+	deps4exec) show_exec_deps $THAT_PICK ;;
+	deps4file) show_file_deps $THAT_PICK ;;
 	bins4pack) show_pack_bins $THAT_PICK ;;
 	deps4pack) show_pack_deps $THAT_PICK ;;
+	packfull) show_pack_full $THAT_PICK ;;
+	raw_find) show_find_raw $THAT_PICK ;;
 	*) [ "$THAT_TASK" != "" ] && echo "Unknown task '$THAT_TASK'!" ;;
 esac
 
