Bugfix Commit
- minor bugfix for edkbuild (return value was not valid)
- added skip/stop function for video clip extraction...

diff --git a/edkbuild b/edkbuild
--- a/edkbuild
+++ b/edkbuild
@@ -343,14 +343,10 @@ function build_ace()
 	build_download
 
 	# genace option
-	local VSK_GENACE_OPT="-jprog \n
-	-board user \n
-	-target mdm \n
-	-hw $FPGA_DOWNLOAD_FILE \n
-	-elf $APP_EXECUTABLE \n
-	-configdevice devicenr 1 idcode 0x0384e093 irlength 6 partname xc3sd3400a \n
-	-debugdevice devicenr 1 cpunr 0 \n
-	-ace $FPGA_ACEFILE\n"
+	local VSK_GENACE_OPT="-jprog\n-board user\n-target mdm\n"
+	VSK_GENACE_OPT+="-hw $FPGA_DOWNLOAD_FILE\n-elf $APP_EXECUTABLE\n"
+	VSK_GENACE_OPT+="-configdevice devicenr 1 idcode 0x0384e093 irlength 6 partname xc3sd3400a\n"
+	VSK_GENACE_OPT+="-debugdevice devicenr 1 cpunr 0\n-ace $FPGA_ACEFILE\n"
 	# options for genace.tcl
 	local ACE_GENACE_OPT=${ACE_GENACE_OPT:="$VSK_GENACE_OPT"}
 	local TEMP_GENACE_OPT=${TEMP_GENACE_OPT:="genace.opt"}
@@ -366,9 +362,9 @@ function build_ace()
 	echo "$header_msg"
 	for (( a=0;a<${#header_msg};a++ )) ; do echo -n "$banner_char"; done ; echo
 	echo -e "$ACE_GENACE_OPT" >$TEMP_GENACE_OPT
+	rm -rf $FPGA_ACEFILE
 	xmd -tcl genace.tcl -opt $TEMP_GENACE_OPT >> $EDK_LOGFILE
-	check_result=$?
-	[[ $check_result -ne 0 ]] && echo -e "[$TOOL_THISFILE] xmd error? [$check_result] Aborting...\n" && exit 1
+	[[ ! -f "$FPGA_ACEFILE" ]] && echo -e "[$TOOL_THISFILE] xmd error? Aborting...\n" && exit 1
 	rm $TEMP_GENACE_OPT
 }
 
diff --git a/video-tool b/video-tool
--- a/video-tool
+++ b/video-tool
@@ -26,6 +26,8 @@ VIDEO_OUTTMP=""
 RUN_TESTCODE=""
 RUN_QUIET="-quiet"
 SINGLE_PASS_OPT=""
+SKIP_OPT=""
+STOP_OPT=""
 
 AVIGAIN_DB_VALUE="100"
 DO_AVIGAIN=""
@@ -137,13 +139,29 @@ while [[ "$1" != "" ]]; do
 		--do-avigain )
 			DO_AVIGAIN="YES"
 			;;
+		--skip-frame )
+			shift
+			if [[ "$1" == "" ]] ; then
+				echo "Missing params [$1] for (-ss)!"
+				exit 1
+			fi;
+			SKIP_OPT="-ss $1"
+			;;
+		--stop-frame )
+			shift
+			if [[ "$1" == "" ]] ; then
+				echo "Missing params [$1] for (-endpos)!"
+				exit 1
+			fi;
+			STOP_OPT="-endpos $1"
+			;;
 		--cut-frame )
 			shift
 			if [[ "$1" == "" ]] || [[ "$2" == "" ]]; then
 				echo "Missing params [$1] for (-ss) and [$2] for (-endpos)!"
 				exit 1
 			fi;
-			SINGLE_PASS_OPT="-ss $1 -endpos $2 -ovc copy -oac copy"
+			SINGLE_PASS_OPT="-forceidx -ss $1 -endpos $2 -ovc copy -oac copy"
 			shift
 			;;
 		--output )
@@ -265,8 +283,8 @@ LAME_PASS1_OPT="-nosound"
 LAME_PASS2_OPT="-oac mp3lame -lameopts br=56:cbr:mode=0"
 VIDEO_OPT="-force-avi-aspect $ASPECT_RATIO -ofps 25"
 
-PASS1_OPT="$RUN_QUIET $VIDEO_INPUT $VFILTER_OPT $XVID_PASS1_OPT $AFILTER_OPT $LAME_PASS1_OPT $VIDEO_OPT -o /dev/null $DVD_SUBT_OPT"
-PASS2_OPT="$RUN_QUIET $VIDEO_INPUT $VFILTER_OPT $XVID_PASS2_OPT $AFILTER_OPT $LAME_PASS2_OPT $VIDEO_OPT -o $VIDEO_OUTPUT $DVD_SUBT_OPT"
+PASS1_OPT="$RUN_QUIET $VIDEO_INPUT $VFILTER_OPT $SKIP_OPT $STOP_OPT $XVID_PASS1_OPT $AFILTER_OPT $LAME_PASS1_OPT $VIDEO_OPT -o /dev/null $DVD_SUBT_OPT"
+PASS2_OPT="$RUN_QUIET $VIDEO_INPUT $VFILTER_OPT $SKIP_OPT $STOP_OPT $XVID_PASS2_OPT $AFILTER_OPT $LAME_PASS2_OPT $VIDEO_OPT -o $VIDEO_OUTPUT $DVD_SUBT_OPT"
 
 TEST1_OPT="$PASS1_OPT"
 TEST2_OPT="$PASS2_OPT"
