Update for getsync script
- can now manually specify target (serverURL)
- will only look for config file in pwd
- making --update switch the default
  = cannot remember why this was not the case...

diff --git a/getsync b/getsync
--- a/getsync
+++ b/getsync
@@ -7,24 +7,26 @@
 MY1TOOL="$(basename $0 .sh)"
 MY1PATH="$(dirname $0)"
 CURPATH="$(pwd)"
+CFGFILE="$CURPATH/.$MY1TOOL"
 
 # look for config file
-for conffile in "$CURPATH/.$MY1TOOL" "$HOME/.$MY1TOOL" ; do
-	[[ ! -f $conffile ]] && continue
-	source $conffile ; break
-done
-
-# enforce this!
-[[ "$RSYNCURL" == "" ]] && echo "Server URL not specified!" && exit 1
+[ -f "$CFGFILE" ] && source $CFGFILE
 
 # tool & env setup
 RSYNC=${RSYNC:="$(which rsync 2>/dev/null)"}
 RSYNCURL=${RSYNCURL:="user@server:/path/to/home/"}
-RSYNCOPT=${RSYNCOPT:="-e ssh -rpltD --partial --progress --dry-run"}
+RSYNCOPT=${RSYNCOPT:="-e ssh -rpltD --partial --progress --dry-run --update"}
 LOCALURL=${LOCALURL:="."}
 
 # make sure rsync is available!
-[[ "$RSYNC" == "" ]] && echo "Cannot find rsync!" && exit 1
+[ "$RSYNC" == "" ] && echo "Cannot find rsync!" && exit 1
+
+# first parameter CAN be a path to server URL
+[ -d "$1" ] && RSYNCURL="$(cd $1;pwd)/" && LOCALURL="." &&
+	INCLUDES="$INCLUDES --include=/" && shift
+
+# enforce this!
+[ "$RSYNCURL" == "" ] && echo "Server URL not specified!" && exit 1
 
 # check target & source
 RSYNCSRC="${RSYNCURL}"
@@ -33,11 +35,11 @@ RSYNCTGT="${LOCALURL}"
 # customized sync list
 EXCLUDES=${EXCLUDES:=""}
 INCLUDES=${INCLUDES:=""}
-[[ -r "$EXCLUDEFILE" ]] && EXCLUDES="--exclude-from=$EXCLUDEFILE"
-[[ -r "$INCLUDEFILE" ]] && INCLUDES="--include-from=$INCLUDEFILE"
+[ -r "$EXCLUDEFILE" ] && EXCLUDES="--exclude-from=$EXCLUDEFILE"
+[ -r "$INCLUDEFILE" ] && INCLUDES="--include-from=$INCLUDEFILE"
 
 # check parameters
-while  [[ "$1" != "" ]]; do
+while  [ "$1" != "" ]; do
 	case $1 in
 		--upload)
 			RSYNCTMP="${RSYNCSRC}"
@@ -50,14 +52,17 @@ while  [[ "$1" != "" ]]; do
 		--delete|--update)
 			RSYNCOPT="${RSYNCOPT} $1"
 			;;
-		--update)
-			RSYNCOPT="${RSYNCOPT} --update"
-			;;
 		--dolink)
 			RSYNCOPT="${RSYNCOPT} --copy-links --keep-dirlinks"
 			;;
 		--exec)
 			RSYNCOPT="${RSYNCOPT// --dry-run/}"
+			;;
+		--exclude*)
+			EXCLUDES="$EXCLUDES $1"
+			;;
+		--include*)
+			INCLUDES="$INCLUDES $1"
 			;;
 		*)
 			echo "Unknown parameter '$1'"
