Update Commit
- updated libmy1slack
- bugfix for getslack and slackpatch
- added description for slacktest

diff --git a/getslack b/getslack
--- a/getslack
+++ b/getslack
@@ -27,16 +27,14 @@ SLACKFULL=\${SLACKFULL:="slackware"}
 NO_KDE=\${NO_KDE:="no"}
 GO_BOOTSTRAP=\${GO_BOOTSTRAP:="no"}
 # include some wanted software in excluded path
-#INCLUDES="\$INCLUDES --include=extra/PACKAGES.TXT"
+INCLUDES="\$INCLUDES --include=extra/PACKAGES.TXT"
 #INCLUDES="\$INCLUDES --include=extra/wicd/"
-#INCLUDES="\$INCLUDES --include=extra/google-chrome/"
 #INCLUDES="\$INCLUDES --include=extra/jdk-6/"
-#INCLUDES="\$INCLUDES --include=extra/kde3-compat"
 #INCLUDES="\$INCLUDES --include=extra/source/"
 #INCLUDES="\$INCLUDES --include=extra/source/flashplayer-plugin/"
 # exclude non-essentials
-EXCLUDES="\$EXCLUDES --exclude=extra/"
-#EXCLUDES="\$EXCLUDES --exclude=extra/*"
+#EXCLUDES="\$EXCLUDES --exclude=extra/"
+EXCLUDES="\$EXCLUDES --exclude=extra/*"
 #EXCLUDES="\$EXCLUDES --exclude=extra/source/*"
 # exclude non-standard
 EXCLUDES="\$EXCLUDES --exclude=pasture/ --exclude=testing/"
@@ -62,7 +60,7 @@ EXCLUDES="\$EXCLUDES --exclude=source/kdei/ --exclude=source/y/"
 [[ "\$GO_BOOTSTRAP" == "yes" ]] && EXCLUDES="\$EXCLUDES --exclude=\${SLACKFULL}/xap/ --exclude=source/xap/"
 MY1CONF
 )
-if [[ "$1" == "--write" ]]; then
+if [[ "$1" == "--config" ]]; then
 	echo "$MY1_GETSLACK_CONF" >$HOME/.$MY1TOOL
 	echo "New config file ($HOME/.$MY1TOOL) written!"
 	exit 0
@@ -89,8 +87,9 @@ if [[ "$1" == "--mkiso" ]]; then
 	[[ "$MKISOFS" == "" ]] && echo "'mkisofs' not found! Aborting!" && exit 1
 	ISOPATH=${ISOPATH:="$HOME/temp"}
 	[[ ! -d "$ISOPATH"  ]] && echo "Path '$ISOPATH' not found! Aborting!" && exit 1
-	echo -n "Creating ISO from $SLACKPATH... "
+	[[ ! -d "$SLACKPATH" ]] && echo "Path '$SLACKPATH' not found! Aborting!" && exit 1
 	cd $SLACKPATH
+	echo -n "Creating ISO from $SLACKPATH... "
 	$MKISOFS -o $ISOPATH/${SLACKRELEASE}-install.iso -V "${SLACKRELEASE} Install DVD" \
 		-R -J -hide-rr-moved -hide-joliet-trans-tbl -d -N \
 		-v -v -no-emul-boot -boot-load-size 32 -boot-info-table \
diff --git a/libmy1slack b/libmy1slack
--- a/libmy1slack
+++ b/libmy1slack
@@ -5,7 +5,7 @@
 # - library functions for slackware system management
 
 MY1_LIBNAME="libmy1slack"
-MY1_LIBVERS="2012.03.00"
+MY1_LIBVERS="2012.07.00"
 MY1_LIBCALL="$(basename $0 .sh)"
 
 # determine slackware architecture, NOT machine's!
@@ -42,18 +42,41 @@ SLACKPKGFILE=${SLACKPKGFILE:="${SLACKPKGPATH}/PACKAGES.TXT"}
 SLACKEXTFILE=${SLACKEXTFILE:="${SLACKEXTPATH}/PACKAGES.TXT"}
 SLACKINSTLOG="/var/log/packages"
 
+function error_exit()
+{
+	echo -e "\033[1;31m[ERROR]\033[0;31m $1 Aborting!\033[0m\n" 1>&2
+	exit 1
+}
+
+function debug_msg()
+{
+	echo -e "\033[1;32m[DEBUG]\033[0;32m $1\033[0m" 1>&2
+}
+
+function warn_msg()
+{
+	echo -e "\033[1;33m[WARN]\033[0;33m $1\033[0m" 1>&2
+}
+
+function info_msg()
+{
+	echo -e "\033[1;34m[INFO]\033[0;34m $1\033[0m"
+}
+
 if [[ "$MY1_DEBUG" == "YES" ]]; then
 	echo
-	echo "[DEBUG-$$] ==> my1slack Library Name is $MY1_LIBNAME"
-	echo "[DEBUG-$$] ==> my1slack Library Version is $MY1_LIBVERS"
-	echo "[DEBUG-$$] ==> Slack Release is $SLACKRELEASE"
-	echo "[DEBUG-$$] ==> Slack Tree is at $SLACKROOTDIR"
-	echo "[DEBUG-$$] ==> Command Call '$MY1_LIBCALL'"
+	debug_msg "my1slack Library Name is $MY1_LIBNAME"
+	debug_msg "my1slack Library Version is $MY1_LIBVERS"
+	debug_msg "System machine is $(uname -m)"
+	debug_msg "Slack Version is $(cat /etc/slackware-version)"
+	debug_msg "Slack Release is $SLACKRELEASE"
+	debug_msg "Slack Tree is at $SLACKROOTDIR"
+	debug_msg "Command Call '$MY1_LIBCALL'"
 fi
 
 function must_be_root()
 {
-	[[ $UID -ne 0 ]] && echo -e "Abort: must run as root!\n" && exit 1
+	[[ $UID -ne 0 ]] && error_exit "Must run as root!"
 }
 
 function get_pkg_info()
@@ -232,7 +255,7 @@ function find_package()
 	local pkg_test="$1"
 	local pkg_temp="\<PACKAGE NAME:  ${pkg_test}-[^-]*-[^-]*-[^-]*\.t[gx]z\>"
 	local pkg_file=$(cat $SLACKPKGFILE | grep -e "$pkg_temp")
-	[[ "$pkg_file" == "" ]] &&
+	[[ "$pkg_file" == "" ]] && [[ -f $SLACKEXTFILE ]] &&
 		pkg_file=$(cat $SLACKEXTFILE | grep -e "$pkg_temp")
 	[[ "$pkg_file" == "" ]] && return
 	pkg_file="${pkg_file##* }"
@@ -359,27 +382,4 @@ function format_text()
 		shift
 	done
 	echo -e "$text"
-}
-
-function test_param()
-{
-	# just testing...
-	local test="$@"
-	# show parameters
-	echo "Param count: $#"
-	echo "Param \$@ is $@"
-	echo "Param \$* is $*"
-	echo "Param \$1 is $1"
-	echo "Param \$test is $test"
-	shift
-	echo "Params shifted by 1!"
-	# $* similar to $@, but use IFS as separator
-	test="$@"
-	echo "Param count: $#"
-	echo "Param \$@ is $@"
-	echo "Param \$* is $*"
-	echo "Param \$1 is $1"
-	echo "Param \$test is $test"
-	shift
-	echo "Param \$\$ is $$"
 }
