Code cleanup
- bugfix in getslackbuild due to libmy1slack structure update

diff --git a/getslack b/getslack
--- a/getslack
+++ b/getslack
@@ -5,7 +5,6 @@
 # - a 'reduced' version of alien_bob's mirror_slackware_current.sh
 
 TOOL_NAME=`basename $0 .sh`
-TOOL_PATH=`dirname $0`
 # look for config file
 for conf in `pwd`/.$TOOL_NAME $HOME/.$TOOL_NAME ; do
 	[ -r $conf ] && source $conf && break
@@ -21,21 +20,15 @@ done
 	SLACKVERS=`cat /etc/slackware-version | sed 's/Slackware //'`
 SLACKFULL=$SLACKNAME-$SLACKVERS
 SLACKTREE=$SLACKROOT/$SLACKFULL
-# capture error in sub-shells
-set -e # activates errexit
-# setup rsync stuffs (e.g. default rsync url)
+# setup rsync stuffs
+RSYNC_BIN=`which rsync 2>/dev/null`
+[ "$RSYNC_BIN" == "" ] && echo "Cannot find rsync!" && exit 1
 [ -z "$RSYNCURLROOT" ] && RSYNCURLROOT="slackware.mirrors.tds.net::slackware/"
 RSYNC_URL="$RSYNCURLROOT$SLACKFULL/"
 RSYNC_OPT="--delete --delete-excluded --partial -rlptD --progress"
-# check if rsync binary is available
-RSYNC_BIN=`which rsync 2>/dev/null`
-[ "$RSYNC_BIN" == "" ] && echo "Cannot find rsync! Aborting!" && exit 1
-# customized default sync list
-[ -z "$EXCLUDES" ] && EXCLUDES="--exclude=source/"
 # start actual mirroring process - reduced version of alien_bob's script
 echo -e "#\n# Checking and changing to $SLACKTREE ...\n#"
-[ ! -d $SLACKTREE ] && mkdir -pv $SLACKTREE
-cd $SLACKTREE
+[ ! -d $SLACKTREE ] && mkdir -pv $SLACKTREE ; cd $SLACKTREE
 echo "*** Using $RSYNC_URL ***"
 $RSYNC_BIN $RSYNC_OPT $INCLUDES $EXCLUDES $RSYNC_URL $SLACKTREE
 echo "*** Using $RSYNC_URL - (2nd Run) ***"
diff --git a/getslackbuild b/getslackbuild
--- a/getslackbuild
+++ b/getslackbuild
@@ -6,33 +6,54 @@
 
 TOOL_NAME=`basename $0 .sh`
 TOOL_PATH=`dirname $0`
+TOOL_PATH=`cd $TOOL_PATH ; pwd`
 # look for config file
-for config in `pwd` $HOME; do
-	config=$config/.$TOOL_NAME
-	[ -r $config ] && source $config && break
+for conf in `pwd` $HOME; do
+	conf=$conf/.$TOOL_NAME
+	[ -r $conf ] && . $conf && break
 done
-
-# find libraries
-[ ! -f $TOOL_PATH/libmy1slack ] &&
-	echo "Cannot find libmy1slack!" && exit 1
-. $TOOL_PATH/libmy1slack
-must_have_file $TOOL_PATH/libmy1get
-. $TOOL_PATH/libmy1get
-
+# look for library scripts
+source_lib()
+{
+	local name=$1
+	local full=$TOOL_PATH/$name
+	[ ! -f "$full" ] && echo "Cannot find $full!" && exit 1
+	. $full
+}
+source_lib libmy1slack
+source_lib libmy1echo
+source_lib libmy1file
+source_lib libmy1get
 # temporary path
 TOOL_USER=`whoami`
 TOOL_TEMP="/tmp/$TOOL_USER/$TOOL_NAME"
-
 # tool specific
 TOOL_DESC="my1 SlackBuilds.org Executor"
-TOOL_VERS="2019.07.00"
+TOOL_VERS="2019.11.00"
+TOOL_HELP=`cat <<SETHELPMSG
+Usage:
+  $TOOL_NAME [options] <pkg_name>
+Options:
+  --path|-p </path/to/slackbuilds>
+  --pack|-f </sub/path/to/package/group>
+  --depends | -d : Check (and build) dependencies
+  --update  | -u : Fetch new build script if available
+  --install | -i : Install when (and if) the build completes
+  --execute | -x : Execute build (else, simply check @ dry-run)
+  --buildup | -b : Force build even already installed
+  --verbose | -v : Show more information (for --check-installed)
+              -l : List ALL local scripts (without updating)
+              -s : Use existing package list (no internet update)
+              -a : Update all locally saved build scripts
+              -r : Check reverse dependencies
+              -c : Compare installed version against build script
+SETHELPMSG`
 TOOL_PDIR=`dirname $TOOL_PATH`
 WORK_PATH="$TOOL_PDIR/slackbuilds"
 CURR_PATH=`pwd -P`
 PACK_PATH="test-pack" # default package path
-[ -z "$SLACKNAME" ] && [ -n "$ARCH" ] && [ "$ARCH" = "x86_64" ] &&
-	SLACKNAME="slackware64" || SLACKNAME="slackware"
-[ -z "$SLACKVERS" ] && [ -n "$VERS" ] && SLACKVERS=$VERS || SLACKVERSE="current"
+
+# setup here to use SLACK* variables
 call_setup
 BUILD_URL="http://slackbuilds.org/slackbuilds/$SLACKVERS"
 BUILDLIST="SLACKBUILDS.TXT"
@@ -52,24 +73,6 @@ OPT_CHK_SYS="NO"
 OPT_BUILDUP="NO"
 OPT_VERBOSE="NO"
 OPT_REVDEPS="NO"
-MSG_THISHELP=`cat <<SETHELPMSG
-Usage:
-  $TOOL_NAME [options] <pkg_name>
-Options:
-  --path|-p </path/to/slackbuilds>
-  --pack|-f </sub/path/to/package/group>
-  --depends | -d : Check (and build) dependencies
-  --update  | -u : Fetch new build script if available
-  --install | -i : Install when (and if) the build completes
-  --execute | -x : Execute build (else, simply check @ dry-run)
-  --buildup | -b : Force build even already installed
-  --verbose | -v : Show more information (for --check-installed)
-              -l : List ALL local scripts (without updating)
-              -s : Use existing package list (no internet update)
-              -a : Update all locally saved build scripts
-              -r : Check reverse dependencies
-              -c : Compare installed version against build script
-SETHELPMSG`
 
 info_build()
 {
@@ -534,58 +537,23 @@ process_command()
 	# check parameters
 	while [ "$1" != "" ]; do
 		case "$1" in
-			--install|-i)
-				OPT_INSTALL="--install"
-				;;
-			--depends|-d)
-				OPT_DEPENDS="YES"
-				;;
-			-r)
-				OPT_REVDEPS="YES"
-				;;
-			--execute|-x)
-				OPT_EXECUTE="YES"
-				;;
-			--update|-u)
-				OPT_CLEANUP="YES"
-				OPT_WARNOLD="YES"
-				;;
-			-a)
-				OPT_ALL_NEW="YES"
-				;;
-			-c)
-				OPT_CHK_SYS="YES"
-				;;
-			--verbose|-v)
-				OPT_VERBOSE="YES"
-				;;
-			-l)
-				OPT_LISTALL="YES"
-				;;
-			-s)
-				OPT_LISTOLD="YES"
-				;;
-			--buildup|-b)
-				OPT_BUILDUP="YES"
-				;;
-			--path|-p)
-				shift
-				must_have_path $1 "Invalid path '$1'!"
-				WORK_PATH=`cd $1;pwd`
-				;;
-			--pack|-f)
-				shift
-				PACK_PATH="$1"
-				;;
-			-*)
-				echo -e "$MSG_THISHELP\n"
-				echo -e "[ERROR] Unknown option '$1'!\n" ; exit 1
-				;;
-			*)
-				[ "$pkg_name" != "" ] &&
-					echo -e "[ERROR] Multiple package? [$pkg_name]\n" && exit 1
-				pkg_name="$1"
-				;;
+			--install|-i) OPT_INSTALL="--install" ;;
+			--depends|-d) OPT_DEPENDS="YES" ;;
+			--execute|-x) OPT_EXECUTE="YES" ;;
+			--update|-u) OPT_CLEANUP="YES" ; OPT_WARNOLD="YES" ;;
+			--verbose|-v) OPT_VERBOSE="YES" ;;
+			--buildup|-b) OPT_BUILDUP="YES" ;;
+			--path|-p) shift ; must_have_path $1 ; WORK_PATH=`cd $1;pwd` ;;
+			--pack|-f) shift ; PACK_PATH="$1" ;;
+			-r) OPT_REVDEPS="YES" ;;
+			-a) OPT_ALL_NEW="YES" ;;
+			-c) OPT_CHK_SYS="YES" ;;
+			-l) OPT_LISTALL="YES" ;;
+			-s) OPT_LISTOLD="YES" ;;
+			-*) error_exit "Unknown option '$1'!\n\n" ;;
+			*) [ "$pkg_name" != "" ] &&
+					error_exit "Unknown parameter '$1'\n\n"
+				pkg_name="$1" ;;
 		esac
 		shift
 	done
@@ -600,7 +568,7 @@ process_command()
 	# check option to check installed build script(s)
 	[ "$OPT_CHK_SYS" == "YES" ] && do_check_installed && exit 0
 	# check if name supplied
-	[ "$pkg_name" == "" ] && echo -e "$MSG_THISHELP\n" && exit 0
+	[ "$pkg_name" == "" ] && echo -e "$TOOL_HELP\n" && exit 0
 	# check option to check dependents
 	[ "$OPT_REVDEPS" == "YES" ] && do_check_reversedeps $pkg_name && exit 0
 	# check if package path supplied
diff --git a/getslackpack b/getslackpack
--- a/getslackpack
+++ b/getslackpack
@@ -5,7 +5,6 @@
 # - standalone slackware package retriever
 
 TOOL_NAME=`basename $0 .sh`
-TOOL_PATH=`dirname $0`
 # look for config file
 for conf in `pwd`/.$TOOL_NAME $HOME/.$TOOL_NAME ; do
 	[ -r $conf ] && source $conf && break
@@ -26,16 +25,12 @@ TOOL_USER=`whoami`
 TOOL_TEMP="/tmp/$TOOL_USER/$TOOL_NAME"
 # x86 packages usually target specific arch - used in salix/rwork repos!
 [ -z "$ARCH_X86" ] && ARCH_X86="i486"
-case $SLACKARCH in
-	x86|i*86) SLACKARCH=$ARCH_X86 ;;
-esac
-
+case $SLACKARCH in x86|i*86) SLACKARCH=$ARCH_X86 ;; esac
 # default repo - alien stuffs!
 BOB_ROOT="http://bear.alienbase.nl"
 DEF_ROOT="${BOB_ROOT}/mirrors/people/alien/slackbuilds"
 DEF_REPO="alien"
 DEF_PACK="libreoffice libreoffice-dict-en openjdk"
-
 # tool options - allow config file to set these...
 OPT_CHECK=${OPT_CHECK:="YES"}
 OPT_CLEAN=${OPT_CLEAN:="NO"}
@@ -305,12 +300,8 @@ do_readconf()
 				pkg_repo="rwork"
 				pkg_rawp=",go_raw"
 				;;
-			-*)
-				echo "Unknown repo '$1'!" >&2 && exit 1
-				;;
-			*)
-				echo "${pkg_root},${pkg_repo},$1${pkg_rawp}"
-				;;
+			-*) echo "Unknown repo '$1'!" >&2 && exit 1 ;;
+			*) echo "${pkg_root},${pkg_repo},$1${pkg_rawp}" ;;
 		esac
 		shift
 	done
@@ -502,67 +493,34 @@ do_execthis()
 chk_param()
 {
 	local chk_valid="--$DEF_REPO"
+	local opt_xfburn="--rwork xfburn libburn libisofs"
 	# check parameters
 	while [ "$1" != "" ]; do
 		case "$1" in
-			--alien)
-				chk_valid="$1"
-				;;
-			--aliensec)
-				chk_valid="$1"
-				;;
-			--slack)
-				chk_valid="$1"
-				;;
-			--salix)
-				chk_valid="$1"
-				;;
-			--rwork)
-				chk_valid="$1"
-				;;
-			--reset)
-				THIS_CONF=""
-				;;
-			--check)
-				OPT_CHECK="YES"
-				;;
-			--default)
-				THIS_CONF="${THIS_CONF} --$DEF_REPO $DEF_PACK"
-				;;
-			--xfburn)
-				THIS_CONF="${THIS_CONF} --rwork xfburn libburn libisofs"
-				;;
-			--exec)
-				OPT_CHECK="NO"
-				;;
-			--clean)
-				OPT_CLEAN="YES"
-				;;
-			--sweep)
-				OPT_SWEEP="YES"
-				;;
-			--path)
-				shift
-				[ ! -d "$1" ] && echo "[ERROR] Invalid path '$1'!" && exit 1
-				SLACKPATH=`cd $1; pwd`
-				;;
-			-*)
-				echo "[ERROR] Unknown option '$1'!"
-				exit 1
-				;;
-			*)
-				THIS_CONF="${THIS_CONF} ${chk_valid} $1 "
-				;;
+			--alien) chk_valid="$1" ;;
+			--aliensec) chk_valid="$1" ;;
+			--slack) chk_valid="$1" ;;
+			--salix) chk_valid="$1" ;;
+			--rwork) chk_valid="$1" ;;
+			--reset) THIS_CONF="" ;;
+			--check) OPT_CHECK="YES" ;;
+			--default) THIS_CONF="${THIS_CONF} --$DEF_REPO $DEF_PACK" ;;
+			--xfburn) THIS_CONF="${THIS_CONF} $opt_xfburn" ;;
+			--exec) OPT_CHECK="NO" ;;
+			--clean) OPT_CLEAN="YES" ;;
+			--sweep) OPT_SWEEP="YES" ;;
+			--path) shift
+				[ ! -d "$1" ] && echo "Invalid path '$1'!" && exit 1
+				SLACKPATH=`cd $1; pwd` ;;
+			-*) echo "[ERROR] Unknown option '$1'!" ; exit 1 ;;
+			*) THIS_CONF="${THIS_CONF} ${chk_valid} $1 " ;;
 		esac
 		shift
 	done
 }
 
-# duh!
-chk_param "$@"
-# do your thing!
+chk_param $@
 do_execthis "$(do_readconf $THIS_CONF)"
-
 # look for duplicate and delete old???
 
 exit 0
