Updated getslackbuild
- can now update all locally saved build scripts

diff --git a/getslackbuild b/getslackbuild
--- a/getslackbuild
+++ b/getslackbuild
@@ -21,6 +21,8 @@ MY1_TOOLPDIR=`dirname $MY1PATH`
 MY1_BUILDDIR=${MY1_BUILDDIR:="${MY1_TOOLPDIR}/slackbuilds"}
 MY1_THISPATH=`pwd -P`
 MY1_PACKPATH=""
+MY1_LISTFILE=""
+MY1_THISPACK=""
 [ -z "$SLACKVERS" ] && [ -n "$RELEASE" ] && SLACKVERS=$RELEASE
 SLACKVERS=${SLACKVERS:=""}
 if [ "$SLACKVERS" == "" ]; then
@@ -44,6 +46,7 @@ OPT_DEPENDS="NO"
 OPT_EXECUTE="NO"
 OPT_CLEANUP="NO"
 OPT_WARNOLD="NO"
+OPT_ALL_NEW="NO"
 MSG_THISHELP=`cat <<SETHELPMSG
 Usage:
   $MY1TOOL [options] <pkg_name>
@@ -136,19 +139,13 @@ function get_buildinfo()
 	return
 }
 
-function do_build()
+function do_list_update()
 {
-	local pkg_name=$1
-	local pkg_path=$2
-	local opt_inst=$3
-	local chk_path=${MY1_THISPATH}
-	local sav_path=${pkg_path}
-	local pkg_vers=${SLACKVERS}
-	local pkg_root="http://slackbuilds.org/slackbuilds/$pkg_vers"
 	local chk_user=`whoami`
 	local pkg_temp="/tmp/$chk_user/my1/$MY1TOOL"
+	local pkg_vers=${SLACKVERS}
+	local pkg_root="http://slackbuilds.org/slackbuilds/$pkg_vers"
 	local pkg_list="SLACKBUILDS.TXT"
-	local pkg_base
 	# prepare temp - get the list!
 	mkdir -p $pkg_temp 2>/dev/null
 	[ $? -ne 0 ] &&
@@ -166,7 +163,7 @@ function do_build()
 			gzip -d $pkg_list.gz
 		else
 			[ -r "$pkg_list" -a "$OPT_WARNOLD" = "YES" ] &&
-				echo -e "[WARNING] NOT using latest $pkg_list!\n"
+				echo -e "[WARNING] NOT using latest $pkg_list!\n" >&2
 		fi
 		cd - >/dev/null
 	fi
@@ -174,9 +171,17 @@ function do_build()
 	local tmp_list="${pkg_temp}/$pkg_list"
 	[ ! -r "$tmp_list" ] &&
 		echo -e "[ERROR] File '$tmp_list' not found!\n" >&2 && exit 1
+	MY1_LISTFILE="$pkg_root;$pkg_temp;$tmp_list"
+}
+
+function do_list_search()
+{
+	local pkg_list=$1
+	local pkg_name=$2
+	local pkg_root=$3
 	# look for pkg_name
 	local pkg_test="SLACKBUILD NAME: $pkg_name"
-	local pkg_text=`cat ${pkg_temp}/$pkg_list|grep -e "${pkg_test}$" -A10`
+	local pkg_text=`cat $pkg_list|grep -e "${pkg_test}$" -A10`
 	[ "$pkg_text" == "" ] &&
 		echo -e "[ERROR] Cannot find script for '$pkg_name'!\n" >&2 && exit 1
 	# extract info
@@ -195,66 +200,178 @@ function do_build()
 	pkg_fil2=`echo "$pkg_fil2" | sed 's/.*: \(.*\)$/\1/'`
 	local pkg_deps=`echo "$pkg_text" | grep 'SLACKBUILD REQUIRES'`
 	pkg_deps=`echo "$pkg_deps" | sed 's/.*: \(.*\)$/\1/'`
+	MY1_THISPACK="$pkg_load;$pkg_vers;$pkg_file;$pkg_fil2;$pkg_deps"
+}
+
+function do_fetch()
+{
+	local pkg_list=$1
+	local pkg_name=$2
+	local pkg_root=$3
+	local pkg_path=$4
+	local pkg_temp=$5
+	local chk_skip=0
+	# look for package in list
+	do_list_search $pkg_list $pkg_name $pkg_root
+	local pkg_info="$MY1_THISPACK"
+	local pkg_vers=`echo "$pkg_info" | cut -d';' -f2`
 	# check if local version is available
 	local tmp_vers=""
-	local pkg_info=`get_buildinfo $pkg_name $pkg_path`
-	[ "$pkg_info" != "" ] && tmp_vers=`echo "$pkg_info" | cut -d';' -f2`
-	# do we need to fetch?
-	if [ "$tmp_vers" != "$pkg_vers" ] ; then
-		if [ "$tmp_vers" == "" ] ; then
-			# look within tree?
-			local top_path=${MY1_BUILDDIR}
-			pkg_test=`find $top_path -name "$pkg_name" -type d`
-			if [ -d "$pkg_test" ] ; then
-				local tmp_path=`dirname $pkg_test`
-				pkg_info=`get_buildinfo $pkg_name $tmp_path`
-				if [ "$pkg_info" != "" ] ; then
-					tmp_vers=`echo "$pkg_info" | cut -d';' -f2`
-					pkg_path=${tmp_path}
-				fi
-			fi
-			if [ "$tmp_vers" == "" -o "$OPT_CLEANUP" == "YES" ] ; then
-				pkg_test=`dirname $pkg_load`
-				pkg_text=`basename $pkg_load`
-				cd $pkg_temp
-				wget --spider $pkg_test >/dev/null 2>&1
-				[ $? -ne 0 ] &&
-					echo -e "[ERROR] Cannot find $pkg_test!\n" >&2 && exit 1
-				# remove old tarballs?
-				rm -rf ${pkg_text}*
-				do_download $pkg_load $pkg_text 2>/dev/null
-				[ ! -r "$pkg_text" ] &&
-					echo -e "[ERROR] Cannot download $pkg_load!\n" >&2 && exit 1
-				cd - >/dev/null
-				tmp_vers=$pkg_vers
-				pkg_test=$pkg_temp/$pkg_text
-				[ ! -d "$pkg_path" ] && mkdir -p $pkg_path
-				cd $pkg_path
-				# remove old?
-				rm -rf ${pkg_name}
-				# extract accordingly?
-				tar xf $pkg_test 2>/dev/null
-				[ $? -ne 0 ] &&
-					echo -e "[ERROR] Cannot extract $pkg_test!\n" >&2 && exit 1
-				cd - >/dev/null
+	local tmp_info=`get_buildinfo $pkg_name $pkg_path`
+	if [ "$tmp_info" != "" ] ; then
+		tmp_vers=`echo "$tmp_info" | cut -d';' -f2`
+	else
+		# look within tree?
+		local top_path=${MY1_BUILDDIR}
+		local pkg_test=`find $top_path -name "$pkg_name" -type d`
+		if [ -d "$pkg_test" ] ; then
+			local tmp_path=`dirname $pkg_test`
+			tmp_info=`get_buildinfo $pkg_name $tmp_path`
+			if [ "$tmp_info" != "" ] ; then
+				tmp_vers=`echo "$tmp_info" | cut -d';' -f2`
+				pkg_path=${tmp_path}
 			fi
 		fi
 	fi
+	# do we need to fetch?
+	if [ "$tmp_vers" != "$pkg_vers" ] ; then
+		if [ "$tmp_vers" == "" -o "$OPT_CLEANUP" == "YES" ] ; then
+			local pkg_load=`echo "$pkg_info" | cut -d';' -f1`
+			local pkg_test=`dirname $pkg_load`
+			local pkg_text=`basename $pkg_load`
+			cd $pkg_temp
+			wget --spider $pkg_test >/dev/null 2>&1
+			[ $? -ne 0 ] &&
+				echo -e "[ERROR] Cannot find $pkg_test!\n" >&2 && exit 1
+			# remove old tarballs?
+			rm -rf ${pkg_text}*
+			do_download $pkg_load $pkg_text 2>/dev/null
+			[ ! -r "$pkg_text" ] &&
+				echo -e "[ERROR] Cannot download $pkg_load!\n" >&2 && exit 1
+			cd - >/dev/null
+			tmp_vers=$pkg_vers
+			pkg_test=$pkg_temp/$pkg_text
+			[ ! -d "$pkg_path" ] && mkdir -p $pkg_path
+			cd $pkg_path
+			# remove old?
+			rm -rf ${pkg_name}
+			# extract accordingly?
+			tar xf $pkg_test 2>/dev/null
+			[ $? -ne 0 ] &&
+				echo -e "[ERROR] Cannot extract $pkg_test!\n" >&2 && exit 1
+			cd - >/dev/null
+		else
+			# local version available - skip downloading tarball!
+			chk_skip=1
+		fi
+	fi
+	# true path!
 	pkg_path=${pkg_path}/${pkg_name}
 	# have we got the buildscript?
 	local pkg_exec=${pkg_path}/${pkg_name}.SlackBuild
 	[ ! -f "$pkg_exec" ] &&
 		echo -e "Script '$pkg_exec' not found!\n" && exit 1
-	# check if tarball available?
-	local pkg_ball=`basename $pkg_file`
-	[ ! -f "${pkg_path}/${pkg_ball}" ] && do_loadball $pkg_path $pkg_file
-	if [ "$pkg_fil2" != "" ] ; then
-		pkg_ball=`basename $pkg_fil2`
-		[ ! -f "${pkg_path}/${pkg_ball}" ] && do_loadball $pkg_path $pkg_fil2
+	# do we need to download?
+	if [ $chk_skip -eq 0 ] ; then
+		# check if tarball available?
+		local pkg_file=`echo "$pkg_info" | cut -d';' -f3`
+		local pkg_fil2=`echo "$pkg_info" | cut -d';' -f4`
+		local pkg_ball=`basename $pkg_file`
+		[ ! -f "${pkg_path}/${pkg_ball}" ] &&
+			do_loadball $pkg_path $pkg_file
+		if [ "$pkg_fil2" != "" ] ; then
+			pkg_ball=`basename $pkg_fil2`
+			[ ! -f "${pkg_path}/${pkg_ball}" ] &&
+				do_loadball $pkg_path $pkg_fil2
+		fi
 	fi
 	# some deps asks to refer to README
+	local pkg_deps=`echo "$pkg_info" | cut -d';' -f5`
 	[ "$pkg_deps" == "%README%" ] && pkg_deps=""
-	# show this before dependencies if not building
+	# some external function need these info
+	MY1_THISPACK="$pkg_path;$pkg_vers;$tmp_vers;$pkg_deps"
+}
+
+function do_build()
+{
+	local pkg_name=$1
+	local pkg_vers=$2
+	local pkg_path=$3
+	local pkg_temp=$4
+	local opt_inst=$5
+	# check if already installed? should check version as well?
+	local pkg_temp="^${pkg_name}-[^-]*-[^-]*-[^-]*$"
+	local pkg_root=`ls /var/log/packages | grep -e "$pkg_temp"`
+	if [ "$pkg_root" != "" ] ; then
+		# check version - stop if exactly the same!
+		pkg_temp=`echo $pkg_root | sed 's/\(.*\)-\(.*\)/\1/'`
+		pkg_temp=`echo $pkg_temp | sed 's/\(.*\)-\(.*\)/\1/'`
+		pkg_temp=`echo $pkg_temp | sed 's/\(.*\)-\(.*\)/\2/'`
+		[ "$pkg_vers" == "$pkg_temp" ] &&
+			echo "Package ${pkg_root} installed." && return
+		# continue, but do not install?
+		opt_inst=""
+	fi
+	# only root can actually build!
+	[ $UID -ne 0 ] &&
+		echo -e "Must run as root! ($pkg_name-$pkg_vers)\n" && return
+	# start build?
+	local log_file=${pkg_temp}/${pkg_name}.buildlog
+	cd ${pkg_path}
+	[ ! -f "${pkg_name}.SlackBuild" ] &&
+		echo -e "Script '$pkg_exec' not found in $pkg_path!\n" && exit 1
+	echo -n "Building '$pkg_name' ... "
+	sh ${pkg_name}.SlackBuild >${log_file} 2>&1
+	[ $? -ne 0 ] && echo -e "Error building '$pkg_name'!\n" && exit 1
+	echo "done!"
+	cd - >/dev/null
+	local pkg_file=`cat ${log_file} | tail -n 2 | grep Slackware`
+	pkg_file=`echo "$pkg_file" | sed 's/^.*package \(.*\) created.*$/\1/'`
+	[ ! -f "$pkg_file" ] &&
+		echo "Cannot find package '$pkg_file'!" && exit 1
+	if [ "$opt_inst" == "--install" ] ; then
+		# go install!
+		echo -n "Installing '$pkg_file'... "
+		installpkg $pkg_file >>${log_file} 2>&1
+		[ $? -ne 0 ] &&
+			echo -e "Error installing '$pkg_file'!\n" && exit 1
+		echo "done!"
+	else
+		# copy built package & build log to chk_path (cwd)
+		echo -n "Copying '$pkg_file' to '$chk_path'... "
+		local chk_perm=`get_userngrp $chk_path`
+		mv $pkg_file $chk_path
+		pkg_file=${chk_path}/`basename $pkg_file`
+		mv $log_file $chk_path
+		log_file=${chk_path}/`basename $log_file`
+		if [ "$chk_perm" != "" ] ; then
+			chown $chk_perm $pkg_file $log_file
+		fi
+		echo "done!"
+	fi
+}
+
+function do_build_all()
+{
+	local pkg_name=$1
+	local pkg_path=$2
+	local opt_inst=$3
+	local chk_path=${MY1_THISPATH}
+	local sav_path=${pkg_path}
+	# update list
+	do_list_update
+	# get parameters
+	local pkg_root=`echo "$MY1_LISTFILE" | cut -d';' -f1`
+	local pkg_temp=`echo "$MY1_LISTFILE" | cut -d';' -f2`
+	local pkg_list=`echo "$MY1_LISTFILE" | cut -d';' -f3`
+	# fetch build
+	do_fetch $pkg_list $pkg_name $pkg_root $pkg_path $pkg_temp
+	# update path (in case in different path?)
+	pkg_path=`echo "$MY1_THISPACK" | cut -d';' -f1`
+	local pkg_vers=`echo "$MY1_THISPACK" | cut -d';' -f2`
+	local tmp_vers=`echo "$MY1_THISPACK" | cut -d';' -f3`
+	local pkg_deps=`echo "$MY1_THISPACK" | cut -d';' -f4`
+	# show this before dependencies if not really building
 	if [ "$OPT_EXECUTE" != "YES" ]; then
 		echo -n "Package: $pkg_name ($pkg_vers)"
 		[ "$tmp_vers" != "" -a "$tmp_vers" != "$pkg_vers" ] &&
@@ -264,60 +381,45 @@ function do_build()
 	# iterate through dependencies, if requested
 	if [ "$OPT_DEPENDS" == "YES" ]; then
 		for pkg in $pkg_deps ; do
-			do_build $pkg $sav_path --install
+			do_build_all $pkg $sav_path --install
 		done
 	fi
 	# build only if explicitly requested
-	if [ "$OPT_EXECUTE" == "YES" ]; then
-		# check if already installed? should check version as well?
-		pkg_temp="^${pkg_name}-[^-]*-[^-]*-[^-]*$"
-		pkg_base=`ls /var/log/packages | grep -e "$pkg_temp"`
-		if [ "$pkg_base" != "" ] ; then
-			# check version - stop if exactly the same!
-			pkg_temp=`echo $pkg_base | sed 's/\(.*\)-\(.*\)/\1/'`
-			pkg_temp=`echo $pkg_temp | sed 's/\(.*\)-\(.*\)/\1/'`
-			pkg_temp=`echo $pkg_temp | sed 's/\(.*\)-\(.*\)/\2/'`
-			[ "$pkg_vers" == "$pkg_temp" ] &&
-				echo "Package ${pkg_base} installed." && return
-			# continue, but do not install?
-			opt_inst=""
-		fi
-		# only root can actually build!
-		[ $UID -ne 0 ] &&
-			echo -e "Must run as root! ($pkg_name-$pkg_vers)\n" && return
-		# start build?
-		local log_file=/tmp/${pkg_name}.buildlog
-		cd ${pkg_path}
-		echo -n "Building '$pkg_name' ... "
-		sh ${pkg_name}.SlackBuild >${log_file} 2>&1
-		[ $? -ne 0 ] && echo -e "Error building '$pkg_name'!\n" && exit 1
-		echo "done!"
-		cd - >/dev/null
-		pkg_file=`cat ${log_file} | tail -n 2 | grep Slackware`
-		pkg_file=`echo "$pkg_file" | sed 's/^.*package \(.*\) created.*$/\1/'`
-		[ ! -f "$pkg_file" ] &&
-			echo "Cannot find package '$pkg_file'!" && exit 1
-		if [ "$opt_inst" == "--install" ] ; then
-			# go install!
-			echo -n "Installing '$pkg_file'... "
-			installpkg $pkg_file >>${log_file} 2>&1
-			[ $? -ne 0 ] &&
-				echo -e "Error installing '$pkg_file'!\n" && exit 1
-			echo "done!"
-		else
-			# copy built package & build log to chk_path (cwd)
-			echo -n "Copying '$pkg_file' to '$chk_path'... "
-			local chk_perm=`get_userngrp $chk_path`
-			mv $pkg_file $chk_path
-			pkg_file=${chk_path}/`basename $pkg_file`
-			mv $log_file $chk_path
-			log_file=${chk_path}/`basename $log_file`
-			if [ "$chk_perm" != "" ] ; then
-				chown $chk_perm $pkg_file $log_file
-			fi
-			echo "done!"
-		fi
-	fi;
+	[ "$OPT_EXECUTE" == "YES" ] &&
+		do_build $pkg_name $pkg_vers $pkg_path $pkg_temp $opt_inst
+}
+
+function do_update_all()
+{
+	local chk_path=$1
+	local chk_list=`find $pkg_path -name "*.SlackBuild"`
+	echo -e "Updating buildscripts in '$chk_path':\n"
+	for pkg in $chk_list ; do
+		local tmp_path=`dirname $pkg`
+		local pkg_path=`dirname $tmp_path`
+		local pkg_name=`basename $tmp_path`
+		local pkg_info=`get_buildinfo $pkg_name $pkg_path`
+		[ "$pkg_info" == "" ] &&
+			echo -e "Error updating '$pkg_name'! Aborting!\n" && exit 1
+		# update list
+		do_list_update
+		# get parameters
+		local pkg_root=`echo "$MY1_LISTFILE" | cut -d';' -f1`
+		local pkg_temp=`echo "$MY1_LISTFILE" | cut -d';' -f2`
+		local pkg_list=`echo "$MY1_LISTFILE" | cut -d';' -f3`
+		# fetch build
+		do_fetch $pkg_list $pkg_name $pkg_root $pkg_path $pkg_temp
+		# update path (in case in different path?)
+		pkg_path=`echo "$MY1_THISPACK" | cut -d';' -f1`
+		local pkg_vers=`echo "$MY1_THISPACK" | cut -d';' -f2`
+		local tmp_vers=`echo "$MY1_THISPACK" | cut -d';' -f3`
+		# show this before dependencies if not really building
+		echo -n "Package: $pkg_name ($pkg_vers)"
+		[ "$tmp_vers" != "" -a "$tmp_vers" != "$pkg_vers" ] &&
+			echo -n ", Local Version: {$tmp_vers}"
+		pkg_path=`echo $pkg_path | sed "s|$chk_path||"`
+		echo " [Path: $pkg_path]"
+	done ; echo
 }
 
 function process_command()
@@ -338,6 +440,9 @@ function process_command()
 			--update|-u)
 				OPT_CLEANUP="YES"
 				OPT_WARNOLD="YES"
+				;;
+			--update-local)
+				OPT_ALL_NEW="YES"
 				;;
 			--path|-p)
 				shift
@@ -361,13 +466,18 @@ function process_command()
 		esac
 		shift
 	done
+	# check if path is valid?
+	pkg_path=${MY1_BUILDDIR}
+	[ ! -d "$pkg_path" ] &&
+		echo -e "Path '$pkg_path' not found! Aborting!\n" && exit 1
+	# check option to update ALL build scripts found
+	[ "$OPT_ALL_NEW" == "YES" ] && do_update_all ${pkg_path} && exit 0
 	# check if name supplied
 	[ "$pkg_name" == "" ] && echo -e "$MSG_THISHELP\n" && exit 0
 	# check if package path supplied
-	pkg_path=${MY1_BUILDDIR}
 	[ "$MY1_PACKPATH" != "" ] && pkg_path=${pkg_path}/${MY1_PACKPATH}
 	# do your thing!
-	do_build ${pkg_name} ${pkg_path} ${OPT_INSTALL}
+	do_build_all ${pkg_name} ${pkg_path} ${OPT_INSTALL}
 }
 
 # BEGIN MAIN SCRIPT
