Updated getslackpack
- should delete invalid packages (corrupt download?)

diff --git a/getslackpack b/getslackpack
--- a/getslackpack
+++ b/getslackpack
@@ -217,8 +217,13 @@ function go_loadpack()
 	# check if valid package exists
 	if [ -r $pkg_file.md5 ]; then
 		md5sum --check $pkg_file.md5 >/dev/null 2>&1
-		[ $? -eq 0 ] && echo "[INFO]  VALID LOCAL COPY!" &&
-			pkg_test="OK"
+		[ $? -eq 0 ] && pkg_test="OK"
+		if [ "$pkg_test" == "OK" ]; then
+			echo "[INFO]  VALID LOCAL COPY!"
+		else
+			rm -rf ${pkg_file}*
+			echo "[INFO]  Invalid local package... deleted!"
+		fi
 	fi
 	if [ "$OPT_CHECK" != "YES" ] && [ "$pkg_test" != "OK" ]; then
 		# download if not found or invalid
