More fixes for getslackbuild
- i thought i had this??? :(

diff --git a/getslackbuild b/getslackbuild
--- a/getslackbuild
+++ b/getslackbuild
@@ -16,7 +16,7 @@ done
 
 # my1slack tool specific
 MY1_TOOLNAME="my1 SlackBuilds.org Executor"
-MY1_TOOLVERS="2017.03.01"
+MY1_TOOLVERS="2017.03.02"
 MY1_TOOLPDIR=`dirname $MY1PATH`
 MY1_BUILDDIR=${MY1_BUILDDIR:="${MY1_TOOLPDIR}/slackbuilds"}
 MY1_THISPATH=`pwd -P`
@@ -80,8 +80,12 @@ function do_loadball()
 	local pkg_ball=`basename $pkg_file`
 	[ ! -d $pkg_path ] &&
 		echo -e "[ERROR] Cannot find $pkg_path!\n" >&2 && exit 1
-	wget --spider $pkg_file >/dev/null 2>&1
-	[ $? -ne 0 ] && echo -e "[ERROR] Cannot get $pkg_file!\n" >&2 && exit 1
+	# TODO! This has problems if redirected a lot (github source?)
+	#wget --spider $pkg_file >/dev/null 2>&1
+	#[ $? -ne 0 ] && echo -e "[ERROR] Cannot get $pkg_file!\n" >&2 && exit 1
+	local chk_test=`curl -s -o /dev/null -w '%{http_code}' $pkg_file`
+	[ $chk_test -ne 200 -o $chk_test -ne 302 ] &&
+		echo -e "[ERROR] Cannot get $pkg_file!\n" >&2 && exit 1
 	cd $pkg_path
 	do_download $pkg_file $pkg_ball 2>/dev/null
 	[ ! -r $pkg_ball ] &&
@@ -207,7 +211,10 @@ function do_build()
 			cd - >/dev/null
 			tmp_vers=$pkg_vers
 			pkg_test=$pkg_temp/$pkg_text
-			cd `dirname $pkg_path`
+			top_path=`dirname $pkg_path`
+			[ ! -d "$top_path" ] && mkdir -p $top_path
+			cd $top_path
+			# remove old?
 			rm -rf ${pkg_name}
 			# extract accordingly?
 			tar xf $pkg_test 2>/dev/null
@@ -240,6 +247,11 @@ function do_build()
 	# build only if explicitly requested
 	if [ "$OPT_EXECUTE" == "YES" ]; then
 		[ $UID -ne 0 ] && echo -e "Must run as root!\n" && exit 1
+		# check if already installed?
+		local chk_temp="^${pkg_name}-[^-]*-[^-]*-[^-]*$"
+		local chk_base=`ls /var/log/packages | grep -e "$chk_temp"`
+		[ "$chk_base" != "" ] &&
+			echo "Package ${chk_base} installed." && return
 		# are we building x86_64?
 		[ "$SLACKARCH" == "x86_64" -a "$pkg_fil2" != "" ] &&
 			pkg_file="$pkg_fil2"
