Update Commit
- updated video-tool and slack-related tools
- added 2 new scripts (chkbuild chkgit)

diff --git a/getslack b/getslack
--- a/getslack
+++ b/getslack
@@ -15,7 +15,10 @@ done
 
 MY1_GETSLACK_CONF=$(cat <<MY1CONF
 # checkout release & arch
+# RSYNCURLROOT=\${RSYNCURLROOT:="slackware.mirrors.tds.net::slackware/slackware-current"}
+# RSYNCURLROOT=\${RSYNCURLROOT:="rsync.osuosl.org::slackware/slackware-current"}
 RSYNCURLROOT=\${RSYNCURLROOT:="taper.alienbase.nl::mirrors/slackware/"}
+# RSYNCURLROOT=\${RSYNCURLROOT:="mirror.aarnet.edu.au::slackware/"}
 RELEASE=\${RELEASE:="13.37"}
 SLACKARCH=\${SLACKARCH:="\$(uname -m)"}
 SLACKFULL=\${SLACKFULL:="slackware"}
@@ -77,6 +80,24 @@ SLACKPATH="${SLACKROOT}/${SLACKRELEASE}"
 RSYNCURLROOT=${RSYNCURLROOT:="rsync.osuosl.org::slackware/"}
 RSYNCURL=${RSYNCURL:="${RSYNCURLROOT}${SLACKRELEASE}"}
 RSYNCOPT=${RSYNCOPT:="--delete --delete-excluded --partial -rlptD --progress"}
+
+# option to create iso - helping o-thers... local mirror must exist!
+if [[ "$1" == "--mkiso" ]]; then
+	MKISOFS=${MKISOFS:="$(chk_mkisofs=$(which mkisofs 2>&1); [[ $? -eq 0 ]] && echo "$chk_mkisofs")"}
+	[[ "$MKISOFS" == "" ]] && echo "'mkisofs' not found! Aborting!" && exit 1
+	ISOPATH=${ISOPATH:="$HOME/temp"}
+	[[ ! -d "$ISOPATH"  ]] && echo "Path '$ISOPATH' not found! Aborting!" && exit 1
+	echo -n "Creating ISO from $SLACKPATH... "
+	cd $SLACKPATH
+	$MKISOFS -o $ISOPATH/${SLACKRELEASE}-install.iso -V "${SLACKRELEASE} Install DVD" \
+		-R -J -hide-rr-moved -hide-joliet-trans-tbl -d -N \
+		-v -v -no-emul-boot -boot-load-size 32 -boot-info-table \
+		-sort isolinux/iso.sort -b isolinux/isolinux.bin -c isolinux/isolinux.boot \
+		-A "${SLACKRELEASE} Install DVD (build $(date +%Y%m%d))" . \
+		> $ISOPATH/${SLACKRELEASE}-install_build.log 2>&1
+	echo "done!"
+	exit 0
+fi
 
 # customized sync list
 EXCLUDES=${EXCLUDES:="--exclude pasture"}
diff --git a/slackpatch b/slackpatch
--- a/slackpatch
+++ b/slackpatch
@@ -5,8 +5,8 @@
 # - slackware patch manager
 
 # standard tool info
-TOOL_THISFUNC="Slackware Patch Tool"
-TOOL_THISVERS="2010.04.00"
+TOOL_THISFUNC="my1 Slackware Patch Tool"
+TOOL_THISVERS="2011.12.00"
 # standard tool conf
 TOOL_CHECKCMD="$@"
 TOOL_COMMANDS=${TOOL_CHECKCMD:="help"}
@@ -25,10 +25,6 @@ done
 TOOL_SLACKDIR=${TOOL_SLACKDIR:="${SLACKROOTDIR}/${SLACKRELEASE}"}
 TOOL_PATCHDIR=${TOOL_PATCHDIR:="${TOOL_SLACKDIR}/patches/packages"}
 TOOL_LOGFILE=${TOOL_LOGFILE:="/tmp/${TOOL_THISFILE%%.*}.log"}
-# patch lists (global params)
-list_update=""
-list_unknown=""
-list_done=""
 # global options & settings
 OPT_FULLINFO="NO"
 OPT_AUTOPATCH="YES"
@@ -36,8 +32,9 @@ MSG_THISHELP=$(cat <<SETHELPMSG
 Usage:
   $TOOL_THISFILE <command> [options]
 Commands:
-  check : Check patch status
-  nlist : List patches NOT in update list
+  check : Check patch status (find relevant patches)
+  pdone : List patches that has been applied
+  nlist : List patches NOT in update list (not used)
   patch : Apply updates/patches
   help  : Show this help message
 Options:
@@ -48,7 +45,7 @@ Options:
   --path <path_name> : Specify additional patch path
   --pkg <package_name> : Auto-Patch Implied!
 Mirror Source:
-  ${SLACKROOTDIR}/${SLACKRELEASE}
+  $TOOL_SLACKDIR
 Log File:
   $TOOL_LOGFILE
 SETHELPMSG
@@ -56,53 +53,50 @@ SETHELPMSG
 
 function find_patches()
 {
+	local pat_exts pat_base pat_name
+	local pat_vers pat_arch pat_extd
+	local pkg_temp pkg_base pkg_name
+	local pkg_vers pkg_arch pkg_extd
 	local curr_dir=$(pwd)
+
 	for pat_file in *.t[gx]z; do
 		# check extension first
 		pat_exts="${pat_file##*.}"
+		pat_base="${pat_file%%.${pat_exts}}"
 		# get particulars
-		pat_name="${pat_file%-*-*-*.${pat_exts}}"
-		temp="${pat_file##${pat_name}-}"
-		pat_vers="${temp%-*-*.${pat_exts}}"
-		temp="${temp##${pat_vers}-}"
-		pat_arch="${temp%-*.${pat_exts}}"
-		temp="${temp##${pat_arch}-}"
-		pat_extd="${temp%.${pat_exts}}"
+		pkg_temp=($(get_pkg_info $pat_base))
+		pat_name="${pkg_temp[0]}"
+		pat_vers="${pkg_temp[1]}"
+		pat_arch="${pkg_temp[2]}"
+		pat_extd="${pkg_temp[3]}"
 		# find installed
-		pkg_file=""
-		for tfile in $(ls /var/log/packages|grep "$pat_name"); do
-			pkg_name="${tfile%-*-*-*}"
-			if [[ "$pkg_name" == "$pat_name" ]]; then
-				pkg_file="$tfile"
-				break;
-			fi
-		done
-		if [[ "$pkg_file" != "" ]]; then
-			pkg_name="${pkg_file%-*-*-*}"
-			temp="${pkg_file##${pkg_name}-}"
-			pkg_vers="${temp%-*-*}"
-			temp="${temp##${pkg_vers}-}"
-			pkg_arch="${temp%-*}"
-			temp="${temp##${pkg_arch}-}"
-			pkg_extd="${temp}"
+		pkg_base="$(find_install $pat_name)"
+		if [[ "$pkg_base" != "" ]]; then
+			pkg_temp=($(get_pkg_info $pkg_base))
+			pkg_name="${pkg_temp[0]}"
+			pkg_vers="${pkg_temp[1]}"
+			pkg_arch="${pkg_temp[2]}"
+			pkg_extd="${pkg_temp[3]}"
 			if [[ "$pkg_vers" == "$pat_vers" ]] &&
 				[[ "$pkg_extd" == "$pat_extd" ]]; then
-				list_done="$pat_name $list_done"
-				eval patchinfo_${pat_name//[-.]/_}=[${pkg_vers}/${pkg_extd}]-to-[${pat_vers}/${pat_extd}]
+				PAT_LIST="$PAT_LIST $pat_name"
+				eval patchstat_${pat_name//[-.]/_}="pdone"
+				eval patchfile_${pat_name//[-.]/_}=${curr_dir}/${pat_file}
+				eval patchvers_${pat_name//[-.]/_}=[${pat_vers}/${pat_extd}]
 			else
-				list_update="$pat_name $list_update"
+				PAT_LIST="$PAT_LIST $pat_name"
+				eval patchstat_${pat_name//[-.]/_}="check"
 				eval patchfile_${pat_name//[-.]/_}=${curr_dir}/${pat_file}
 				eval patchvers_${pat_name//[-.]/_}=[${pkg_vers}/${pkg_extd}]-to-[${pat_vers}/${pat_extd}]
 			fi
-			#echo "Patch: $pat_file"
-			#echo "Install: $pkg_file"
 		else
-			list_unknown="$pat_name $list_unknown"
-			eval patchinfo_${pat_name//[-.]/_}=${pat_file}
+			PAT_LIST="$PAT_LIST $pat_name"
+			eval patchstat_${pat_name//[-.]/_}="nlist"
+			eval patchfile_${pat_name//[-.]/_}=${curr_dir}/${pat_file}
+			eval patchvers_${pat_name//[-.]/_}=[${pat_vers}/${pat_extd}]
 		fi
 	done
 	cd $curr_dir
-	#echo -n "--done $list_done --update $list_update --unknown $list_unknkown"
 }
 
 function check_patches()
@@ -117,15 +111,36 @@ function check_patches()
 	for path in $KERNEL_PATPATH; do
 		cd $path
 		find_patches
+		cd $TOOL_PATCHDIR
 	done
 	while [[ "$1" != "" ]]; do
-		if [[ -d "$1" ]]; then
-			cd $1
-			find_patches
-		fi
+		cd $1
+		find_patches
 		shift
 	done
-	cd $curr_dir
+}
+
+function extract_patches()
+{
+	local pkg_temp pat_list pkg_list pkg_opts
+	pkg_opts=$1; shift; pkg_list=$@
+	pat_list=""
+	for pkg_name in $pkg_list ; do
+		pkg_temp="patchstat_${pkg_name//-/_}"
+		[[ "${!pkg_temp}" == "$pkg_opts" ]] && pat_list="$pat_list $pkg_name"
+	done
+	echo -n "$pat_list"
+}
+
+function check_request()
+{
+	local pkg_temp pkg_list
+	pkg_list=""
+	for pkg_name in $@ ; do
+		pkg_temp="patchstat_${pkg_name//-/_}"
+		[[ "${!pkg_temp}" == "check" ]] && pkg_list="$pkg_list $pkg_name"
+	done
+	echo -n "$pkg_list"
 }
 
 function must_be_root()
@@ -135,37 +150,23 @@ function must_be_root()
 
 function execute_patches()
 {
-	local tempfile=""
-	local patchfile=""
-	local patchvers=""
-	local pkg_temp=""
+	local pkg_temp pkg_file pkg_vers
+	local pkg_list=$(check_request $@)
 
 	must_be_root
 
-	# update specific requested package
-	if [[ "$1" != "" ]]; then
-		while [[ "$1" != "" ]]; do
-			pkg_temp=$1
-			tempfile="patchfile_${pkg_temp//-/_}"
-			patchfile=${!tempfile}
-			tempfile="patchvers_${pkg_temp//-/_}"
-			patchvers=${!tempfile}
-			echo -n "Auto-updating single package '$pkg_temp'... "
-			/sbin/upgradepkg ${patchfile} >>$TOOL_LOGFILE
-			echo -e "done.\n"
-			shift
-		done
-		return
-	fi
-
-	if [[ ! -z "$list_update" ]]; then
+	[[ "$pkg_list" == "" ]] && pkg_list=$(extract_patches check $PAT_LIST)
+	if [[ ! -z "$pkg_list" ]]; then
 		echo -e "$TOOL_THISFILE - $TOOL_THISFUNC ($TOOL_THISVERS)\n$(date)\n" >$TOOL_LOGFILE
 		echo "Packages need updating:"
-		for pkg in $list_update ; do
-			tempfile="patchfile_${pkg//-/_}"
-			patchfile=${!tempfile}
-			tempfile="patchvers_${pkg//-/_}"
-			patchvers=${!tempfile}
+		for pkg_name in $pkg_list ; do
+			pkg_temp="patchstat_${pkg_name//-/_}"
+			[[ "${!pkg_temp}" != "check" ]] && continue
+			pkg_temp="patchfile_${pkg_name//-/_}"
+			pkg_file=${!pkg_temp}
+			pkg_temp="patchvers_${pkg_name//-/_}"
+			pkg_vers=${!pkg_temp}
+			[[ ! -r "$patchfile" ]] && echo "Error: File '$patchfile' not found!" && exit 1
 			if [[ "$OPT_AUTOPATCH" == "NO" ]] ; then
 				read -n 1 -p "Update package '$pkg' ? [y]/[*]/[q] : " do_update ; echo
 				if [[ "$do_update" == "y" ]]; then
@@ -188,87 +189,44 @@ function execute_patches()
 	echo
 }
 
-function update_patches()
+function display_patches()
 {
-	local tempfile=""
-	local patchfile=""
-	local patchvers=""
+	local pkg_temp pkg_file pkg_vers pkg_list pkg_opts
 
-	if [[ ! -z "$list_update" ]]; then
-		echo "Packages need updating:"
-		for pkg in $list_update ; do
-			tempfile="patchfile_${pkg//-/_}"
-			patchfile=${!tempfile}
-			tempfile="patchvers_${pkg//-/_}"
-			patchvers=${!tempfile}
+	pkg_opts=$1; shift; pkg_list=$(extract_patches $pkg_opts $PAT_LIST)
+	if [[ ! -z "$pkg_list" ]]; then
+		[[ "$pkg_opts" == "check" ]] && echo "Packages need updating:"
+		[[ "$pkg_opts" == "pdone" ]] && echo "Packages already up-to-date:"
+		[[ "$pkg_opts" == "nlist" ]] && echo "Unknown patches:"
+		for pkg_name in $pkg_list ; do
+			pkg_temp="patchstat_${pkg_name//-/_}"
+			[[ "${!pkg_temp}" != "$pkg_opts" ]] && continue
+			pkg_temp="patchfile_${pkg_name//-/_}"
+			pkg_file=${!pkg_temp}
+			pkg_temp="patchvers_${pkg_name//-/_}"
+			pkg_vers=${!pkg_temp}
 			if [[ "$OPT_FULLINFO" == "NO" ]] ; then
-				echo -n "$pkg "
+				echo -n "$pkg_name "
 			elif [[ "$OPT_FULLINFO" == "YES" ]] ; then
-				echo "$pkg : ${patchvers}"
+				echo "$pkg_name: ${pkg_vers}"
 			fi
 		done
 		[[ "$OPT_FULLINFO" != "YES" ]] && echo
 	else
-		echo "Nothing to patch/upgrade!"
-	fi
-	echo
-}
-
-function done_patches()
-{
-	local tempfile=""
-	local patchinfo=""
-
-	if [[ ! -z "$list_done" ]]; then
-		echo "Packages already up-to-date:"
-		for pkg in $list_done ; do
-			tempfile="patchinfo_${pkg//-/_}"
-			patchinfo=${!tempfile}
-			if [[ "$OPT_FULLINFO" == "NO" ]] ; then
-				echo -n "$pkg "
-			elif [[ "$OPT_FULLINFO" == "YES" ]] ; then
-				echo "$pkg : ${patchinfo}"
-			fi
-		done
-		[[ "$OPT_FULLINFO" != "YES" ]] && echo
-	else
-		echo "No updated patches! Check your patches!"
-	fi
-	echo
-}
-
-function unknown_patches()
-{
-	local tempfile=""
-	local patchinfo=""
-	local patch_opt="$1"
-
-	if [ ! -z "$list_unknown" ]; then
-		echo "Patches for packages NOT in installation:"
-		for pkg in $list_unknown ; do
-			tempfile="patchinfo_${pkg//-/_}"
-			patchinfo=${!tempfile}
-			if [[ "$OPT_FULLINFO" == "YES" ]] ; then
-				echo "$pkg : ${patchinfo}"
-			else
-				echo -n "$pkg "
-			fi
-		done
-		[[ "$OPT_FULLINFO" != "YES" ]] && echo
-	else
-		echo "No unknown patches!"
+		[[ "$pkg_opts" == "check" ]] && echo "No updates found!"
+		[[ "$pkg_opts" == "pdone" ]] && echo "No up2date patches!"
+		[[ "$pkg_opts" == "nlist" ]] && echo "No unknown patches!"
 	fi
 	echo
 }
 
 function process_command()
 {
-	local go_commands="check nlist patch"
+	local go_commands="check pdone nlist patch"
 	local do_command=""
-	local list_pkgs=""
-	local list_path=""
+	local pkg_list="" pkg_path=""
 	local pkg_temp
-
+	# check parameters
 	while [[ "$1" != "" ]]; do
 		case "$1" in
 			--short)
@@ -288,21 +246,15 @@ function process_command()
 				# check additional path
 				[[ ! -d "$1" ]] &&
 					echo -e "Cannot find path '$1'!\n" && exit 1
-				list_path="${list_path} $(cd $1;pwd)"
+				pkg_path="${pkg_path} $(cd $1;pwd)"
 				;;
 			--pkg)
 				shift
 				# check discrete package name
-				pkg_temp=""
-				for tfile in $(ls /var/log/packages|grep "$1"); do
-					if [[ "${tfile%-*-*-*}" == "$1" ]]; then
-						pkg_temp=$tfile
-						break;
-					fi
-				done
+				pkg_temp=$(find_install $1)
 				[[ "$pkg_temp" == "" ]] &&
 					echo -e "Unknown package '$1'!\n" && exit 1
-				list_pkgs="${list_pkgs} $pkg_temp"
+				pkg_list="${pkg_list} $pkg_temp"
 				;;
 			--help|-h|help)
 				echo -e "$MSG_THISHELP\n"
@@ -323,14 +275,14 @@ function process_command()
 		esac
 		shift
 	done
-
+	# exit if no command...
 	[[ "$do_command" == "" ]] && echo -e "No command given!\n" && exit 1
-
-	check_patches $list_path
-	[[ "$do_command" == "check" ]] && update_patches
-	[[ "$do_command" == "nlist" ]] && done_patches
-	[[ "$do_command" == "nlist" ]] && unknown_patches
-	[[ "$do_command" == "patch" ]] && execute_patches $list_pkgs
+	# find packages
+	check_patches $pkg_path
+	# display packages
+	[[ "$do_command" != "patch" ]] && display_patches $do_command
+	# patch packages
+	[[ "$do_command" == "patch" ]] && execute_patches $pkg_list
 }
 
 # BEGIN MAIN SCRIPT
