Script getwifi confirmed to be usable :p
- also added 2 new scripts: chkwifi & chknet

diff --git a/getwifi b/getwifi
--- a/getwifi
+++ b/getwifi
@@ -9,7 +9,6 @@ WIFI_DEV=${WIFI_DEV:="wlan0"}
 WIFI_ADD=${WIFI_ADD:="192.168.1.100"}
 WIFI_MSK=${WIFI_MSK:="255.255.255.0"}
 WIFI_SSID=${WIFI_SSID:=""}
-WIFI_ENC=${WIFI_ENC:=""}
 WIFI_ENCS=${WIFI_ENCS:=""}
 
 WIFI_LOGFILE=${WIFI_LOGFILE:="/tmp/$(basename $0).log"}
@@ -23,7 +22,7 @@ OPT_WRITECFG_WPA=""
 
 function must_be_root()
 {
-	[[ $UID -ne 0 ]] && echo -e "Abort: must run as root!\n" && exit 1
+	[ $UID -ne 0 ] && echo -e "Abort: must run as root!\n" && exit 1
 }
 
 while [ "$1" != "" ]; do
@@ -45,31 +44,31 @@ while [ "$1" != "" ]; do
 			;;
 		--ssid)
 			shift
-			[[ "$1" == "" ]] && echo "No SSID given? Aborting..." && exit 1
+			[ "$1" == "" ] && echo "No SSID given? Aborting..." && exit 1
 			WIFI_SSID="$1"
 			;;
 		--key)
 			shift
-			[[ "$1" == "" ]] && echo "No key given? Aborting..." && exit 1
-			WIFI_ENC="$1"
+			[ "$1" == "" ] && echo "No key given? Aborting..." && exit 1
+			WIFI_ENCS="$1"
 			;;
 		--wpa)
 			WIFI_WPA_SUPP="yes"
 			;;
 		--device)
 			shift
-			[[ "$1" == "" ]] && echo "No device given? Aborting..." && exit 1
+			[ "$1" == "" ] && echo "No device given? Aborting..." && exit 1
 			WIFI_DEV="$1"
 			;;
 		--static)
 			shift
-			[[ "$1" == "" ]] && echo "No address given? Aborting..." && exit 1
+			[ "$1" == "" ] && echo "No address given? Aborting..." && exit 1
 			WIFI_ADD="$1"
 			WIFI_RUN_DHCP=""
 			;;
 		--netmask)
 			shift
-			[[ "$1" == "" ]] && echo "No netmask given? Aborting..." && exit 1
+			[ "$1" == "" ] && echo "No netmask given? Aborting..." && exit 1
 			WIFI_MSK="$1"
 			;;
 		-s|--stop)
@@ -90,7 +89,7 @@ done
 # now we start!
 must_be_root
 
-if [[ "$OPT_WRITECFG_WPA" == "yes" ]]; then
+if [ "$OPT_WRITECFG_WPA" == "yes" ]; then
 WIFI_WPA_CONF_DATA=$(cat <<SETVAR1
 network={
 	scan_ssid=0
@@ -109,14 +108,14 @@ SETVAR1
 	echo "$WIFI_WPA_CONF_DATA" >>$WIFI_WPA_CONF
 fi
 
-if [[ "$WIFI_DO_STOP" == "yes" ]]; then
+if [ "$WIFI_DO_STOP" == "yes" ]; then
 	# check if wpa is running?
-	if [[ "$(wpa_cli status 2>/dev/null | grep "$MSG_NO_WPA_SUPPLICANT")" == "" ]] ; then
-		if [[ "$(wpa_cli status 2>/dev/null | grep "$WIFI_DEV")" == "" ]] ; then
+	if [ "$(wpa_cli status 2>/dev/null | grep "$MSG_NO_WPA_SUPPLICANT")" == "" ] ; then
+		if [ "$(wpa_cli status 2>/dev/null | grep "$WIFI_DEV")" == "" ] ; then
 			echo "Interface '$WIFI_DEV' NOT up?!"
 		else
 			echo -n "Terminating wpa_supplicant... "
-			if [[ "$(wpa_cli -i$WIFI_DEV terminate | grep OK)" == "" ]]; then
+			if [ "$(wpa_cli -i$WIFI_DEV terminate | grep OK)" == "" ]; then
 				echo "wpa_cli ERROR!"
 			else
 				echo "done."
@@ -130,16 +129,16 @@ if [[ "$WIFI_DO_STOP" == "yes" ]]; then
 	GO_FISH=""
 	# check currently running dhcpcd process
 	for (( a=0;a<${#tmp_lines[@]};a++ )); do
-		[[ "$(echo ${tmp_lines[$a]} | grep $WIFI_DEV)" == "" ]] && continue
+		[ "$(echo ${tmp_lines[$a]} | grep $WIFI_DEV)" == "" ] && continue
 		GO_FISH="yes"
 	done
-	if [[ "$GO_FISH" == "" ]]; then
+	if [ "$GO_FISH" == "" ]; then
 		echo "No running dhcpcd on $WIFI_DEV!"
 	else
 		echo -n "Terminating dhcp daemon on $WIFI_DEV... "
 		dhcpcd -k $WIFI_DEV 2>/dev/null
 		retval=$?
-		[[ $retval -ne 0 ]] && echo -n "(dhcpcd) Return Error [$retval]? "
+		[ $retval -ne 0 ] && echo -n "(dhcpcd) Return Error [$retval]? "
 		echo "done."
 	fi
 	exit 0
@@ -147,12 +146,12 @@ fi
 
 # look for WIFI_DEV, in case it's NOT plugged in
 echo -n "Looking for $WIFI_DEV..."
-[[ "$(iwconfig 2>/dev/null | grep "$WIFI_DEV")" == "" ]] &&
+[ "$(iwconfig 2>/dev/null | grep "$WIFI_DEV")" == "" ] &&
 	echo "NOT FOUND! Exiting!" && exit 0
 echo "found."
 
 # configure for static if DHCP NOT requested
-if [[ "$WIFI_RUN_DHCP" == "yes" ]] ; then
+if [ "$WIFI_RUN_DHCP" == "yes" ] ; then
 	WIFI_ADD=""
 	WIFI_MSK=""
 else
@@ -161,27 +160,29 @@ else
 fi
 
 # configure for WEP key & assign ssid
-if [[ "$WIFI_WPA_SUPP" == "" ]]; then
-	[[ "$WIFI_ENC" != "" ]] && WIFI_ENC="enc $WIFI_ENC"
+if [ "$WIFI_WPA_SUPP" == "" ]; then
+	[ "$WIFI_ENCS" != "" ] && WIFI_ENCS="enc $WIFI_ENCS"
 fi
-[[ "$WIFI_SSID" != "" ]] && WIFI_SSID="essid $WIFI_SSID"
+[ "$WIFI_SSID" != "" ] && WIFI_SSID="essid $WIFI_SSID"
 
 echo -n "Configuring $WIFI_DEV..."
 iwconfig $WIFI_DEV $WIFI_SSID $WIFI_ENC >>$WIFI_LOGFILE
 ifconfig $WIFI_DEV up $WIFI_MSK $WIFI_ADD >>$WIFI_LOGFILE
 echo "done."
 
-if [[ "$WIFI_WPA_SUPP" == "yes" ]]; then
+if [ "$WIFI_WPA_SUPP" == "yes" ]; then
 	echo -n "Starting wpa_supplicant... "
-	wpa_supplicant -B -Dwext -i$WIFI_DEV -c$WIFI_WPA_CONF
+	wpa_supplicant -B -Dwext -i$WIFI_DEV -c$WIFI_WPA_CONF 2>&1 >>$WIFI_LOGFILE
+	retval=$?
+	[ $retval -ne 0 ] && echo -n "(wpa_supplicant) Return Error [$retval]? "
 	echo "done."
 fi
 
-if [[ "$WIFI_RUN_DHCP" == "yes" ]]; then
+if [ "$WIFI_RUN_DHCP" == "yes" ]; then
 	echo -n "Starting DHCP client daemon..."
 	dhcpcd -h $(hostname) $WIFI_DEV 2>/dev/null >>$WIFI_LOGFILE
 	retval=$?
-	[[ $retval -ne 0 ]] && echo -n "(dhcpcd) Return Error [$retval]? "
+	[ $retval -ne 0 ] && echo -n "(dhcpcd) Return Error [$retval]? "
 	echo "done."
 fi
 
