Finally... got getwifi to connect to wep-based ap
- had to execute twice before :o

diff --git a/getwifi b/getwifi
--- a/getwifi
+++ b/getwifi
@@ -125,9 +125,13 @@ if [ "$WIFI_DO_STOP" == "yes" ]; then
 CONN=`iwconfig $WIFI_DEV | sed -n "s/^.*Access Point: \([^ ]*\) .*$/\1/ p"`
 			if [ "$CONN" != "Not-Associated" ] ; then
 				echo -n "Taking $WIFI_DEV down... "
+				iwconfig $WIFI_DEV essid any enc off
 				ifconfig $WIFI_DEV down
-				[ $? -eq 0 ] && echo "done."
-				[ $? -ne 0 ] && echo "something is wrong?"
+				if [ $? -eq 0 ] ; then
+					echo "done."
+				else
+					echo "something is wrong?"
+				fi
 			else
 				echo "Interface '$WIFI_DEV' NOT up?!"
 			fi
@@ -193,18 +197,19 @@ fi
 
 # configure for WEP key & assign ssid
 if [ "$WIFI_WPA_SUPP" == "" ]; then
-	[ "$WIFI_ENCS" != "" ] && WIFI_ENCS="key open s:$WIFI_ENCS"
+	[ "$WIFI_ENCS" != "" ] && WIFI_ENCS="key s:$WIFI_ENCS open"
 fi
 
 echo -n "Configuring $WIFI_DEV..."
-iwconfig $WIFI_DEV essid $WIFI_SSID >>$WIFI_LOGFILE
+iwconfig $WIFI_DEV essid "$WIFI_SSID" >>$WIFI_LOGFILE
 if [ "$WIFI_ENCS" != "" ] ; then
-	iwconfig $WIFI_DEV $WIFI_ENCS >>$WIFI_LOGFILE
-	#iwconfig $WIFI_DEV enc on >>$WIFI_LOGFILE # maybe i need this?
+	ifconfig $WIFI_DEV down
+	iwconfig $WIFI_DEV essid "$WIFI_SSID" $WIFI_ENCS >>$WIFI_LOGFILE
+	ifconfig $WIFI_DEV up
 	sleep 2 # give some time for it to do its thing :o
 	CONN=`iwconfig $WIFI_DEV | sed -n "s/^.*Access Point: \([^ ]*\) .*$/\1/ p"`
 	if [ "$CONN" == "Not-Associated" ] ; then
-		echo "failed to connect to AP?"
+		echo " failed to connect to AP?"
 		exit 1
 	fi
 fi
