Updated gitpack
- packthis will now use gitpack when --git is requested
- will remove git-related stuff later...

diff --git a/gitpack b/gitpack
--- a/gitpack
+++ b/gitpack
@@ -2,6 +2,7 @@
 
 # gitpack
 # - written by azman@my1matrix.net
+# - was a part of packthis script (maintain related options)
 # - create git bundle (AND git patch if necessary)
 
 CURRPATH=$(pwd)
@@ -10,22 +11,30 @@ BALLPATH=$HOME/temp
 BALLNAME=$(basename $CURRPATH)
 MAINNAME=${MAINNAME:="$BALLNAME"}
 BALLSUFX=${BALLSUFX:=""}
+DOBUNDLE=${DOBUNDLE:="YES"}
 DATE_FMT=${DATE_FMT:="+%Y%m%d"}
 PATCHGIT=${PATCHGIT:="NO"}
 PATCHNUM=${PATCHNUM:="4"}
 
+#echo "[INFO] Running "`basename $0`
+
 while [ "$1" != "" ]; do
 	case $1 in
-		--suffix)
-			shift
-			BALLSUFX="-$1"
-			;;
-		--name)
-			shift
-			MAINNAME="$1"
+		--diff)
+			DOBUNDLE="NO"
 			;;
 		--time)
 			DATE_FMT="+%Y%m%d%H%M"
+			;;
+		--suffix)
+			shift
+			BALLSUFX="$1"
+			;;
+		--name)
+			shift
+			[ "$1" == "" ] &&
+				echo "No name given ['$1']?" && exit 1
+			MAINNAME="$1"
 			;;
 		--path)
 			shift
@@ -64,18 +73,23 @@ CHK_DATE=`date ${DATE_FMT}`
 CHK_NAME=${MAINNAME}-${CHK_DATE}
 
 # create git bundle
-git bundle create ${BALLPATH}/${CHK_NAME}${BALLSUFX}.git --branches --tags
-[ $? -ne 0 ] && echo "Error running git?" && exit 1
+if [ "$DOBUNDLE" == "YES" ]; then
+	git bundle create ${BALLPATH}/${CHK_NAME}-${BALLSUFX}.git --branches --tags
+	[ $? -ne 0 ] && echo "Error running git?" && exit 1
+fi
 
 # create diff - if we have one?
 GIT_DIFF=`git diff`
-[ "$GIT_DIFF" != "" ] &&
-	echo "$GIT_DIFF" >${BALLPATH}/${CHK_NAME}${BALLSUFX}.patch
+if [ "$GIT_DIFF" != "" ]; then
+	echo "$GIT_DIFF" >${BALLPATH}/${CHK_NAME}-${BALLSUFX}.patch
+	echo "Patch file '${BALLPATH}/${CHK_NAME}-${BALLSUFX}.patch' created."
+fi
 
-# are we formattting patches?
+# are we formatting patches?
 if [ "$PATCHGIT" == "YES" ]; then
+	[ PATCHNUM=="" ] && PATCHNUM=1
 	BALLSUFX="${BALLSUFX}_patches"
 	rm -rf ${BALLPATH}/${CHK_NAME}
-	git format-patch -o ${BALLPATH}/${CHK_NAME}${BALLSUFX} -${PATCHNUM}
+	git format-patch -o ${BALLPATH}/${CHK_NAME}-${BALLSUFX} -${PATCHNUM}
 	[ $? -ne 0 ] && echo "Error running git?" && exit 1
 fi
diff --git a/packthis b/packthis
--- a/packthis
+++ b/packthis
@@ -4,10 +4,12 @@
 # - written by azman@my1matrix.net
 # - to pack current working directory
 
-CURRPATH=$(pwd)
-WORKPATH=$(dirname $CURRPATH)
+THISPATH=`dirname $0`
+THISPATH=`cd $THISPATH;pwd`
+CURRPATH=`pwd`
+WORKPATH=`dirname $CURRPATH`
 BALLPATH=$HOME/temp
-BALLNAME=$(basename $CURRPATH)
+BALLNAME=`basename $CURRPATH`
 MAINNAME=${MAINNAME:="$BALLNAME"}
 NAMESUFX=${NAMESUFX:=""}
 BALLSUFX=${BALLSUFX:=""}
@@ -31,6 +33,15 @@ CHK_NAME=
 CHK_COPY=
 CHK_EXTN=
 
+# if requested, use gitpack
+GIT_REQS=`echo $@ | grep -- "--git"`
+if [ "$GIT_REQS" != "" ]; then
+	[ ! -d "$CURRPATH/.git" ] &&
+		echo "Not a git path! Abort!" && exit 1
+	${THISPATH}/gitpack `echo $@|sed 's/--git//'`
+	exit $?
+fi
+
 while [ "$1" != "" ]; do
 	case $1 in
 		--suffix|--name-suffix)
@@ -43,6 +54,8 @@ while [ "$1" != "" ]; do
 			;;
 		--name)
 			shift
+			[ "$1" == "" ] &&
+				echo "No name given ? ['$1']?" && exit 1
 			MAINNAME="$1"
 			;;
 		--time)
@@ -51,7 +64,7 @@ while [ "$1" != "" ]; do
 		--ignore-git)
 			CHECKGIT="NO"
 			;;
-		--bundle-git|--git)
+		--bundle-git)
 			CHECKGIT="NO"
 			BUNDLGIT="YES"
 			PATCHGIT="NO"
@@ -116,7 +129,7 @@ if [ "$BUNDLGIT" == "YES" ]; then
 		[ $? -ne 0 ] && echo "Error running git?" && exit 1
 	else
 		if [ "$CHECKGIT" == "ALL" ] ; then
-			CHK_BRANCH="--branches --tags"
+			CHK_BRANCH="--branches --tags" # maybe do '--all'?
 		else
 			CHK_BRANCH="$(git branch|grep "* ")"
 			CHK_BRANCH="${CHK_BRANCH#* }"
