Updated *_kernel scripts
- more like a code cleanup...

diff --git a/install_kernel b/install_kernel
--- a/install_kernel
+++ b/install_kernel
@@ -13,6 +13,7 @@ SMAP="System.map"
 EXTD=`uname -m`
 [ "$EXTD" = "x86_64" ] && EXTD=".x64" || EXTD=
 EXEC=0
+REDO=0
 
 verify_path()
 {
@@ -22,6 +23,7 @@ verify_path()
 while [ ! -z "$1" ] ; do
 	case $1 in
 		-x|--exec) EXEC=1 ;;
+		-r|--redo) REDO=1 ;;
 		-n|--name) NAME=$1 ;;
 		-p|--path) verify_path $1 ; FROM=`cd $1 ; pwd` ;;
 		-*) echo "Unknown option $1!" && exit 1 ;;
@@ -44,15 +46,34 @@ SMAP_SRC="$SMAP"
 BOOT_TGT="$BOOT-$NAME-$VERS"
 CONF_TGT="$CONF-$NAME-$VERS$EXTD"
 SMAP_TGT="$SMAP-$NAME-$VERS"
+BOOT_CHK="/boot/$BOOT_TGT"
+CONF_CHK="/boot/$CONF_TGT"
+SMAP_CHK="/boot/$SMAP_TGT"
 
 echo "Path:{$MAIN} Version:{$VERS}"
 
 if [ $UID -ne 0 ] ; then
 	echo "Must be root!"
-	echo "-- $BOOT_SRC => $BOOT_TGT"
-	echo "-- $CONF_SRC => $CONF_TGT"
-	echo "-- $SMAP_SRC => $SMAP_TGT"
+	echo "-- $BOOT_SRC => $BOOT_CHK"
+	echo "-- $CONF_SRC => $CONF_CHK"
+	echo "-- $SMAP_SRC => $SMAP_CHK"
 	exit 1
+fi
+
+redo_target()
+{
+	local file=$1
+	if [ -f "$file" ] ; then
+		echo -n "Removing target '$file'... "
+		rm $file
+		[ $? -eq 0 ] && echo "done." || echo "error?"
+	fi
+}
+
+if [ $REDO -ne 0 ] ; then
+	redo_target $BOOT_CHK
+	redo_target $CONF_CHK
+	redo_target $SMAP_CHK
 fi
 
 check_source()
@@ -66,25 +87,24 @@ check_source $SMAP_SRC
 
 check_target()
 {
-	local path=$1
-	local file=$2
-	local full=$path/$file
-	[ -f "$full" ] && echo "Target exists '$full'! Aborting!" && exit 1
+	local file=$1
+	[ -f "$file" ] && echo "Target exists '$file'! Aborting!" && exit 1
 }
-check_target /boot $BOOT_TGT
-check_target /boot $CONF_TGT
-check_target /boot $SMAP_TGT
-[ -d "$MODS" ] && echo "Modules path '$MODS' detected! Aborting!" && exit 1
+check_target $BOOT_CHK
+check_target $CONF_CHK
+check_target $SMAP_CHK
 
 if [ $EXEC -ne 0 ] ; then
 	echo -n "Install kernel... "
-	# copy stuffs to /boot
-	cp $BOOT_SRC /boot/$BOOT_TGT
-	cp $CONF_SRC /boot/$CONF_TGT
-	cp $SMAP_SRC /boot/$SMAP_TGT
-	# also install modules
+	cp $BOOT_SRC $BOOT_CHK
+	cp $CONF_SRC $CONF_CHK
+	cp $SMAP_SRC $SMAP_CHK
 	echo "done."
-	echo -h "Install modules... "
-	make modules_install
-	echo "done."
+	if [ -d "$MODS" ] ; then
+		echo "Modules path '$MODS' detected!"
+	else
+		echo -h "Install modules... "
+		make modules_install
+		echo "done."
+	fi
 fi
diff --git a/make_kernel b/make_kernel
--- a/make_kernel
+++ b/make_kernel
@@ -35,10 +35,10 @@ done
 [ $UID -ne 0 ] && echo "Must be root!" && exit 1
 PICK_FILE="linux-${PICK_VERS}.tar.xz"
 PICK_FULL="$PICK_PATH/${PICK_FILE}"
-[ ! -f "$PICK_FULL" ] && echo "Cannot find file '${PICK_FULL}'!" && exit 1
 PICK_BASE=`basename $PICK_FULL .tar.xz`
 cd /usr/src
 if [ $PICK_KEEP -eq 0 ] ; then
+	[ ! -f "$PICK_FULL" ] && echo "Cannot find file '${PICK_FULL}'!" && exit 1
 	[ -d "$PICK_BASE" ] && echo "Removing old $PICK_BASE!" && rm -rf $PICK_BASE
 	echo "-- Extracting $PICK_FILE to "`pwd`
 	tar xf $PICK_FULL
