Update Commit
- major rewrite for slack-related scripts
- clean-up collection (deleted unused scripts)...
  = ttykerm no longer needed (using my1termu ;p)
  = wwwperm moved to repo for www-related scripts...

diff --git a/libmy1slack b/libmy1slack
--- a/libmy1slack
+++ b/libmy1slack
@@ -1,10 +1,11 @@
 #!/bin/bash
 
-# libmy1slack (by azman@my1matrix.net)
-# -> library function for my1slack system management
+# libmy1slack
+# - written by azman@my1matrix.net
+# - library functions for slackware system management
 
 MY1_LIBNAME="libmy1slack"
-MY1_LIBVERS="2011.12.00"
+MY1_LIBVERS="2012.03.00"
 MY1_LIBCALL="$(basename $0 .sh)"
 
 # determine slackware architecture, NOT machine's!
@@ -48,6 +49,11 @@ if [[ "$MY1_DEBUG" == "YES" ]]; then
 	echo "[DEBUG-$$] ==> Command Call '$MY1_LIBCALL'"
 fi
 
+function must_be_root()
+{
+	[[ $UID -ne 0 ]] && echo -e "Abort: must run as root!\n" && exit 1
+}
+
 function get_pkg_info()
 {
 	# get pkg info from name (i.e. filename minus extension!)
@@ -62,27 +68,36 @@ function get_pkg_info()
 	echo -n "$pkg_name $pkg_vers $pkg_arch $pkg_extd"
 }
 
-function get_softpack()
+function get_pathpack()
 {
-	local pkg_list
-	local pkg_pack="${SLACKPKGPATH}/$1"
+	# make a package list from custom path
+	local pkg_list=""
+	local pkg_pack="$(cd $1;pwd)"
 	if [[ -d $pkg_pack ]]; then
 		cd $pkg_pack
 		for pkg_file in *.t[gx]z; do
-			pkg_list="$pkg_list ${pkg_file%.t[gx]z}"
+			pkg_list="$pkg_list ${pkg_file%.t[gx]z}" # trim extension
 		done
+		cd - >/dev/null
 	fi
 	echo -n "$pkg_list"
 }
 
+function get_softpack()
+{
+	# make a package list from official software set (e.g. a,d,l...)
+	echo -n "$(get_pathpack ${SLACKPKGPATH}/$1)"
+}
+
 function comp_package()
 {
+	# compare 2 packages (based on filename), returns 0 if the same!
 	local pkg1_file="$1"
 	local pkg2_file="$2"
 	local pkg_temp
 	local pkg1_name pkg1_vers pkg1_arch pkg1_extd
 	local pkg2_name pkg2_vers pkg2_arch pkg2_extd
-
+	# extract info components
 	pkg_temp=($(get_pkg_info $pkg1_file))
 	pkg1_name="${pkg_temp[0]}"
 	pkg1_vers="${pkg_temp[1]}"
@@ -93,17 +108,18 @@ function comp_package()
 	pkg2_vers="${pkg_temp[1]}"
 	pkg2_arch="${pkg_temp[2]}"
 	pkg2_extd="${pkg_temp[3]}"
-
+	# do compare!
 	[[ "$pkg1_name" == "$pkg2_name" ]] || return 1
 	[[ "$pkg1_vers" == "$pkg2_vers" ]] || return 2
 	[[ "$pkg1_arch" == "$pkg2_arch" ]] || return 3
 	[[ "$pkg1_extd" == "$pkg2_extd" ]] || return 4
-
+	# okay.. the same!
 	return 0
 }
 
 function pkg_db_package()
 {
+	# get package info from mirror tree and put into db!
 	local pkg_name="$1"
 	local pkg_flag="$2"
 	local pkg_info pkg_long pkg_file pkg_path
@@ -112,7 +128,6 @@ function pkg_db_package()
 	local pkg_test=$(cat $SLACKPKGFILE | grep -e "$pkg_temp" -A3)
 	[[ "$pkg_test" = "" ]] && return 1
 	[[ "$pkg_flag" == "--check" ]] && echo -n "$pkg_name" && return 0
-
 	# extract info
 	pkg_file=$(echo "$pkg_test" | grep 'PACKAGE NAME')
 	pkg_file="${pkg_file##* }"
@@ -133,12 +148,14 @@ function pkg_db_package()
 	eval pkgfull_${pkg_name//[-.]/_}="$pkg_full"
 	eval pkgbase_${pkg_name//[-.]/_}="$pkg_base"
 	eval pkgdesc_${pkg_name//[-.]/_}='$pkg_desc'
-
+	# done!
 	return 0
 }
 
 function pkg_db_install()
 {
+	# get package info from current installation and put into db!
+	# CHECKED20120324: HAVE TO DO THIS IN DIFFERENT FUNCTION FROM ABOVE!
 	local pkg_name="$1"
 	local pkg_flag="$2"
 	local pkg_base pkg_file pkg_path
@@ -147,7 +164,6 @@ function pkg_db_install()
 	local pkg_test=$(ls $SLACKINSTLOG | grep -e "$pkg_temp")
 	[[ "$pkg_test" = "" ]] && return 1
 	[[ "$pkg_flag" == "--check" ]] && echo -n "$pkg_name" && return 0
-
 	# extract info
 	pkg_temp="$SLACKINSTLOG/$pkg_test"
 	pkg_test=$(cat $pkg_temp | grep -e "^PACKAGE NAME:" -A3)
@@ -169,12 +185,13 @@ function pkg_db_install()
 	eval pkgfull_${pkg_name//[-.]/_}="$pkg_full"
 	eval pkgbase_${pkg_name//[-.]/_}="$pkg_base"
 	eval pkgdesc_${pkg_name//[-.]/_}='$pkg_desc'
-
+	# done!
 	return 0
 }
 
 function find_infile()
 {
+	# get package entry from a file
 	local pkg_base="$1"
 	local pkg_test="$2"
 	local pkg_temp="\<${pkg_test}-[^-]*-[^-]*-[^-]*$"
@@ -184,6 +201,7 @@ function find_infile()
 
 function find_inpath()
 {
+	# get package entry from file(s) in a path (filename)
 	local pkg_test="$1"
 	local tgt_path="$2"
 	[[ -d "$tgt_path" ]] || tgt_path="."
@@ -194,6 +212,7 @@ function find_inpath()
 
 function find_install()
 {
+	# get package entry from current installation
 	local pkg_test="$1"
 	local pkg_temp="\<${pkg_test}-[^-]*-[^-]*-[^-]*$"
 	local pkg_file=$(ls $SLACKINSTLOG | grep -e "$pkg_temp")
@@ -202,6 +221,7 @@ function find_install()
 
 function find_package()
 {
+	# get package entry from mirror tree
 	local pkg_test="$1"
 	local pkg_temp="\<PACKAGE NAME:  ${pkg_test}-[^-]*-[^-]*-[^-]*\.t[gx]z\>"
 	local pkg_file=$(cat $SLACKPKGFILE | grep -e "$pkg_temp")
@@ -212,12 +232,13 @@ function find_package()
 
 function show_info()
 {
+	# print package info (including desc entry!)
 	local pkg_test="$1"
 	local pkg_path pkg_size pkg_full
 	local pkg_stat pkg_flag pkg_base
 	local pkg_temp pkg_desc pkg_log pkg_file
 	local pkg_name pkg_vers pkg_arch pkg_extd
-
+	# extracting information
 	pkg_temp="pkgbase_${pkg_test//-/_}"
 	[[ -z "${!pkg_temp}" ]] && return
 	pkg_base="${!pkg_temp}"
@@ -239,17 +260,11 @@ function show_info()
 	[[ "$pkg_path" == "" ]] && pkg_path="Unknown"
 	[[ "$pkg_size" == "" ]] && pkg_size="Unknown"
 	[[ "$pkg_full" == "" ]] && pkg_full="Unknown"
-
-	if [[ "$(find_install $pkg_name)" == "" ]]; then
-		pkg_flag="NOT "
-	else
-		pkg_flag=""
-	fi
-	if [[ "$(find_package $pkg_name)" == "" ]]; then
-		pkg_stat=" (ALIEN!)"
-	else
+	pkg_flag=""
+	[[ "$(find_install $pkg_name)" == "" ]] && pkg_flag="NOT "
 		pkg_stat=""
-	fi
+	[[ "$(find_package $pkg_name)" == "" ]] && pkg_stat=" (ALIEN!)"
+	# do the printing
 	local title="PACKAGE <$pkg_name> - BEGIN"
 	local trail="PACKAGE <$pkg_name> - END"
 	for (( a=0;a<${#title};a++ )) ; do echo -n "-"; done ; echo
@@ -263,47 +278,19 @@ function show_info()
 	echo "SIZE (Compressed)  : $pkg_size"
 	echo "SIZE (Uncompressed): $pkg_full"
 	echo "INSTALL STATUS     : ${pkg_flag}INSTALLED"
-	echo "DESCRIPTION        :"
-	echo -e "$pkg_desc"
+	[[ "$pkg_desc" != "" ]] &&
+	echo "DESCRIPTION        : " && echo -e "$pkg_desc"
 	for (( a=0;a<${#trail};a++ )) ; do echo -n "-"; done ; echo
 	echo "$trail"
 	for (( a=0;a<${#trail};a++ )) ; do echo -n "-"; done ; echo ; echo
 }
 
-function find_alien_pkgs()
-{
-	local pkg_list pkg_name
-
-	# find installed
-	for pkg_base in $(ls $SLACKINSTLOG); do
-		pkg_name="${pkg_base%-*-*-*}"
-		# find if alien
-		[[ "$(find_package $pkg_name)" == "" ]] && pkg_list="$pkg_list $pkg_base"
-	done
-
-	echo -n "$pkg_list"
-}
-
-function find_datab_pkg()
-{
-	# find package from db, if not found create entry!
-	local pkg_name="$1"
-	local pkg_temp pkg_base
-
-	pkg_temp="pkgbase_${pkg_name//-/_}"
-	[[ -z "${!pkg_temp}" ]] && pkg_db_package $pkg_name
-	[[ -z "${!pkg_temp}" ]] && pkg_db_install $pkg_name
-	[[ -z "${!pkg_temp}" ]] && return 1
-	pkg_base="${!pkg_temp}"
-
-	echo -n "$pkg_base"
-	return 0
-}
-
 function format_text()
 {
-	local begin="\033[0m"
-	local end="\033[0m"
+	# oooh! blinking color text!
+	local mark="\033[0m"
+	local begin=$mark
+	local end=$mark
 	local bold="\033[1m"
 	local uline="\033[4m"
 	local blink="\033[5m"
@@ -319,7 +306,7 @@ function format_text()
 	local cyan="\033[36m"
 	local white="\033[37m"
 	local text=""
-
+	# check options
 	while [ "$1" != "" ]; do
 		case "$1" in
 		--bold) begin="${begin}${bold}" ;;
@@ -338,28 +325,34 @@ function format_text()
 				*) color="$black" ;;
 			esac
 			begin="${begin}${color}";;
-		--text)
-			shift; text="$1";;
+		*)
+			text="${begin}${1}${end}"; begin=$mark;;
 		esac
 		shift
 	done	
-	echo -e "$begin""$text""$end"
+	echo -e "$text"
 }
 
 function test_param()
 {
-	local test="$1"
-	echo "Param @ is $@"
-	echo "Param * is $*"
-	echo "Param 1 is $1"
-	echo "Param test is $test"
+	# just testing...
+	local test="$@"
+
+
+	echo "Param count: $#"
+	echo "Param \$@ is $@"
+	echo "Param \$* is $*"
+	echo "Param \$1 is $1"
+	echo "Param \$test is $test"
 	shift
 	echo "Params shifted by 1!"
-	test="$1"
-	echo "Param @ is $@"
-	echo "Param * is $*"
-	echo "Param 1 is $1"
-	echo "Param test is $test"
+	# $* similar to $@, but use IFS as separator
+	test="$@"
+	echo "Param count: $#"
+	echo "Param \$@ is $@"
+	echo "Param \$* is $*"
+	echo "Param \$1 is $1"
+	echo "Param \$test is $test"
 	shift
-	echo "Param \$ is $$"
+	echo "Param \$\$ is $$"
 }
diff --git a/slackpatch b/slackpatch
--- a/slackpatch
+++ b/slackpatch
@@ -5,32 +5,32 @@
 # - slackware patch manager
 
 # standard tool info
-TOOL_THISFUNC="my1 Slackware Patch Tool"
-TOOL_THISVERS="2011.12.00"
-# standard tool conf
-TOOL_CHECKCMD="$@"
-TOOL_COMMANDS=${TOOL_CHECKCMD:="help"}
-TOOL_THISFILE=$(basename $0 .sh)
-TOOL_LOCATION=$(cd $(dirname $0);pwd)
-TOOL_CONFFILE="$TOOL_THISFILE.conf"
-TOOL_MY1SLACK="libmy1slack"
+MY1_TOOLNAME="my1 Slackware Patch Tool"
+MY1_TOOLVERS="2012.03.00"
+MY1_TOOLBASE=$(basename $0 .sh)
+MY1_TOOLPATH=$(cd $(dirname $0);pwd)
+MY1_TOOL_LIB="libmy1slack"
 # look for config file
-for conf_path in  $(pwd) $TOOL_LOCATION ; do
-	config_file="${conf_path}/${TOOL_CONFFILE}"
-	[[ -r $config_file ]] && source $config_file && break
+for config in $(pwd) $MY1_TOOLPATH $HOME; do
+	config=$config/.$MY1_TOOLBASE
+	[[ ! -f $config ]] && continue
+	source $config ; break
 done
 # look for my1slack library
-[[ -r "$TOOL_LOCATION/$TOOL_MY1SLACK" ]] && source $TOOL_LOCATION/$TOOL_MY1SLACK
+[[ -r "$MY1_TOOLPATH/$MY1_TOOL_LIB" ]] &&
+	source $MY1_TOOLPATH/$MY1_TOOL_LIB
+
 # my1slack tool specific
-TOOL_SLACKDIR=${TOOL_SLACKDIR:="${SLACKROOTDIR}/${SLACKRELEASE}"}
-TOOL_PATCHDIR=${TOOL_PATCHDIR:="${TOOL_SLACKDIR}/patches/packages"}
-TOOL_LOGFILE=${TOOL_LOGFILE:="/tmp/${TOOL_THISFILE%%.*}.log"}
+MY1_SLACKDIR=${MY1_SLACKDIR:="${SLACKROOTDIR}/${SLACKRELEASE}"}
+MY1_PATCHDIR=${MY1_PATCHDIR:="${MY1_SLACKDIR}/patches/packages"}
+MY1_LOG_FILE=${MY1_LOG_FILE:="${MY1_TOOLPATH}/${MY1_TOOLBASE%%.*}.log"}
 # global options & settings
 OPT_FULLINFO="NO"
 OPT_AUTOPATCH="YES"
+OPT_LOGFILE="/dev/null"
 MSG_THISHELP=$(cat <<SETHELPMSG
 Usage:
-  $TOOL_THISFILE <command> [options]
+  $MY1_TOOLBASE <command> [options]
 Commands:
   check : Check patch status (find relevant patches)
   pdone : List patches that has been applied
@@ -42,12 +42,13 @@ Options:
   --full   : Full Info
   --prompt : Prompt Before Patching
   --auto   : Auto-Patch
+  --log    : Write to log file
   --path <path_name> : Specify additional patch path
   --pkg <package_name> : Auto-Patch Implied!
 Mirror Source:
-  $TOOL_SLACKDIR
+  $MY1_SLACKDIR
 Log File:
-  $TOOL_LOGFILE
+  $MY1_LOG_FILE
 SETHELPMSG
 )
 
@@ -57,8 +58,9 @@ function find_patches()
 	local pat_vers pat_arch pat_extd
 	local pkg_temp pkg_base pkg_name
 	local pkg_vers pkg_arch pkg_extd
-	local curr_dir=$(pwd)
-
+	local chk_name chk_stat chk_file chk_vers
+	local chk_path=$(pwd)
+	# process all package files
 	for pat_file in *.t[gx]z; do
 		# check extension first
 		pat_exts="${pat_file##*.}"
@@ -69,6 +71,10 @@ function find_patches()
 		pat_vers="${pkg_temp[1]}"
 		pat_arch="${pkg_temp[2]}"
 		pat_extd="${pkg_temp[3]}"
+		# populate information
+		chk_name="$pat_name"
+		chk_file="${chk_path}/${pat_file}"
+		chk_vers="[${pat_vers}/${pat_extd}]"
 		# find installed
 		pkg_base="$(find_install $pat_name)"
 		if [[ "$pkg_base" != "" ]]; then
@@ -77,111 +83,150 @@ function find_patches()
 			pkg_vers="${pkg_temp[1]}"
 			pkg_arch="${pkg_temp[2]}"
 			pkg_extd="${pkg_temp[3]}"
+			# skip if for different arch!
+			[[ "$pkg_arch" != "$pat_arch" ]] && continue
+			# check version update
 			if [[ "$pkg_vers" == "$pat_vers" ]] &&
 				[[ "$pkg_extd" == "$pat_extd" ]]; then
-				PAT_LIST="$PAT_LIST $pat_name"
-				eval patchstat_${pat_name//[-.]/_}="pdone"
-				eval patchfile_${pat_name//[-.]/_}=${curr_dir}/${pat_file}
-				eval patchvers_${pat_name//[-.]/_}=[${pat_vers}/${pat_extd}]
+				chk_stat="pdone"
 			else
-				PAT_LIST="$PAT_LIST $pat_name"
-				eval patchstat_${pat_name//[-.]/_}="check"
-				eval patchfile_${pat_name//[-.]/_}=${curr_dir}/${pat_file}
-				eval patchvers_${pat_name//[-.]/_}=[${pkg_vers}/${pkg_extd}]-to-[${pat_vers}/${pat_extd}]
+				chk_stat="check"
+				chk_vers="[${pkg_vers}/${pkg_extd}]->[${pat_vers}/${pat_extd}]"
 			fi
 		else
-			PAT_LIST="$PAT_LIST $pat_name"
-			eval patchstat_${pat_name//[-.]/_}="nlist"
-			eval patchfile_${pat_name//[-.]/_}=${curr_dir}/${pat_file}
-			eval patchvers_${pat_name//[-.]/_}=[${pat_vers}/${pat_extd}]
+			chk_stat="nlist"
 		fi
+		echo "$chk_name $chk_stat $chk_file $chk_vers"
 	done
-	cd $curr_dir
 }
 
 function check_patches()
 {
-	local curr_dir=$(pwd)
-	[[ ! -d $TOOL_PATCHDIR ]] &&
-		echo -e "Path '$TOOL_PATCHDIR' not found! Aborting!\n" && exit 1
-	cd $TOOL_PATCHDIR
-	TOOL_PATCHDIR=$(pwd)
-	find_patches
-	KERNEL_PATPATH=$(find . -name "linux-*" -type d -maxdepth 1)
-	for path in $KERNEL_PATPATH; do
+	local pat_path pat_list
+	local lnx_path chk_path=$(pwd)
+	MY1_PATCHDIR=$(cd $MY1_PATCHDIR;pwd)
+	[[ ! -d $MY1_PATCHDIR ]] &&
+		echo -e "Path '$MY1_PATCHDIR' not found! Aborting!\n" && exit 1
+	cd $MY1_PATCHDIR
+	pat_list=$(find_patches)
+	# look for paths for kernel patches
+	lnx_path=$(find . -name "linux-*" -type d -maxdepth 1)
+	for path in $lnx_path; do
 		cd $path
-		find_patches
-		cd $TOOL_PATCHDIR
+		pat_list="${pat_list}$(find_patches)"
+		cd $MY1_PATCHDIR
 	done
+	# process extra paths
 	while [[ "$1" != "" ]]; do
-		cd $1
-		find_patches
+		pat_path=$(cd $1;pwd)
+		[[ ! -d $pat_path ]] && 
+			echo -e "Path '$pat_path' is invalid! Aborting!\n" && exit 1
+		cd $pat_path
+		pat_list="${pat_list}$(find_patches)"
+		cd - >/dev/null
 		shift
-	done
-}
-
-function extract_patches()
-{
-	local pkg_temp pat_list pkg_list pkg_opts
-	pkg_opts=$1; shift; pkg_list=$@
-	pat_list=""
-	for pkg_name in $pkg_list ; do
-		pkg_temp="patchstat_${pkg_name//-/_}"
-		[[ "${!pkg_temp}" == "$pkg_opts" ]] && pat_list="$pat_list $pkg_name"
 	done
 	echo -n "$pat_list"
 }
 
-function check_request()
+function apply_patch()
 {
-	local pkg_temp pkg_list
-	pkg_list=""
-	for pkg_name in $@ ; do
-		pkg_temp="patchstat_${pkg_name//-/_}"
-		[[ "${!pkg_temp}" == "check" ]] && pkg_list="$pkg_list $pkg_name"
-	done
-	echo -n "$pkg_list"
+	local pat_temp pat_name pat_stat pat_file do_update
+	pat_temp=($(echo "$@"))
+	pat_name=${pat_temp[0]}
+	pat_stat=${pat_temp[1]}
+	pat_file=${pat_temp[2]}
+	# check if can be applied
+	[[ "$pat_stat" != "check" ]] && return # patch not needed
+	[[ ! -r "$pat_file" ]] &&
+		echo "Error: File '$pat_file' not found!" && exit 1
+	# apply the patch!
+	if [[ "$OPT_AUTOPATCH" == "NO" ]] ; then
+		read -n 1 -p "Update '$pat_name'? [y]/[*]/[q] : " do_update ; echo
+		if [[ "$do_update" == "y" ]]; then
+			echo -n "Updating '$pat_name'... "
+			/sbin/upgradepkg ${pat_file} >>$OPT_LOGFILE
+			echo "done."
+		elif [[ "$do_update" == "q" ]]; then
+			echo "Aborting on '$pat_name'!"
+			exit 1
+		fi
+	elif [[ "$OPT_AUTOPATCH" == "YES" ]] ; then
+		echo -n "Auto-updating '$pat_name'... "
+		/sbin/upgradepkg ${pat_file} >>$OPT_LOGFILE
+		echo "done."
+	fi
 }
 
-function must_be_root()
+function display_patches()
 {
-	[[ $UID -ne 0 ]] && echo -e "Abort: must run as root!\n" && exit 1
+	local pat_temp pat_name pat_stat pat_file pat_vers
+	local pat_opts pat_list chk_null
+	pat_opts=$1 ; shift ; pat_list=("$@")
+	#echo "Patch Count: ${#pat_list[@]}"
+	[[ "$pat_opts" == "check" ]] && echo "Packages need updating:"
+	[[ "$pat_opts" == "pdone" ]] && echo "Packages already up-to-date:"
+	[[ "$pat_opts" == "nlist" ]] && echo "Unknown patches:"
+	for (( a=0;a<${#pat_list[@]};a++ )); do
+		pat_temp=($(echo ${pat_list[$a]}))
+		pat_name=${pat_temp[0]}
+		pat_stat=${pat_temp[1]}
+		#pat_file=${pat_temp[2]}
+		pat_vers=${pat_temp[3]}
+		#echo "Check: ${pat_temp[0]}, (${pat_stat}:${pat_opts})"
+		if [[ "$pat_stat" == "$pat_opts" ]] ; then
+			chk_null="NO"
+			[[ "$OPT_FULLINFO" == "NO" ]] && echo -n "$pat_name "
+			[[ "$OPT_FULLINFO" == "YES" ]] && echo "$pat_name: ${pat_vers}"
+		fi
+	done
+	# prettify output
+	if [[ "$chk_null" == "NO" ]] ; then
+		[[ "$OPT_FULLINFO" != "YES" ]] && echo
+	else
+		[[ "$pat_opts" == "check" ]] && echo "** No updates found! **"
+		[[ "$pat_opts" == "pdone" ]] && echo "** No up2date patches! **"
+		[[ "$pat_opts" == "nlist" ]] && echo "** No unknown patches! **"
+	fi
+	echo
 }
 
 function execute_patches()
 {
-	local pkg_temp pkg_file pkg_vers
-	local pkg_list=$(check_request $@)
-
-	must_be_root
-
-	[[ "$pkg_list" == "" ]] && pkg_list=$(extract_patches check $PAT_LIST)
-	if [[ ! -z "$pkg_list" ]]; then
-		echo -e "$TOOL_THISFILE - $TOOL_THISFUNC ($TOOL_THISVERS)\n$(date)\n" >$TOOL_LOGFILE
+	local pat_temp pat_name pat_stat pat_file pat_vers
+	local pat_opts pat_list pkg_list chk_list log_init
+	#echo "Parameter Count: ${#}"
+	# only root can apply patches!
+	must_be_root 
+	# get pkg request list
+	while [[ "$1" != "" ]]; do
+		[[ "$1" == "--patches" ]] && break;
+		pkg_list="$pkg_list $1"
+		shift
+	done
+	pkg_list=($(echo $pkg_list))
+	# get available patches list
+	shift && pat_list=("$@")
+	# check for requested package
+	for (( x=0,y=0;x<${#pat_list[@]};x++ )); do
+		pat_temp=($(echo ${pat_list[$x]}))
+		pat_name=${pat_temp[0]}
+		pat_stat=${pat_temp[1]}
+		pat_file=${pat_temp[2]}
+		if [[ ${#pkg_list[@]} -eq 0 ]] ||
+			[[ "$(echo ${pkg_list[@]} | grep $pat_name)" != "" ]] ; then
+			chk_list[$y]="$pat_name $pat_stat $pat_file"
+			(( y++ ))
+		fi
+	done
+	#echo "Check Count: ${#chk_list[@]}"
+	# browse through the check list
+	if [[ ${#chk_list[@]} -gt 0 ]]; then
+		log_init="$MY1_TOOLBASE - $MY1_TOOLNAME ($MY1_TOOLVERS) - $(date)\n"
+		echo -e $log_init >$OPT_LOGFILE
 		echo "Packages need updating:"
-		for pkg_name in $pkg_list ; do
-			pkg_temp="patchstat_${pkg_name//-/_}"
-			[[ "${!pkg_temp}" != "check" ]] && continue
-			pkg_temp="patchfile_${pkg_name//-/_}"
-			pkg_file=${!pkg_temp}
-			pkg_temp="patchvers_${pkg_name//-/_}"
-			pkg_vers=${!pkg_temp}
-			[[ ! -r "$pkg_file" ]] && echo "Error: File '$pkg_file' not found!" && exit 1
-			if [[ "$OPT_AUTOPATCH" == "NO" ]] ; then
-				read -n 1 -p "Update package '$pkg' ? [y]/[*]/[q] : " do_update ; echo
-				if [[ "$do_update" == "y" ]]; then
-					echo -n "Updating '$pkg_name'... "
-					/sbin/upgradepkg ${pkg_file} >>$TOOL_LOGFILE
-					echo "done."
-				elif [[ "$do_update" == "q" ]]; then
-					echo "Aborting on '$pkg_name'!"
-					exit 1
-				fi
-			elif [[ "$OPT_AUTOPATCH" == "YES" ]] ; then
-				echo -n "Auto-updating '$pkg_name'... "
-				/sbin/upgradepkg ${pkg_file} >>$TOOL_LOGFILE
-				echo "done."
-			fi
+		for (( x=0;x<${#chk_list[@]};x++ )); do
+			apply_patch "${chk_list[$x]}"
 		done
 	else
 		echo "Nothing to patch/upgrade!"
@@ -189,43 +234,11 @@ function execute_patches()
 	echo
 }
 
-function display_patches()
-{
-	local pkg_temp pkg_file pkg_vers pkg_list pkg_opts
-
-	pkg_opts=$1; shift; pkg_list=$(extract_patches $pkg_opts $PAT_LIST)
-	if [[ ! -z "$pkg_list" ]]; then
-		[[ "$pkg_opts" == "check" ]] && echo "Packages need updating:"
-		[[ "$pkg_opts" == "pdone" ]] && echo "Packages already up-to-date:"
-		[[ "$pkg_opts" == "nlist" ]] && echo "Unknown patches:"
-		for pkg_name in $pkg_list ; do
-			pkg_temp="patchstat_${pkg_name//-/_}"
-			[[ "${!pkg_temp}" != "$pkg_opts" ]] && continue
-			pkg_temp="patchfile_${pkg_name//-/_}"
-			pkg_file=${!pkg_temp}
-			pkg_temp="patchvers_${pkg_name//-/_}"
-			pkg_vers=${!pkg_temp}
-			if [[ "$OPT_FULLINFO" == "NO" ]] ; then
-				echo -n "$pkg_name "
-			elif [[ "$OPT_FULLINFO" == "YES" ]] ; then
-				echo "$pkg_name: ${pkg_vers}"
-			fi
-		done
-		[[ "$OPT_FULLINFO" != "YES" ]] && echo
-	else
-		[[ "$pkg_opts" == "check" ]] && echo "No updates found!"
-		[[ "$pkg_opts" == "pdone" ]] && echo "No up2date patches!"
-		[[ "$pkg_opts" == "nlist" ]] && echo "No unknown patches!"
-	fi
-	echo
-}
-
 function process_command()
 {
 	local go_commands="check pdone nlist patch"
-	local do_command=""
-	local pkg_list="" pkg_path=""
-	local pkg_temp
+	local do_command
+	local pkg_list pkg_path pkg_temp pat_list
 	# check parameters
 	while [[ "$1" != "" ]]; do
 		case "$1" in
@@ -241,11 +254,14 @@ function process_command()
 			--auto)
 				OPT_AUTOPATCH="YES"
 				;;
+			--log)
+				OPT_LOGFILE="$MY1_LOG_FILE"
+				;;
 			--path)
 				shift
 				# check additional path
 				[[ ! -d "$1" ]] &&
-					echo -e "Cannot find path '$1'!\n" && exit 1
+					echo "Cannot find path '$1'!" && exit 1
 				pkg_path="${pkg_path} $(cd $1;pwd)"
 				;;
 			--pkg)
@@ -253,41 +269,50 @@ function process_command()
 				# check discrete package name
 				pkg_temp=$(find_install $1)
 				[[ "$pkg_temp" == "" ]] &&
-					echo -e "Unknown package '$1'!\n" && exit 1
-				pkg_list="${pkg_list} $pkg_temp"
+					echo "Unknown package '$1'!" && exit 1
+				pkg_temp=($(get_pkg_info $pkg_temp))
+				pkg_temp="${pkg_temp[0]}"
+				pkg_list="${pkg_list} ${pkg_temp}"
 				;;
 			--help|-h|help)
-				echo -e "$MSG_THISHELP\n"
+				echo "$MSG_THISHELP"
 				exit 0
 				;;
 			-*)
-				echo -e "Unknown option '$1'!\n" && exit 1
+				echo "Unknown option '$1'!" && exit 1
 				;;
 			*)
 				[[ "$do_command" != "" ]] &&
-					echo -e "Multiple commands '$1' & '$do_command'\n" && exit 1
+					echo "Multiple commands '$1' & '$do_command'" && exit 1
 				for tcommand in $go_commands; do
 					[[ "$1" == "$tcommand" ]] && do_command=$1 && break
 				done
 				[[ "$do_command" == "" ]] &&
-					echo -e "Unknown command '$1'!\n" && exit 1
+					echo "Unknown command '$1'!" && exit 1
 				;;
 		esac
 		shift
 	done
 	# exit if no command...
-	[[ "$do_command" == "" ]] && echo -e "No command given!\n" && exit 1
-	# find packages
-	check_patches $pkg_path
+	[[ "$do_command" == "" ]] && echo "$MSG_THISHELP!" && exit 0
+	# find patches
+	pat_list=$(check_patches $pkg_path)
+	SAVE_IFS=$IFS
+	IFS='
+'
+	pat_list=($(echo "$pat_list"))
+	IFS=$SAVE_IFS
 	# display packages
-	[[ "$do_command" != "patch" ]] && display_patches $do_command
+	[[ "$do_command" != "patch" ]] &&
+		display_patches $do_command "${pat_list[@]}"
 	# patch packages
-	[[ "$do_command" == "patch" ]] && execute_patches $pkg_list
+	[[ "$do_command" == "patch" ]] &&
+		execute_patches $pkg_list --patches "${pat_list[@]}"
 }
 
 # BEGIN MAIN SCRIPT
 
-echo -e "\n$TOOL_THISFILE - $TOOL_THISFUNC ($TOOL_THISVERS)\n"
-process_command $TOOL_COMMANDS
+echo -e "\n$MY1_TOOLBASE - $MY1_TOOLNAME ($MY1_TOOLVERS)\n"
+process_command "$@"
 
 # END MAIN SCRIPT
diff --git a/slackview b/slackview
--- a/slackview
+++ b/slackview
@@ -2,276 +2,293 @@
 
 # slackview
 # - written by azman@my1matrix.net
-# - slackware package viewer/selector
+# - slackware package info viewer
 
 # standard tool info
-TOOL_THISFUNC="my1 Slackware Package Tool"
-TOOL_THISVERS="2011.12.00"
-# standard tool conf
-TOOL_CHECKCMD="$@"
-TOOL_COMMANDS=${TOOL_CHECKCMD:="--help"}
-TOOL_THISFILE=$(basename $0 .sh)
-TOOL_LOCATION=$(cd $(dirname $0);pwd)
-TOOL_CONFFILE="$TOOL_THISFILE.conf"
-TOOL_MY1SLACK="libmy1slack"
+MY1_TOOLNAME="my1 Slackware Package Viewer Tool"
+MY1_TOOLVERS="2012.03.00"
+MY1_TOOLBASE=$(basename $0 .sh)
+MY1_TOOLPATH=$(cd $(dirname $0);pwd)
+MY1_TOOL_LIB="libmy1slack"
 # look for config file
-for conf_path in  $(pwd) $TOOL_LOCATION ; do
-	config_file="${conf_path}/${TOOL_CONFFILE}"
-	[[ -r $config_file ]] && source $config_file && break
+for config in $(pwd) $MY1_TOOLPATH $HOME; do
+	config=$config/.$MY1_TOOLBASE
+	[[ ! -f $config ]] && continue
+	source $config ; break
 done
 # look for my1slack library
-[[ -r "$TOOL_LOCATION/$TOOL_MY1SLACK" ]] && source $TOOL_LOCATION/$TOOL_MY1SLACK
-# my1slack tool specific
+[[ -r "$MY1_TOOLPATH/$MY1_TOOL_LIB" ]] &&
+	source $MY1_TOOLPATH/$MY1_TOOL_LIB
 
-function show_alien_pkgs()
+function pkg_db_check()
 {
-	local do_echo=""
+	local pkg_temp pkg_name=$1
+	pkg_temp="pkgbase_${pkg_name//-/_}"
+	[[ -z "${!pkg_temp}" ]] && pkg_db_package $pkg
+	[[ -z "${!pkg_temp}" ]] && pkg_db_install $pkg
+	[[ -z "${!pkg_temp}" ]] && return 1
+	return 0
+}
 
+function view_alien_pkgs()
+{
+	local do_echo
 	# find installed
-	for pkg_base in $(find_alien_pkgs); do
-		echo "Alien package: ${pkg_base%-*-*-*} ($pkg_base)"
-		do_echo="YES"
+	for pkg_base in $(ls $SLACKINSTLOG); do
+		pkg_name="${pkg_base%-*-*-*}"
+		# find if alien
+		if [[ "$(find_package $pkg_name)" == "" ]]; then
+			echo "Alien package: ${pkg_base%-*-*-*} ($pkg_base)"
+			do_echo="YES"
+		fi
 	done
+	[[ "$do_echo" != "YES" ]] && echo "No alien package found!"
+	echo
+}
 
-	[[ "$do_echo"=="YES" ]] && echo
+function view_show_pkgs()
+{
+	for pkg in "$@"; do
+		pkg_db_check $pkg
+		[[ $? -ne 0 ]] &&
+			echo -e "Package '$pkg' not found!\n" && continue
+		show_info $pkg
+	done
+}
+
+function view_find_package()
+{
+	local pkg_list
+	while [[ "$1" != "" ]]; do
+		case "$1" in
+			--alien)
+				view_alien_pkgs
+				return
+				;;
+			*)
+				pkg_list="$pkg_list $1"
+				;;
+		esac
+		shift
+	done
+	view_show_pkgs $pkg_list
+}
+
+function file_insert_package()
+{
+	local pkg_temp pkg_test
+	local pkg_file=$1
+	local pkg_name=$2
+	pkg_test=$(find_infile $pkg_file $pkg_name)
+	pkg_temp=$(find_package $pkg_name)
+	if [[ "$pkg_test" == "" ]]; then
+		echo $pkg_temp >>$pkg_file
+		echo "Package '$pkg_temp' added to $pkg_file."
+	else
+		# insert/update?
+		sed -i -e "\|^$pkg_name|c\\$pkg_temp" $pkg_file
+		if [[ $? -ne 0 ]]; then
+			echo "Error replacing package '$pkg_temp'! [$pkg_name]"
+		else
+			echo "Package '$pkg_temp' updated in $pkg_file."
+		fi
+	fi
+	echo
+}
+
+function file_remove_package()
+{
+	local pkg_temp
+	local pkg_file=$1
+	local pkg_name=$2
+	pkg_temp=$(find_infile $pkg_file $pkg_name)
+	if [[ "$pkg_temp" == "" ]]; then
+		echo "Package '$pkg_name' not in file!"
+	else
+		# remove?
+		sed -i -e "\|^$pkg_temp|d" $pkg_file
+		if [[ $? -ne 0 ]]; then
+			echo "Error deleting package '$pkg_temp'! [$pkg_name]"
+		else
+			echo "Package '$pkg_temp' deleted from $pkg_file."
+		fi
+	fi
+	echo
+}
+
+function file_option_package()
+{
+	local pkg_temp pkg_test
+	local pkg_file=$1
+	local pkg_name=$2
+	local pkg_stat="INCLUDED"
+	# interactive
+	pkg_test="pkgbase_${pkg_name//-/_}"
+	[[ -z "${!pkg_test}" ]] && pkg_db_package $pkg
+	[[ -z "${!pkg_test}" ]] &&
+		echo "Package '$pkg_name' unknown!" && return
+	show_info $pkg_name
+	pkg_temp=$(find_package $pkg_name)
+	pkg_test=$(find_infile $pkg_file $pkg_name)
+	if [[ "$pkg_test" == "" ]]; then
+		pkg_stat="EXCLUDED"
+	else
+		comp_package $pkg_test $pkg_temp
+		[[ $? -ne 0 ]] &&
+			pkg_stat="INCLUDED ($pkg_test/$pkg_temp) [$?]"
+	fi
+	echo -n "Status: $pkg_stat. "
+	read -n 1 -p "Command ([i]nsert/[d]elete/[*]): " do_select ; echo
+	if [[ "$do_select" == "i" ]]; then
+		file_insert_package $pkg_file $pkg_name
+	elif [[ "$do_select" == "d" ]]; then
+		file_remove_package $pkg_file $pkg_name
+	else
+		echo
+	fi
+}
+
+function file_browse_packages()
+{
+	local pkg_list pkg_name pkg_temp
+	local pkg_file=$1
+	# get all packages on file
+	SAVE_IFS=$IFS
+	IFS='
+'
+	pkg_list=($(cat $pkg_file))
+	IFS=$SAVE_IFS
+	# process the list
+	for (( x=0;x<${#pkg_list[@]}; )); do
+		pkg_temp=($(get_pkg_info ${pkg_list[$x]}))
+		pkg_name=${pkg_temp[0]}
+		echo -n "Package: ${pkg_list[$x]} => "
+		read -n 1 -p "Command ([p]revious/[n]ext/[*]quit): " do_select ; echo
+		if [[ "$do_select" == "n" ]]; then
+			[[ $x -lt ${#pkg_list[@]}-1 ]] && (( x++ ))
+		elif [[ "$do_select" == "p" ]]; then
+			[[ $x -gt 0 ]] && (( x-- ))
+		else
+			break;
+		fi
+	done
+	echo
+}
+
+function file_listall_packages()
+{
+	local pkg_list pkg_name pkg_temp
+	local pkg_file=$1
+	# get all packages on file
+	SAVE_IFS=$IFS
+	IFS='
+'
+	pkg_list=($(cat $pkg_file))
+	IFS=$SAVE_IFS
+	# process the list
+	for (( x=0;x<${#pkg_list[@]};x++ )); do
+		echo "Package: ${pkg_list[$x]}"
+	done
+	echo
+}
+
+function view_file_package()
+{
+	local pkg_list pkg_file pkg_temp pkg_name
+	local do_select do_sort
+	while [[ "$1" != "" ]]; do
+		case "$1" in
+			--select)
+				do_select="YES"
+				;;
+			--unselect)
+				do_select="INV"
+				;;
+			--list)
+				do_select="LST"
+				;;
+			--all)
+				do_select="CHK"
+				;;
+			--name)
+				shift
+				pkg_file="$1"
+				;;
+			--sort)
+				do_sort="YES"
+				;;
+			--pack)
+				shift
+				pkg_temp=$(get_softpack $1)
+				for pkg in $pkg_temp ; do
+					pkg_name=($(get_pkg_info $pkg))
+					pkg_list="$pkg_list ${pkg_name[0]}"
+				done
+				;;
+			*)
+				pkg_list="$pkg_list $1"
+				;;
+		esac
+		shift
+	done
+	# check package file - create if needed
+	[[ "$pkg_file" == "" ]] &&
+		echo -e "[ERROR] File name for package list NOT given!\n" && return
+	[[ ! -f "$pkg_file" ]] && touch "$pkg_file"
+	[[ ! -r "$pkg_file" ]] &&
+		echo -e "[ERROR] Cannot read file '$pkg_file'!\n" && return
+	# check request to browse file
+	[[ "$do_select" == "CHK" ]] && file_browse_packages $pkg_file && return
+	[[ "$do_select" == "LST" ]] && file_listall_packages $pkg_file && return
+	# check if list is empty
+	[[ "$pkg_list" == "" ]] &&
+		echo -e "No package selected? Nothing to do!\n" && return
+	# process the given package list
+	for pkg in $pkg_list; do
+		case $do_select in
+			YES) file_insert_package $pkg_file $pkg ;;
+			INV) file_remove_package $pkg_file $pkg ;;
+			*) file_option_package $pkg_file $pkg ;;
+		esac
+	done
+	# sort file if requested
+	if [[ "$do_sort" == "YES" ]]; then
+		# should be with software set!
+		echo -n "Sorting (with uniq) $pkg_file..."
+		cat $pkg_file | uniq | sort -o $pkg_file
+		echo " done!"
+	fi
 }
 
 function process_command()
 {
-	local ignore_list=""
-	local pkgs_file=""
-	local pkgs_list=""
-	local temp_list=""
-	local pkgs_flag_all=""
-	local do_repair=""
-	local do_write=""
-	local do_error=""
-	local do_invert=""
-	local do_sort=""
 	local tool_cmd
-	local pkg_temp pkg_test pkg_name
-
 	[[ ! -f $SLACKPKGFILE ]] &&
 		echo -e "File '$SLACKPKGFILE' not found! Aborting!\n" && exit 1
-
+	[[ ! -d $SLACKINSTLOG ]] &&
+		echo -e "'$SLACKINSTLOG' not found! Not a slack? Aborting!\n" && exit 1
 	tool_cmd=$1; shift
 	case "$tool_cmd" in
 		find)
-			if [[ "$1" == "" ]]; then
-				echo -e "No argument given for '$tool_cmd'!\n"
-				exit 1
-			fi
-			while [[ "$1" != "" ]]; do
-				case "$1" in
-					--alien)
-						ignore_list="YES"
-						;;
-					*)
-						pkgs_list="$pkgs_list $1"
-						;;
-				esac
-				shift
-			done
-			if [[ "$ignore_list" == "YES" ]]; then
-				show_alien_pkgs
-			else
-				for tpack in $pkgs_list; do
-					pkg_temp="pkgbase_${tpack//-/_}"
-					[[ -z "${!pkg_temp}" ]] && pkg_db_package $tpack --all
-					[[ -z "${!pkg_temp}" ]] && pkg_db_install $tpack --all
-					if [[ -z "${!pkg_temp}" ]]; then
-						echo -e "Package '$tpack' not found!\n"
-					else
-						show_info $tpack
-					fi
-				done
-			fi
+			view_find_package "$@"
 			;;
-		select)
-			if [[ "$1" == "" ]]; then
-				echo -e "No argument given for '$tool_cmd'!\n"
-				exit 1
-			fi
-			while [[ "$1" != "" ]]; do
-				case "$1" in
-					-f | --file )
-						shift
-						pkgs_file="$1"
-						;;
-					-u | --unselect )
-						do_invert="YES"
-						;;
-					-s | --sort )
-						do_sort="YES"
-						;;
-					-p | --pack )
-						shift
-						pkg_test=$(get_softpack $1)
-						for tpack in $pkg_test ; do
-							pkg_name=($(get_pkg_info $tpack))
-							pkgs_list="$pkgs_list ${pkg_name[0]}"
-						done
-						;;
-					*)
-						pkgs_list="$pkgs_list $1"
-						;;
-				esac
-				shift
-			done
-			[[ "$pkgs_file" == "" ]] &&
-				echo -e "File name for package list NOT given! Aborting!\n" && exit 1
-			[[ ! -f "$pkgs_file" ]] &&
-				touch "$pkgs_file"
-			[[ ! -r "$pkgs_file" ]] &&
-				echo -e "Cannot read file '$pkgs_file'!\n" && exit 1
-			if [[ "$pkgs_list" != "" ]]; then
-				# check the given package list
-				temp_list=$pkgs_list
-				pkgs_list=""
-				for tpack in $temp_list; do
-					pkg_temp=$(find_package $tpack)
-					[[ "$pkg_temp" == "" ]] && echo -e "Cannot find package '$tpack'!\n" && continue
-					pkgs_list="$pkgs_list $tpack"
-				done
-				for tpack in $pkgs_list; do
-					pkg_temp=$(find_infile $pkgs_file $tpack)
-					if [[ "$pkg_temp" == "" ]]; then
-						if [[ "$do_invert" == "YES" ]]; then
-							echo "Package '$tpack' not in file!"
-						else
-							# add new
-							pkg_temp=$(find_package $tpack)
-							echo $pkg_temp >>$pkgs_file
-							echo "Package '$pkg_temp' added to $pkgs_file."
-						fi
-					else
-						if [[ "$do_invert" == "YES" ]]; then
-							# remove?
-							sed -i -e "\|^$tpack|d" $pkgs_file
-							if [[ $? -ne 0 ]]; then
-								echo "Error deleting package '$pkg_temp'! [$tpack]"
-							else
-								echo "Package '$pkg_temp' deleted from $pkgs_file."
-							fi
-						else
-							# replace in case old version!
-							pkg_temp=$(find_package $tpack)
-							sed -i -e "\|^$tpack|c\\$pkg_temp" $pkgs_file
-							if [[ $? -ne 0 ]]; then
-								echo "Error replacing package '$pkg_temp'! [$tpack]"
-							else
-								echo "Package '$pkg_temp' updated in $pkgs_file."
-							fi
-						fi
-					fi
-				done
-			fi
-			if [[ "$do_sort" == "YES" ]]; then
-				echo -n "Sorting (with uniq) $pkgs_file..."
-				cat $pkgs_file | uniq | sort -o $pkgs_file
-				echo " done!"
-			else
-				[[ "$pkgs_list" == "" ]] && echo "No package selected? Nothing to do!"
-			fi
-			echo
-			;;
-		check)
-			if [[ "$1" == "" ]]; then
-				echo -e "No argument given for '$tool_cmd'!\n"
-				exit 1
-			fi
-			while [[ "$1" != "" ]]; do
-				case "$1" in
-					-f | --file )
-						shift
-						pkgs_file="$1"
-						;;
-					-w | --write ) # only if all OK?
-						do_write="YES"
-						;;
-					-r | --repair )
-						do_repair="YES"
-						;;
-					-a | --all )
-						pkgs_flag_all="YES"
-						;;
-					*)
-						pkgs_list="$pkgs_list $1"
-						;;
-				esac
-				shift
-			done
-			[[ "$pkgs_file" == "" ]] &&
-				echo -e "File name for package list NOT given! Aborting!\n" && exit 1
-			[[ ! -r "$pkgs_file" ]] &&
-				echo -e "Cannot read file '$pkgs_file'!\n" && exit 1
-			if [[ "$pkgs_flag_all" == "YES" ]]; then
-				pkgs_list=""
-				for tpack in $(cat $pkgs_file); do
-					pkg_temp=$tpack
-					pkg_test="${tpack%-*-*-*}"
-					if [[ "$pkg_test" == "$tpack" ]]; then # not a package???
-						pkg_test=""
-						if [[ "$do_repair" == "YES" ]]; then
-							pkg_test=$(find_package $tpack)
-						fi
-						[[ "$pkg_test" == "" ]] && continue
-						pkg_temp=$pkg_test
-					fi
-					pkgs_list="$pkgs_list $pkg_temp"
-				done
-			else
-				temp_list=$pkgs_list
-				pkgs_list=""
-				for tpack in $temp_list; do
-					pkg_temp=$(find_infile $pkgs_file $tpack)
-					[[ "$pkg_temp" == "" ]] && echo -e "Cannot find package '$tpack' in '$pkgs_file'!\n" && continue
-					pkgs_list="$pkgs_list $pkg_temp"
-				done
-			fi
-			for tpack in $pkgs_list; do
-				pkg_test="${tpack%-*-*-*}"
-				pkg_temp=$(find_package "$pkg_test")
-				if [[ "$pkg_temp" == "" ]] ; then
-					echo "Package '$tpack': NOT FOUND!"
-					do_error="FOUND"
-				else
-					comp_package $tpack $pkg_temp
-					pkg_test=$?
-					if [[ $pkg_test -eq 1 ]]; then
-						echo "Package '$tpack': Version mis-matched? [$pkg_temp]"
-						do_error="FOUND"
-					else
-						echo "Package '$tpack': OK!"
-					fi
-				fi
-			done
-			[[ "$pkgs_list" == "" ]] && echo "Nothing to do?!" && do_error="MAYBE"
-			if [[ "$do_write" == "YES" ]] && [[ "$do_error" == "" ]]; then
-				echo -n "" >$pkgs_file
-				for tpack in $pkgs_list; do
-					echo $tpack >>$pkgs_file
-				done
-				echo "$pkgs_file re-written!"
-			fi
-			echo
+		file)
+			view_file_package "$@"
 			;;
 		help|-h|--help)
 			echo "Usage:"
-			echo "  $TOOL_THISFILE <command> [parameter]"
+			echo "  $MY1_TOOLBASE <command> [parameter]"
 			echo "Available commands:"
-			echo "  find   : Find package(s)"
-			echo "         > --alien    : Alien Package"
-			echo "         > {pkg_name} : Find & Display Package Info"
-			echo "  select : Update Package File"
-			echo "         > -f | --file     : Specify Package File"
-			echo "         > -u | --unselect : Delete instead of Insert"
-			echo "         > -s | --sort     : Sort Package File"
-			echo "  check  : Check Package File"
-			echo "         > -f | --file    : Specify Package File"
-			echo "         > -w | --write   : Rewrite Package File (only if everything checks out!)"
-			echo "         > -r | --repair  : If package name not in full, find it!"
-			echo "         > -a | --all     : Check ALL packages in Package File"
+			echo "  find   : Find package(s) in mirror@installation"
+			echo "         > --alien    : Find & list alien package(s)"
+			echo "         > {pkg_name} : Find & display package info"
+			echo "  file   : Manage File for package list"
+			echo "         > --select   : Insert package to list"
+			echo "         > --unselect : Delete package from list"
+			echo "         > --list     : List packages on list"
+			echo "         > --all      : Browse packages on list"
+			echo "         > --name     : Specify filename"
+			echo "         > --sort     : Sort package list"
 			echo "  help   : Show this help message"
 			echo "Mirror Source:"
 			echo "  ${SLACKROOTDIR}/${SLACKRELEASE}"
@@ -279,7 +296,8 @@ function process_command()
 			exit 0
 			;;
 		*)
-			echo -e "Unknown command!\n"
+			echo "Unknown command!"
+			echo
 			exit 1
 			;;
 	esac
@@ -287,7 +305,7 @@ function process_command()
 
 # BEGIN MAIN SCRIPT
 
-echo -e "\n$TOOL_THISFILE - $TOOL_THISFUNC ($TOOL_THISVERS)\n"
-process_command $TOOL_COMMANDS
+echo -e "\n$MY1_TOOLBASE - $MY1_TOOLNAME ($MY1_TOOLVERS)\n"
+process_command "$@"
 
 # END MAIN SCRIPT
