Added new option for video-tool
- can now convert to mp4
  = i used this in my other project
  = from internet (link in libtoolvideo)

diff --git a/libtoolvideo b/libtoolvideo
--- a/libtoolvideo
+++ b/libtoolvideo
@@ -110,6 +110,51 @@ video_convert()
 	fi
 }
 
+video_convert_mp4()
+{
+	local ivid=$1
+	video_must_have_input $ivid
+	local path=`dirname $ivid`
+	path=`cd $path ; pwd`
+	local base=`basename $ivid`
+	local extf=${base##*.}
+	local ovid=${base%.${extf}}.mp4
+	local tool="ffmpeg"
+	exec=`which $tool 2>/dev/null`
+	[ ! -x "$exec" ] && echo "Binary $tool not found!" && exit 1
+	ivid=${path}/${base}
+	ovid=${path}/${ovid}
+	while [ -f "$ovid" ] ; do
+		ovid=${ovid//.mp4/_conv.mp4}
+	done
+	local acod="-codec:a aac -b:a 128k"
+	local vcod="-codec:v libx264 -pix_fmt yuv420p"
+	# make sure creation time created from current file's timestamp
+	local stat=`stat -c '%y' $ivid` # modified time
+	local meta=`date -d "$stat" -Ins`
+	meta="-metadata creation_time=${meta:0:19}"
+	case "$2" in
+		# https://gist.github.com/dvlden/b9d923cb31775f92fa54eb8c39ccd5a9
+		--1080p) # MP4 - 1080p
+			vopt="-b:v 4500k -minrate 4500k -maxrate 9000k"
+			vopt="$vopt -bufsize 9000k -vf scale=-2:1080" ;;
+		--720p) # MP4 - 720p
+			vopt="-b:v 2500k -minrate 1500k -maxrate 4000k"
+			vopt="$vopt -bufsize 5000k -vf scale=-2:720" ;;
+		--480p) # MP4 - 480p
+			vopt="-b:v 1000k -minrate 500k -maxrate 2000k"
+			vopt="$vopt -bufsize 2000k -vf scale=-2:480" ;; # -2 div-by-2?
+		--360p) # MP4 - 360p
+			vopt="-b:v 750k -minrate 400k -maxrate 1000k"
+			vopt="$vopt -bufsize 1500k -vf scale=-2:360" ;;
+		-*|*)
+			vopt="-b:v 2500k -minrate 1500k -maxrate 4000k"
+			vopt="$vopt -bufsize 5000k -vf scale=-2:720" ;;
+	esac
+	local opts="-preset slow $meta $acod $vcod $vopt"
+	$exec -i $ivid $opts $ovid
+}
+
 video_split_audio()
 {
 	local ivid=$1
