Updated - still need more testing

diff --git a/libtoolvideo b/libtoolvideo
--- a/libtoolvideo
+++ b/libtoolvideo
@@ -43,42 +43,43 @@ video_convert()
 	local vres=${vres:="704:304"}
 	local vasp=${vasp:="16:9"}
 	local vbit=${vbit:="700k"}
-	local vqsc=${vqsc:="6"}
-	local aqsc=${aqsc:="4"}
-	# check params
+	local vqsc=${vqsc:="8"}
+	local aqsc=${aqsc:="8"}
+	local vfil="scale=$vres"
 	local ovid pas2 dvar dlog=/dev/null
 	local vchk vlen
+	# prepare names
+	video_must_have_input $ivid
+	ovid=`video_prepare_output $ivid $ovid`
+	video_check_output $ovid
+	# check params
 	while [ "$1" != "" ]; do
 		case $1 in
 			--var) dvar="yes" ;;
 			--log) dlog="$ovid.log" ;;
 			--2pass) pas2="yes" ;;
+			--var6) dvar="yes" ; vqsc=6 ; aqsc=6 ;;
 			--vbit) shift ; vbit=$1 ;;
 			--vqsc) shift ; vqsc=$1 ;;
 			--aqsc) shift ; aqsc=$1 ;;
 			--output) shift ; ovid=$1 ;;
 			--tv) vres="512:384" ; vasp="4:3" ;; #mod16 resolution
+			--lite) vfil="$vfil,eq=gamma=1.5:saturation=1.3" ;;
 			--vlen) shift ; vlen=$1 ;;
 			--init) shift ; vchk=$1 ;;
-			*) echo -ne "\n[ABORT] Unknown param '$1'!\n\n" && exit 0
+			*) echo -ne "\n[ABORT] Unknown param '$1'!\n\n" && exit 1
 		esac
 		shift
 	done
-	video_must_have_input $ivid
-	ovid=`video_prepare_output $ivid $ovid`
-	video_check_output $ovid
 	local acod="-ar 48000 -ab 128k"
-	local vcod="-vf scale=$vres -aspect $vasp -vb $vbit -r 25"
-	[ "$dvar" = "yes" ] && pas2="" && acod="-qscale:a $aqsc" &&
-		vcod="-qscale:v $vqsc -vf scale=$vres -aspect $vasp -r 25"
+	local vcod="-vb $vbit"
+	[ "$dvar" = "yes" ] && pas2="" &&
+		acod="-qscale:a $aqsc" && vcod="-qscale:v $vqsc"
 	# -qscale:v 4 is for mpegX stuffs!
 	# -crf 18 is for libx264!
-	# tinker with numbers
-	#ffplay -vf eq=gamma=1.5:saturation=1.3 $ivid
-	#ffplay -vf eq=brightness=0.06:saturation=2 $ivid
-	# render
-	#ffmpeg -i $ivid -vf eq=gamma=1.5:saturation=1.3 -c:a copy $ovid
-	#ffmpeg -i $ivid -vf eq=brightness=0.06:saturation=2 -c:a copy $ovid
+	vcod="$vcod -vf $vfil -aspect $vasp -r 25"
+	# tinker: ffplay -vf eq=brightness=0.06:saturation=2 $ivid
+	# render: ffmpeg -i $ivid -vf eq=brightness=0.06:saturation=2 -c:a copy $ovid
 	# global options
 	local gopt="-sn" # disable subtitle
 	# audio options
@@ -112,7 +113,7 @@ video_convert()
 
 video_convert_mp4()
 {
-	local ivid=$1
+	local ivid=$1 ; shift
 	video_must_have_input $ivid
 	local path=`dirname $ivid`
 	path=`cd $path ; pwd`
@@ -127,32 +128,41 @@ video_convert_mp4()
 	while [ -f "$ovid" ] ; do
 		ovid=${ovid//.mp4/_conv.mp4}
 	done
-	local acod="-codec:a aac -b:a 128k"
+	local acod="-codec:a aac -b:a 128k" # stereo: 64k per channel
 	local vcod="-codec:v libx264 -pix_fmt yuv420p"
 	# make sure creation time created from current file's timestamp
 	local stat=`stat -c '%y' $ivid` # modified time
 	local meta=`date -d "$stat" -Ins`
 	meta="-metadata creation_time=${meta:0:19}"
-	case "$2" in
-		# https://gist.github.com/dvlden/b9d923cb31775f92fa54eb8c39ccd5a9
-		--1080p) # MP4 - 1080p
-			vopt="-b:v 4500k -minrate 4500k -maxrate 9000k"
-			vopt="$vopt -bufsize 9000k -vf scale=-2:1080" ;;
-		--720p) # MP4 - 720p
-			vopt="-b:v 2500k -minrate 1500k -maxrate 4000k"
-			vopt="$vopt -bufsize 5000k -vf scale=-2:720" ;;
-		--480p) # MP4 - 480p
-			vopt="-b:v 1000k -minrate 500k -maxrate 2000k"
-			vopt="$vopt -bufsize 2000k -vf scale=-2:480" ;; # -2 div-by-2?
-		--360p) # MP4 - 360p
-			vopt="-b:v 750k -minrate 400k -maxrate 1000k"
-			vopt="$vopt -bufsize 1500k -vf scale=-2:360" ;;
-		-*|*)
-			vopt="-b:v 750k -minrate 400k -maxrate 1000k"
-			vopt="$vopt -bufsize 1500k -vf scale=-2:360" ;;
-	esac
+	# default option
+	local dlog=/dev/null
+	local vopt="-b:v 650k -minrate 400k -maxrate 900k"
+	vopt="$vopt -bufsize 1500k -vf scale=-2:360"
+	while [ "$1" != "" ]; do
+		case "$1" in
+			# https://gist.github.com/dvlden/b9d923cb31775f92fa54eb8c39ccd5a9
+			--1080p) # MP4 - 1080p
+				vopt="-b:v 4500k -minrate 4500k -maxrate 9000k"
+				vopt="$vopt -bufsize 9000k -vf scale=-2:1080" ;;
+			--720p) # MP4 - 720p
+				vopt="-b:v 2500k -minrate 1500k -maxrate 4000k"
+				vopt="$vopt -bufsize 5000k -vf scale=-2:720" ;;
+			--480p) # MP4 - 480p
+				vopt="-b:v 1000k -minrate 500k -maxrate 2000k"
+				vopt="$vopt -bufsize 2000k -vf scale=-2:480" ;; # -2 div-by-2?
+			--360p) # MP4 - 360p
+				vopt="-b:v 750k -minrate 400k -maxrate 1000k"
+				vopt="$vopt -bufsize 1500k -vf scale=-2:360" ;;
+			--log) dlog="$ovid.log" ;;
+			-*|*) echo -ne "\n[ABORT] Unknown param '$1'!\n\n" && exit 1
+		esac
+		shift
+	done
 	local opts="-preset slow $meta $acod $vcod $vopt"
-	$exec -i $ivid $opts $ovid
+	echo "-- Settings: {$opts}"
+	echo -n "-- Processing... "
+	$exec -i $ivid $opts $ovid 2>>$dlog
+	echo "done."
 }
 
 video_split_audio()
