Trying to update maxisbb - still in progress

diff --git a/maxisbb b/maxisbb
--- a/maxisbb
+++ b/maxisbb
@@ -4,16 +4,27 @@
 # - written by azman@my1matrix.net
 # - to get connected to 3G broadband network using HUAWEI device
 
+HUAWEI_DEV_NAME="HUAWEI"
 HUAWEI_DEV_FILE="/dev/ttyUSB0"
 PPPD_LOG_FILE="/tmp/$(basename $0)-pppd.log"
 
-if [ "$1" == "down" ] ; then
+PATH_DEVICE="/etc/ppp/peers"
+NAME_DEVICE="huawei-dev"
+FILE_DEVICE="$PATH_DEVICE/$NAME_DEVICE"
+FILE_CHATSQ="/etc/ppp/chat-maxisbb"
+
+if [[ "$1" == "cleanup" ]] ; then
+	rm -rf $FILE_DEVICE $FILE_CHATSQ
+	exit 0
+fi
+
+if [[ "$1" == "down" ]] ; then
 	ETH_DEV="$2"
 	ETH_DEV=${ETH_DEV:="eth0"}
 	echo "Stopping server at ethernet device '$ETH_DEV'"
 	DHCPD_PID="$(cat /var/run/dhcpd.pid 2>/dev/null)"
 	ps $DHCPD_PID >/dev/null
-	if [ $? -ne 0 ] || [ $DHCPD_PID == "" ] ; then
+	if [[ $? -ne 0 ]] || [[ $DHCPD_PID == "" ]] ; then
 		echo "dhcpd not running"
 	else
 		kill -s SIGKILL $DHCPD_PID
@@ -23,7 +34,7 @@ if [ "$1" == "down" ] ; then
 	exit 0
 fi
 
-if [ "$1" == "server" ] ; then
+if [[ "$1" == "server" ]] ; then
 	ETH_DEV="$2"
 	ETH_DEV=${ETH_DEV:="eth0"}
 	echo "Running server at ethernet device '$ETH_DEV'"
@@ -34,16 +45,16 @@ if [ "$1" == "server" ] ; then
 	exit 0
 fi
 
-if [ "$1" == "stop" ] ; then
+if [[ "$1" == "stop" ]] ; then
 	PPP_DEV=$(find /var/run -name ppp*.pid)
 	PPP_DEV=${PPP_DEV%.pid}
 	PPP_DEV=${PPP_DEV#/var/run/}
-	if [ "$PPP_DEV" == "" ] ; then
+	if [[ "$PPP_DEV" == "" ]] ; then
 		echo "No pppd running!"
 	else
 		PPP_PID=$(cat /var/run/${PPP_DEV}.pid)
 		ps $PPP_PID >/dev/null
-		if [ $? -ne 0 ] || [ $PPP_PID == "" ] ; then
+		if [[ $? -ne 0 ]] || [[ $PPP_PID == "" ]] ; then
 			echo "pppd not running?!"
 		else
 			echo -n "Terminating pppd (${PPP_DEV}.pid)... "
@@ -55,7 +66,7 @@ if [ "$1" == "stop" ] ; then
 fi
 
 echo -n "Checking if device is plugged in... "
-if [ ! -r $HUAWEI_DEV_FILE ] ; then
+if [[ ! -r $HUAWEI_DEV_FILE ]] ; then
 	echo "Not found!"
 	exit 1
 fi
@@ -65,24 +76,24 @@ echo "done."
 PPP_DEV=$(find /var/run -name ppp*.pid)
 PPP_DEV=${PPP_DEV%.pid}
 PPP_DEV=${PPP_DEV#/var/run/}
-if [ "$PPP_DEV" != "" ] ; then
+if [[ "$PPP_DEV" != "" ]] ; then
 	PPP_PID=$(cat /var/run/${PPP_DEV}.pid)
 	ps $PPP_PID >/dev/null
-	if [ $? -eq 0 ] && [ $PPP_PID != "" ] ; then
+	if [[ $? -eq 0 ]] && [[ $PPP_PID != "" ]] ; then
 		echo "pppd already running (PID=$PPP_PID)"
 		exit 0
 	fi
 fi
 
-ETH_DEV=$(/sbin/ifconfig | grep eth)
+ETH_DEV=$(/sbin/ifconfig | grep 'eth*:')
 ETH_DEV=${ETH_DEV%% *}
-if [ ! "$ETH_DEV" == "" ] ; then
+if [[ ! "$ETH_DEV" == "" ]] ; then
 	echo "Taking down $ETH_DEV device!"
 	/sbin/ifconfig $ETH_DEV down
 fi
 
-MY1_DEV_E220=$(cat <<MY1DEV1
-/dev/ttyUSB0 460800
+MY1_DEV_HUAWEI=$(cat <<MY1DEV1
+/dev/ttyUSB0 3600000
 connect '/usr/sbin/chat -v -f /etc/ppp/chat-maxisbb'
 defaultroute lock
 debug ipcp-accept-remote ipcp-accept-local
@@ -92,7 +103,8 @@ remotename MAXISBB
 password wap
 MY1DEV1
 )
-#echo "$MY1_DEV_E220" >/etc/ppp/huawei-e220
+[[ ! -f "$FILE_DEVICE" ]] && mkdir -p $PATH_DEVICE &&
+	echo "$MY1_DEV_HUAWEI" >$FILE_DEVICE
 
 MY1_CHATSEQ=$(cat <<MY1CHAT
 ABORT 'BUSY'
@@ -103,24 +115,24 @@ OK ATDT*99#
 CONNECT ''
 MY1CHAT
 )
-#echo "$MY1_CHATSEQ" >/etc/ppp/chat-maxisbb
+[[ ! -f "$FILE_CHATSQ" ]] && echo "$MY1_CHATSEQ" >$FILE_CHATSQ
 
 echo -n "" >$PPPD_LOG_FILE
-echo -n "Connecting to Huawei-e220 device ..."
-pppd call huawei-e220 logfile $PPPD_LOG_FILE 1>>$PPPD_LOG_FILE 2>>$PPPD_LOG_FILE
-if [ $? -ne 0 ] ; then
+echo -n "Connecting to $HUAWEI_DEV_NAME device ..."
+pppd call $NAME_DEVICE logfile $PPPD_LOG_FILE 1>>$PPPD_LOG_FILE 2>>$PPPD_LOG_FILE
+if [[ $? -ne 0 ]] ; then
 	echo "Error detected!"
 	exit 1
 fi
 
 # sleep a bit so pppd can finish its job
-while [ "$(/sbin/ifconfig | grep ppp)" == "" ] ; do
+while [[ "$(/sbin/ifconfig | grep ppp)" == "" ]] ; do
 	echo -n "."
 	CHECK_MSGS="$(cat $PPPD_LOG_FILE)"
-	if [ "$(echo "$CHECK_MSGS" | grep "Connect script failed")" != "" ] ; then
+	if [[ "$(echo "$CHECK_MSGS" | grep "Connect script failed")" != "" ]] ; then
 		echo "Connect script failed!"
 		exit 1
-#	elif [ "$(echo "$CHECK_MSGS" | grep "is locked by pid")" != "" ] ; then
+#	elif [[ "$(echo "$CHECK_MSGS" | grep "is locked by pid")" != "" ]] ; then
 #		PROC_PID=$(echo "$CHECK_MSGS" | grep "is locked by pid")
 #		PROC_PID=${PROC_PID##*is locked by pid }
 #		echo "Device locked by process PID=$PROC_PID!"
