Adding gzip option

diff --git a/packthis b/packthis
--- a/packthis
+++ b/packthis
@@ -18,16 +18,19 @@ NUM_COPY=${NUM_COPY:=0}
 TAR_EXEC=${TAR_EXEC:="tar"}
 TAR_OPTS=${TAR_OPTS:="cjf"}
 TAR_EXTN=${TAR_EXTN:=".tar.bz2"}
+TZR_OPTS=${TAR_OPTS:="czf"}
+TZR_EXTN=${TAR_EXTN:=".tar.gz"}
 ZIP_EXEC=${ZIP_EXEC:="zip"}
 ZIP_OPTS=${ZIP_OPTS:="-rq"}
 ZIP_EXTN=${ZIP_EXTN:=".zip"}
 DO_ZIP=${DO_ZIP:="NO"}
+DO_GZ=${DO_GZ:="NO"}
 CHK_EXEC=
 CHK_NAME=
 CHK_COPY=
 CHK_EXTN=
 
-while [[ "$1" != "" ]]; do
+while [ "$1" != "" ]; do
 	case $1 in
 		--suffix)
 			shift
@@ -54,8 +57,11 @@ while [[ "$1" != "" ]]; do
 			;;
 		--path)
 			shift
-			[[ ! -d "$1" ]] && echo "Path '$1' not found!"
-			[[ -d "$1" ]] && BALLPATH=$(cd $1;pwd)
+			[ ! -d "$1" ] && echo "Path '$1' not found!"
+			[ -d "$1" ] && BALLPATH=$(cd $1;pwd)
+			;;
+		--gz)
+			DO_GZ="YES"
 			;;
 		--zip)
 			DO_ZIP="YES"
@@ -67,40 +73,42 @@ while [[ "$1" != "" ]]; do
 	shift
 done
 
-[[ "$CHK_VERB" == "YES" ]] && TAR_OPTS="${TAR_OPTS}v"
-[[ "$CHK_VERB" == "YES" ]] && ZIP_OPTS="${ZIP_OPTS//q/}"
+[ "$DO_GZ" == "YES" ] && TAR_OPTS=$TZR_OPTS && TAR_EXTN=$TZR_EXTN
 
-[[ "$CHECKGIT" == "YES" ]] &&
-	[[ -d "$CURRPATH/.git" ]] && BALLSUFX="${BALLSUFX}_git"
+[ "$CHK_VERB" == "YES" ] && TAR_OPTS="${TAR_OPTS}v"
+[ "$CHK_VERB" == "YES" ] && ZIP_OPTS="${ZIP_OPTS//q/}"
 
-[[ ! -d $BALLPATH ]] && mkdir -pv $BALLPATH
+[ "$CHECKGIT" == "YES" ] &&
+	[ -d "$CURRPATH/.git" ] && BALLSUFX="${BALLSUFX}_git"
 
-if [[ "$BUNDLGIT" == "YES" ]]; then
-	[[ ! -d "$CURRPATH/.git" ]] &&
+[ ! -d $BALLPATH ] && mkdir -pv $BALLPATH
+
+if [ "$BUNDLGIT" == "YES" ]; then
+	[ ! -d "$CURRPATH/.git" ] &&
 		echo "Not a git repo! Cannot use 'git bundle'!" && exit 1
 	CHK_BRANCH="$(git branch|grep "* ")"
 	CHK_BRANCH="${CHK_BRANCH#* }"
 	CHK_NAME=${BALLNAME}-$(date +%Y%m%d%H%M)_${CHK_BRANCH}.git
 	git bundle create ${BALLPATH}/${CHK_NAME} ${CHK_BRANCH}
-	[[ $? -ne 0 ]] && echo "Error running git?" && exit 1
+	[ $? -ne 0 ] && echo "Error running git?" && exit 1
 	exit 0
 fi
 
-if [[ "$PATCHGIT" == "YES" ]]; then
-	[[ ! -d "$CURRPATH/.git" ]] &&
+if [ "$PATCHGIT" == "YES" ]; then
+	[ ! -d "$CURRPATH/.git" ] &&
 		echo "Not a git repo! Cannot use 'git diff'!" && exit 1
 	CHK_NAME=${BALLNAME}-$(date +%Y%m%d%H%M).patch
 	git diff >${BALLPATH}/${CHK_NAME}
-	[[ $? -ne 0 ]] && echo "Error running git?" && exit 1
+	[ $? -ne 0 ] && echo "Error running git?" && exit 1
 	exit 0
 fi
 
-[[ -L "$CURRPATH" ]] && CURRPATH=$(pwd -P) && WORKPATH=$(dirname $CURRPATH)
+[ -L "$CURRPATH" ] && CURRPATH=$(pwd -P) && WORKPATH=$(dirname $CURRPATH)
 
-if [[ -d $WORKPATH ]]; then
+if [ -d $WORKPATH ]; then
 	cd $WORKPATH
-	[[ "$CHK_VERB" == "NO" ]] && echo -n "Archiving ... "
-	if [[ "$DO_ZIP" == "YES" ]]; then
+	[ "$CHK_VERB" == "NO" ] && echo -n "Archiving ... "
+	if [ "$DO_ZIP" == "YES" ]; then
 		CHK_EXEC="${ZIP_EXEC} ${ZIP_OPTS}"
 		CHK_NAME=${BALLNAME}
 		CHK_EXTN=${ZIP_EXTN}
@@ -110,12 +118,12 @@ if [[ -d $WORKPATH ]]; then
 		CHK_EXTN=${TAR_EXTN}
 	fi
 	CHK_COPY=${BALLSUFX}${CHK_COPY}${CHK_EXTN}
-	while [[ -f ${BALLPATH}/${CHK_NAME}-$(date ${DATE_FMT})${CHK_COPY} ]]; do
+	while [ -f ${BALLPATH}/${CHK_NAME}-$(date ${DATE_FMT})${CHK_COPY} ]; do
 		(( NUM_COPY=NUM_COPY+1 ))
 		CHK_COPY="${BALLSUFX}_${NUM_COPY}${CHK_EXTN}"
 	done
 	CHK_EXTN=${CHK_COPY}
 	CHK_NAME=${CHK_NAME}-$(date ${DATE_FMT})${CHK_EXTN}
 	${CHK_EXEC} ${BALLPATH}/${CHK_NAME} ${BALLNAME}
-	[[ "$CHK_VERB" == "NO" ]] && echo "done."
+	[ "$CHK_VERB" == "NO" ] && echo "done."
 fi
