Updated packthis script
- git bundle option can now bundle ALL branches... and tags...
- the --suffix option now appends to name... before date/time

diff --git a/packthis b/packthis
--- a/packthis
+++ b/packthis
@@ -8,6 +8,7 @@ CURRPATH=$(pwd)
 WORKPATH=$(dirname $CURRPATH)
 BALLPATH=$HOME/temp
 BALLNAME=$(basename $CURRPATH)
+NAMESUFX=${NAMESUFX:=""}
 BALLSUFX=${BALLSUFX:=""}
 DATE_FMT=${DATE_FMT:="+%Y%m%d"}
 CHECKGIT=${CHECKGIT:="YES"}
@@ -33,7 +34,7 @@ while [ "$1" != "" ]; do
 	case $1 in
 		--suffix)
 			shift
-			BALLSUFX="-$1"
+			NAMESUFX="-$1"
 			;;
 		--time)
 			DATE_FMT="+%Y%m%d%H%M"
@@ -46,7 +47,12 @@ while [ "$1" != "" ]; do
 			BUNDLGIT="YES"
 			PATCHGIT="NO"
 			;;
-		--patch-git)
+		--git-all)
+			CHECKGIT="ALL"
+			BUNDLGIT="YES"
+			PATCHGIT="NO"
+			;;
+		--git-patch|--patch-git)
 			CHECKGIT="NO"
 			BUNDLGIT="YES"
 			PATCHGIT="YES"
@@ -86,25 +92,28 @@ done
 [ "$CHK_VERB" == "YES" ] && TAR_OPTS="${TAR_OPTS}v"
 [ "$CHK_VERB" == "YES" ] && ZIP_OPTS="${ZIP_OPTS//q/}"
 
-[ "$CHECKGIT" == "YES" ] &&
-	[ -d "$CURRPATH/.git" ] && BALLSUFX="${BALLSUFX}_git"
-
 [ ! -d $BALLPATH ] && mkdir -pv $BALLPATH
 
 if [ "$BUNDLGIT" == "YES" ]; then
 	[ ! -d "$CURRPATH/.git" ] &&
-		echo "Not a git repo! Cannot use 'git bundle'!" && exit 1
+		echo "Not a git repo! Cannot use git stuffs!" && exit 1
 	if [ "$PATCHGIT" == "YES" ]; then
-		CHK_NAME=${BALLNAME}-$(date +%Y%m%d%H%M)_patches
+		BALLSUFX="${BALLSUFX}_patches"
+		CHK_NAME=${BALLNAME}${NAMESUFX}-$(date ${DATE_FMT})${BALLSUFX}
 		rm -rf ${BALLPATH}/${CHK_NAME}
 		#CHK_PREV="$(printf "HEAD%*s" $PATCHNUM "" | tr ' ' '^')";
 		#git bundle create ${BALLPATH}/${CHK_NAME} ${CHK_PREV} HEAD
 		git format-patch -o ${BALLPATH}/${CHK_NAME} -${PATCHNUM}
 		[ $? -ne 0 ] && echo "Error running git?" && exit 1
 	else
-		CHK_BRANCH="$(git branch|grep "* ")"
-		CHK_BRANCH="${CHK_BRANCH#* }"
-		CHK_NAME=${BALLNAME}-$(date +%Y%m%d%H%M)_${CHK_BRANCH}.git
+		if [ "$CHECKGIT" == "ALL" ] ; then
+			CHK_BRANCH="--branches --tags"
+		else
+			CHK_BRANCH="$(git branch|grep "* ")"
+			CHK_BRANCH="${CHK_BRANCH#* }"
+			BALLSUFX="${BALLSUFX}_${CHK_BRANCH}"
+		fi
+		CHK_NAME=${BALLNAME}${NAMESUFX}-$(date ${DATE_FMT})${BALLSUFX}.git
 		git bundle create ${BALLPATH}/${CHK_NAME} ${CHK_BRANCH}
 		[ $? -ne 0 ] && echo "Error running git?" && exit 1
 	fi
@@ -113,8 +122,9 @@ fi
 
 if [ "$PATCHGIT" == "YES" ]; then
 	[ ! -d "$CURRPATH/.git" ] &&
-		echo "Not a git repo! Cannot use 'git diff'!" && exit 1
-	CHK_NAME=${BALLNAME}-$(date +%Y%m%d%H%M).patch
+		echo "Not a git repo! Cannot use git stuffs!" && exit 1
+	BALLSUFX="${BALLSUFX}_git"
+	CHK_NAME=${BALLNAME}${NAMESUFX}-$(date ${DATE_FMT})${BALLSUFX}.patch
 	git diff >${BALLPATH}/${CHK_NAME}
 	[ $? -ne 0 ] && echo "Error running git?" && exit 1
 	exit 0
@@ -127,14 +137,15 @@ if [ -d $WORKPATH ]; then
 	[ "$CHK_VERB" == "NO" ] && echo -n "Archiving ... "
 	if [ "$DO_ZIP" == "YES" ]; then
 		CHK_EXEC="${ZIP_EXEC} ${ZIP_OPTS}"
-		CHK_NAME=${BALLNAME}
 		CHK_EXTN=${ZIP_EXTN}
 	else
 		CHK_EXEC="${TAR_EXEC} ${TAR_OPTS}"
-		CHK_NAME=${BALLNAME}
 		CHK_EXTN=${TAR_EXTN}
 	fi
-	CHK_COPY=${BALLSUFX}${CHK_COPY}${CHK_EXTN}
+	[ "$CHECKGIT" != "NO" ] &&
+		[ -d "$CURRPATH/.git" ] && BALLSUFX="${BALLSUFX}_git"
+	CHK_NAME=${BALLNAME}${NAMESUFX}
+	CHK_COPY=${BALLSUFX}${CHK_EXTN}
 	while [ -f ${BALLPATH}/${CHK_NAME}-$(date ${DATE_FMT})${CHK_COPY} ]; do
 		(( NUM_COPY=NUM_COPY+1 ))
 		CHK_COPY="${BALLSUFX}_${NUM_COPY}${CHK_EXTN}"
