Code cleanup

diff --git a/pi_image_shrink b/pi_image_shrink
--- a/pi_image_shrink
+++ b/pi_image_shrink
@@ -3,16 +3,23 @@
 DISK_FILE="$1"
 [ -z "$DISK_FILE" ] && echo "No image file given!" && exit 1
 [ ! -f "$DISK_FILE" ] && echo "Cannot find '$DISK_FILE'!" && exit 1
-echo "ImageFile:$DISK_FILE"
+echo "DiskFile:$DISK_FILE"
 
 MAKE_EXEC="$2"
 [ "$MAKE_EXEC" == "-x" ] && MAKE_EXEC="YES" || MAKE_EXEC="NO"
 
-DISK_SIZE=`ls -lh "$DISK_FILE" | cut -d ' ' -f 5`
-echo "DiskSize:$DISK_SIZE"
+#DISK_SIZE=`ls -lh "$DISK_FILE" | cut -d ' ' -f 5`
+#echo "DiskSize:$DISK_SIZE"
 
 # must run as root
 [ $UID -ne 0 ] && echo "Must run as root!" && exit 1
+
+clean_exit()
+{
+	# release ALL loop device
+	losetup -D
+	[ "$1" != "--wait" ] && exit 1
+}
 
 # --partscan @ -P
 LOOP_DISK=`losetup -P --show -f "$DISK_FILE"`
@@ -20,8 +27,8 @@ echo "LoopDisk:$LOOP_DISK"
 
 # show disk
 TEST_THAT=`lsblk ; sync ; sync ; sync`
-LOOP_SIZE=`lsblk -l -p | grep "$LOOP_DISK " | tr -s ' ' | cut -d ' ' -f 4`
-echo "LoopSize:$LOOP_SIZE"
+#LOOP_SIZE=`lsblk -l -p | grep "$LOOP_DISK " | tr -s ' ' | cut -d ' ' -f 4`
+#echo "LoopSize:$LOOP_SIZE"
 
 # get loop device for boot partition
 PART_BOOT=`lsblk -l -p -f | grep "$LOOP_DISK" | grep "boot" | tr -s ' '`
@@ -34,6 +41,10 @@ PART_ROOT=`lsblk -l -p -f | grep "$LOOP_DISK" | grep "rootfs" | tr -s ' '`
 LOOP_ROOT=`echo "$PART_ROOT" | cut -d ' ' -f 1`
 #echo "PartRoot:$PART_ROOT"
 echo "LoopRoot:$LOOP_ROOT"
+
+# sanity check!
+[ "$LOOP_BOOT" = "" -o "$LOOP_ROOT" = "" ] &&
+	echo "Cannot find loop device(s) for boot/root!" && clean_exit
 
 # tune2fs
 PART_TEST=`tune2fs -l "$LOOP_ROOT"`
@@ -63,7 +74,7 @@ PART_XTRA=$((SECT_MAKE-PART_MAKE))
 [ $PART_XTRA -lt $SECT_HALF ] && PART_XTRA=$((PART_XTRA+SECT_MAKE))
 #echo "PartXtra:$PART_XTRA"
 PART_MINS=$((PART_MINS+PART_XTRA))
-echo "PartMins:$PART_MINS"
+#echo "PartMins:$PART_MINS"
 
 # shrink fs
 if [ "$MAKE_EXEC" = "YES" ] ; then
@@ -82,20 +93,19 @@ PART_TEST=`echo $PART_ROOT | cut -d ' ' -f 1`
 [ "$PART_TEST" != "$LOOP_ROOT" ] &&
 	echo "Partition mismatch ($PART_TEST!=$LOOP_ROOT)!"
 PART_INIT=`echo $PART_ROOT | cut -d ' ' -f 2`
-echo "PartInit:$PART_INIT"
+[ "$MAKE_EXEC" = "NO" ] && echo "PartInit:$PART_INIT"
 PART_ENDS=`echo $PART_ROOT | cut -d ' ' -f 3`
-echo "PartEnds:$PART_ENDS"
+[ "$MAKE_EXEC" = "NO" ] && echo "PartEnds:$PART_ENDS"
 PART_THAT=`echo $PART_ROOT | cut -d ' ' -f 4`
-echo "PartThat:$PART_THAT"
-
+[ "$MAKE_EXEC" = "NO" ] && echo "PartThat:$PART_THAT"
 PART_BYTE=$((PART_MINS*PART_SIZE))
 #echo "PartByte:$PART_BYTE"
 PART_SECT=$((PART_BYTE/512))
-echo "PartSect:$PART_SECT(512b sectors)"
+[ "$MAKE_EXEC" = "NO" ] && echo "PartSect:$PART_SECT(512b sectors)"
 PART_ENDS=$((PART_INIT+PART_SECT-1))
-echo "PartEnds:$PART_ENDS(NEW)"
+[ "$MAKE_EXEC" = "NO" ] && echo "PartEnds:$PART_ENDS(NEW)"
 DISK_FULL=$((PART_ENDS+1))
-echo "DiskFull:$DISK_FULL(NEW)"
+[ "$MAKE_EXEC" = "NO" ] && echo "DiskFull:$DISK_FULL(NEW)"
 
 if [ "$MAKE_EXEC" = "YES" ] ; then
 echo "Resizing $LOOP_ROOT..."
@@ -111,29 +121,30 @@ w
 EOF
 fi
 
-echo "[RECHECK]"
+[ "$MAKE_EXEC" = "NO" ] && echo "[RECHECK]"
 PART_DISK=`fdisk -l "$LOOP_DISK"`
 PART_ROOT=`echo "$PART_DISK" | tail -n 1 | tr -s ' '`
 PART_INIT=`echo $PART_ROOT | cut -d ' ' -f 2`
-echo "PartInit:$PART_INIT"
+[ "$MAKE_EXEC" = "NO" ] && echo "PartInit:$PART_INIT"
 PART_ENDS=`echo $PART_ROOT | cut -d ' ' -f 3`
-echo "PartEnds:$PART_ENDS"
+[ "$MAKE_EXEC" = "NO" ] && echo "PartEnds:$PART_ENDS"
 PART_THAT=`echo $PART_ROOT | cut -d ' ' -f 4`
-echo "PartThat:$PART_THAT"
+[ "$MAKE_EXEC" = "NO" ] && echo "PartThat:$PART_THAT"
 
 TEST_FLAG=0
 TEST_PATH="mnt"
 [ ! -d $TEST_PATH ] && TEST_FLAG=1 && mkdir -p $TEST_PATH
+[ ! -b $LOOP_BOOT ] &&
+	echo "Cannot find '$LOOP_BOOT' device!" && clean_exit
 mount $LOOP_BOOT $TEST_PATH
 TEST_FILE="$TEST_PATH/cmdline.txt"
 TEST_INIT="init=/usr/lib/raspi-config/init_resize.sh"
 OPTS="-e"
 if [ -f $TEST_FILE ] ; then
-	echo "[CMDLINE]"
-	cat $TEST_FILE
+	[ "$MAKE_EXEC" = "NO" ] && echo "[CMDLINE]" && cat $TEST_FILE
 	PART_UUID=`lsblk -l -p -o NAME,LABEL,PARTUUID | grep "$LOOP_ROOT"`
 	PART_UUID=`echo "$PART_UUID" | cut -d ' ' -f 3`
-	echo "PartUUID=$PART_UUID"
+	[ "$MAKE_EXEC" = "NO" ] && echo "PartUUID=$PART_UUID"
 	[ "$MAKE_EXEC" = "YES" ] && OPTS="-i -e"
 	sed $OPTS "s/^\(.*PARTUUID=\)[^\s]*\(\s.*\)$/\1$PART_UUID\2/g" $TEST_FILE
 	TEST_WHAT=`cat $TEST_FILE | grep "init="`
@@ -142,6 +153,8 @@ if [ -f $TEST_FILE ] ; then
 fi
 sync ; sync ; sync
 umount $TEST_PATH
+[ ! -b $LOOP_ROOT ] &&
+	echo "Cannot find '$LOOP_ROOT' device!" && clean_exit
 mount $LOOP_ROOT $TEST_PATH
 if [ "$MAKE_EXEC" = "YES" ] ; then
 	echo "Creating new $TEST_PATH/etc/rc.local ..."
@@ -157,17 +170,17 @@ reboot
 EOF
 	#cp $TEST_PATH/etc/rc.local $TEST_PATH/etc/rc.local-debug
 	chmod +x $TEST_PATH/etc/rc.local
-	cat $TEST_PATH/etc/rc.local
+	#cat $TEST_PATH/etc/rc.local
 fi
 sync ; sync ; sync
 umount $TEST_PATH
 [ $TEST_FLAG -ne 0 ] && rmdir $TEST_PATH
 
 # release loop device
-losetup -D
+clean_exit --wait
 
 DISK_FULL=$((DISK_FULL*512))
-echo "DiskFull:$DISK_FULL(bytes)"
+[ "$MAKE_EXEC" = "NO" ] && echo "DiskFull:$DISK_FULL(bytes)"
 
 if [ "$MAKE_EXEC" = "YES" ] ; then
 echo "Resizing image $DISK_FILE..."
