Updated slackroot to build squashfs-packed module

diff --git a/slackroot b/slackroot
--- a/slackroot
+++ b/slackroot
@@ -23,8 +23,9 @@ SLACKARCH=${SLACKARCH:="x86"} # force 32-bit slackware!
 # my1slack tool specific
 MY1_TOOL_LOG=${MY1_TOOL_LOG:="/tmp/${MY1_TOOLBASE}.log"}
 MY1_ROOT_DEF=${MY1_ROOT_DEF:="/opt/chroot32"}
-MY1_LIVE_DEF=${MY1_LIVE_DEF:="$(pwd)"}
+MY1_LIVE_DEF=${MY1_LIVE_DEF:="$(pwd)/live"}
 MY1_USER_DEF=${MY1_USER_DEF:="user"}
+MY1_PACK_DEF=${MY1_PACK_DEF:="00-core"}
 # global options & settings
 MSG_THISHELP=$(cat <<SETHELPMSG
 Usage:
@@ -34,6 +35,7 @@ Commands:
   config : Configure for chroot32 installation
   chroot : Do create & config in one command
   squash : Squash root installation (NOT TESTED)
+  livefs : Do create & squash in one command (NOT TESTED)
 Options:
   --verbose : More info
   --exec    : Execute (else just dry run!)
@@ -41,13 +43,13 @@ Options:
 Options (create):
   --path <path> : Specify path for packages
   --file <file> : Specify file containing package list
-  --base-only : Select minimal packages (bootstrap?)
-  --core-only : Select basic system tool packages
-  --console   : Select console application packages 
-  --desktop   : Select desktop application packages
+  --core    : Select basic system tool packages
+  --console : Select console application packages 
+  --desktop : Select desktop application packages
 Options (squash):
   --live <path> : Specify live path (default: $MY1_LIVE_DEF)
   --user <user> : Specify user name (default: $MY1_USER_DEF)
+  --pack <name> : Specify pack name (default: $MY1_PACK_DEF)
   --custom  : Customize root installation
 Log File:
   $MY1_TOOL_LOG
@@ -98,7 +100,6 @@ function do_root_install()
 
 function do_pack_list()
 {
-	local pkg_base="a nb"
 	local pkg_core="a d k l n"
 	local pkg_apps="ap t tcl"
 	local pkg_xgui="x xap"
@@ -110,7 +111,6 @@ function do_pack_list()
 		CORE) pkg_opts="$pkg_core" ;;
 		CONS) pkg_opts="$pkg_core $pkg_apps" ;;
 		DESK) pkg_opts="$pkg_core $pkg_apps $pkg_xgui" ;;
-		BASE) pkg_opts="$pkg_base" ;;
 		*) error_exit "Unknown package option!" ;;
 	esac
 	# check valid pkg path
@@ -118,16 +118,7 @@ function do_pack_list()
 	# select packages
 	for pkg_soft in $pkg_opts; do
 		cd $pkg_path
-		if [[ "$pkg_soft" == "nb" ]] ; then
-			# special case for base packages!
-			pkg_soft="n"
-			cd $pkg_soft
-			for pkg_name in dhcpcd iputils net-tools network-scripts ; do
-				pkg_name=$(find . -name "*.t[xg]z"|grep $pkg_name)
-				pkg_file=${pkg_path}/${pkg_soft}/${pkg_name//.\//}
-				pkg_list="${pkg_list}${pkg_file} "
-			done
-		elif [[ -d $pkg_soft ]] ; then
+		if [[ -d $pkg_soft ]] ; then
 			cd $pkg_soft
 			for pkg_name in $(find . -name "*.t[xg]z"); do
 				pkg_file=${pkg_path}/${pkg_soft}/${pkg_name//.\//}
@@ -146,7 +137,7 @@ function rootfs_create()
 	local chk_file=""
 	local chk_exec=""
 	local chk_syyy=""
-	local pkg_list pkg_temp tmp_list
+	local pkg_list pkg_temp tmp_list pkg_name pkg_base
 	# check parameters
 	while [[ "$1" != "" ]]; do
 		case "$1" in
@@ -163,10 +154,7 @@ function rootfs_create()
 				chk_file=$1
 				pkg_opts="FILE"
 				;;
-			--base-only)
-				pkg_opts="BASE"
-				;;
-			--core-only)
+			--core)
 				pkg_opts="CORE"
 				;;
 			--console)
@@ -181,18 +169,13 @@ function rootfs_create()
 			--exec)
 				chk_exec="--exec"
 				;;
-			-*)
-				error_exit "Unknown create_root option '$1'!"
-				;;
-			*)
-				error_exit "Unknown create_root parameter '$1'!"
-				;;
+			# ignore the rest!
 		esac
 		shift
 	done
 	# must be root to exec!
 	[[ "$chk_exec" == "--exec" ]] && must_be_root
-	# check in case we're simulating target root (need not exist!)
+	# check in case we're only simulating target root (need not exist!)
 	if [[ "$chk_exec" != "--exec" ]] ; then
 		if [[ "${chk_root:0:1}" != "/" ]] ; then
 			[[ "${chk_root:0:2}" == "./" ]] && chk_root=${chk_root:2}
@@ -206,24 +189,27 @@ function rootfs_create()
 	info_msg "Target path: '$chk_root'\n"
 	info_msg "Pack option: '$pkg_opts'\n"
 	# start main info msg
-	info_msg "Creating core root filesystem..."
+	info_msg "Creating root filesystem... "
 	# if executing, check/create root path
 	if [[ "$chk_exec" == "--exec" ]] ; then
-		[[ "$chk_syyy" == "--verbose" ]] &&
-			info_msg "Creating root path '$chk_root' ...\n"
 		mkdir -p $chk_root
 		chk_root=$(cd $chk_root;pwd)
+		[[ "$chk_syyy" == "--verbose" ]] &&
+			info_msg "(Target path: '$chk_root') "
 	fi
 	# if package list given, use it!
 	if [[ "$pkg_opts" == "FILE" ]]; then
 		[[ ! -r $chk_file ]] &&
-			error_msg "Cannot open package file '$chk_file'!\n"
+			error_msg "Cannot open package file '$chk_file'!\n" && return
 		ifs_save=$IFS
 		IFS=$'\n'
 		tmp_list=($(cat $chk_file))
 		IFS=$ifs_save
 		for (( x=0;x<${#tmp_list[@]};x++ )); do
-			pkg_temp=$(find $pkg_path -name "${tmp_list[$x]}.t[xg]z")
+			pkg_base=${tmp_list[$x]}
+			pkg_name=${pkg_base#*!}
+			pkg_base=$(find_package $pkg_name)
+			pkg_temp=$(find $pkg_path -name "${pkg_base}.t[xg]z")
 			pkg_list="${pkg_list}${pkg_temp} "
 		done
 	else
@@ -238,7 +224,7 @@ function rootfs_create()
 
 function chroot_config()
 {
-	local chk_root="MY1_ROOT_DEF"
+	local chk_root="$MY1_ROOT_DEF"
 	local chk_exec="NO"
 	local chk_syyy="YES"
 	local chk_file
@@ -466,6 +452,23 @@ function unpack_init() # for reference
 	cd $path_curr
 }
 
+function get_userngrp()
+{
+	local chk_this=$1
+	local chk_path
+	local chk_user chk_grpn
+	[[ "$chk_this" == "." ]] && chk_this=$(pwd)
+	[[ "$chk_this" == ".." ]] && chk_this=$(cd .. ;pwd)
+	[[ ! -r "$chk_this" ]] && echo -e "Cannot read '$chk_this'!" 1>&2 && return
+	chk_path=$(cd $(dirname $chk_this);pwd)
+	chk_this=$(basename $chk_this)
+	chk_user=$(ls -l "${chk_path}/" | grep -e "${chk_this}$")
+	set -- $chk_user
+	chk_user=$3
+	chk_grpn=$4
+	echo -n "$chk_user:$chk_grpn"
+}
+
 function build_module()
 {
 	local mod_label=$1
@@ -494,28 +497,34 @@ function build_module()
 				;;
 			--exec) chk_exec="YES" ;;
 			--verbose) chk_syyy="NO" ;;
-			*)
-				warn_msg "Unknown build_module parameter '$1'!"
-				;;
+			# ignore the rest!
 		esac
 		shift
 	done
-	# exit if cannot find binary!
-	[[ "$chk_exec" == "YES" ]] && find_binary $MKSQUASHFS_BIN >/dev/null &&
-		MKSQUASHFS_BIN=$(find_binary $MKSQUASHFS_BIN)
 	# if executing, do a sanity check
 	mods_path=${path_live}/${mods_path}
 	if [[ "$chk_exec" == "YES" ]] ; then
+		# exit if cannot find binary!
+		find_binary $MKSQUASHFS_BIN >/dev/null &&
+		MKSQUASHFS_BIN=$(find_binary $MKSQUASHFS_BIN)
+		# prepare paths
 		mkdir -p $mods_path
 		rm -f ${mods_path}/${mods_file}
+		# exit if cannot find root path
 		[[ ! -d "$path_root" ]] && error_exit "Root '$path_root' NOT found!"
+	else
+		[[ "$(which $MKSQUASHFS_BIN 2>/dev/null)" == "" ]] &&
+			warn_msg "Cannot find $MKSQUASHFS_BIN! "
 	fi
 	# process!
 	[[ "$chk_syyy" == "NO" ]] && echo && info_msg "Module path: '$mods_path'\n"
 	[[ "$chk_syyy" == "NO" ]] && info_msg "Preparing module '$mods_file'..."
-	[[ "$chk_exec" == "YES" ]] && $MKSQUASHFS_BIN $path_root \
-		$mods_path/$mods_file \
-		$opt_compress -e tmp dev proc sys $mods_path >/dev/null 2>&1
+	if [[ "$chk_exec" == "YES" ]] ; then
+		$MKSQUASHFS_BIN $path_root $mods_path/$mods_file \
+			$opt_compress -e tmp dev proc sys $mods_path >/dev/null 2>&1
+		local chk_perm=$(get_userngrp $path_live)
+		[[ "$chk_perm" != "" ]] && chown $chk_perm -R $path_live
+	fi
 	[[ "$chk_syyy" == "NO" ]] && info_msg --no-tag " done! ($?)\n"
 	# end main info msg
 	info_msg --no-tag "done!\n"
@@ -526,6 +535,7 @@ function squash_create()
 	local chk_root="$MY1_ROOT_DEF"
 	local chk_live="$MY1_LIVE_DEF"
 	local chk_user="user"
+	local chk_pack="$MY1_PACK_DEF"
 	local chk_exec=""
 	local chk_syyy=""
 	local chk_init=""
@@ -550,6 +560,10 @@ function squash_create()
 					chk_live="$(pwd)/${chk_live}"
 				fi
 				;;
+			--pack)
+				shift
+				chk_pack=$1
+				;;
 			--user)
 				shift
 				chk_user=$1
@@ -563,21 +577,24 @@ function squash_create()
 			--exec)
 				chk_exec=$1
 				;;
-			*)
-				echo "Unknown parameter '$1'!"
-				;;
+			# ignore the rest!
 		esac
 		shift
 	done
+	# show settings
+	info_msg "Root path: '$chk_root'\n"
+	info_msg "Live path: '$chk_live'\n"
 	# do your thing!
-	[[ "$chk_init" == "YES" ]] &&
+	if [[ "$chk_init" == "YES" ]] ; then
+		info_msg "User: $chk_user\n"
 		rootfs_custom $chk_root $chk_user $chk_exec $chk_syyy
-	build_module 00-core --root $chk_root --live $chk_live $chk_exec $chk_syyy
+	fi
+	build_module $chk_pack --root $chk_root --live $chk_live $chk_exec $chk_syyy
 }
 
 function process_command()
 {
-	local go_commands="create config chroot squash"
+	local go_commands="create config chroot squash livefs"
 	local chk_command=$1
 	local do_command
 	shift
@@ -592,6 +609,7 @@ function process_command()
 		config) chroot_config $@ ;;
 		chroot) rootfs_create $@ ; chroot_config $@  ;;
 		squash) squash_create $@  ;;
+		livefs) rootfs_create $@ ; squash_create $@  ;;
 	esac
 }
 
