Code cleanup

diff --git a/slackview b/slackview
--- a/slackview
+++ b/slackview
@@ -34,7 +34,7 @@ Mirror Source:
   $SLACKTREE
 SETHELPMSG`
 
-function view_alien_pkgs()
+view_alien_pkgs()
 {
 	local do_echo="YES"
 	local log_path="/var/log/packages"
@@ -50,7 +50,7 @@ function view_alien_pkgs()
 	[ "$do_echo" == "YES" ] && info_msg "No alien package found!\n"
 }
 
-function view_show_pkgs()
+view_show_pkgs()
 {
 	for pkg_name in "$@"; do
 		show_info $pkg_name $SLACKPACK
@@ -59,7 +59,7 @@ function view_show_pkgs()
 	done
 }
 
-function view_find_package()
+view_find_package()
 {
 	local pkg_list
 	while [ "$1" != "" ]; do
@@ -77,7 +77,7 @@ function view_find_package()
 	view_show_pkgs $pkg_list
 }
 
-function file_pack_part()
+file_pack_part()
 {
 	local pkg_name=$1
 	local pkg_soft=`get_packsoft $SLACKPACK $pkg_name`
@@ -85,7 +85,7 @@ function file_pack_part()
 	echo -n $pkg_part
 }
 
-function file_insert_package()
+file_insert_package()
 {
 	local pkg_temp pkg_test pkg_pack pkg_what
 	local pkg_file=$1
@@ -100,10 +100,11 @@ function file_insert_package()
 	if [ -z "$pkg_test" ]; then
 		pkg_test=`find_package $pkg_name $SLACKPACK`
 		[ "$pkg_test" == "" ] &&
-			echo "PACKAGE: [INSERT] => $pkg_name (FAILED!)" && return
+			echo "PACKAGE: [INSERT] => $pkg_name (FAILED!)" && return 0
 		# insert if package is valid
 		echo "$pkg_temp" >>$pkg_file
 		echo "PACKAGE: [INSERT] => $pkg_temp ($pkg_test)"
+		return 1
 	else
 		pkg_pack=`echo $pkg_test | cut -d'!' -f1`
 		pkg_what=`echo $pkg_temp | cut -d'!' -f1`
@@ -111,11 +112,13 @@ function file_insert_package()
 			sed -i -e "\|^$pkg_test\$|c\\$pkg_temp" $pkg_file
 			[ $? -ne 0 ] && pkg_test="$FAILED!"
 			echo "PACKAGE: [UPDATE] => $pkg_temp ($pkg_test)"
+			return 2
 		fi
 	fi
+	return 0
 }
 
-function file_remove_package()
+file_remove_package()
 {
 	local pkg_temp pkg_test
 	local pkg_file=$1
@@ -135,7 +138,7 @@ function file_remove_package()
 	fi
 }
 
-function file_remove_dups()
+file_remove_dups()
 {
 	local pkg_temp pkg_test
 	local pkg_file=$1
@@ -154,7 +157,7 @@ function file_remove_dups()
 	[ -z "$pkg_test" ] && echo "No duplicates in $pkg_file & $dup_file!"
 }
 
-function file_option_package()
+file_option_package()
 {
 	local pkg_temp pkg_test do_select
 	local pkg_file=$1
@@ -184,7 +187,7 @@ function file_option_package()
 	fi
 }
 
-function file_dolist_packages()
+file_dolist_packages()
 {
 	local pkg_temp pkg_name pkg_base
 	local pkg_file=$1
@@ -206,21 +209,32 @@ function file_dolist_packages()
 	done < $pkg_file
 }
 
-function file_update_packages()
+file_sort_packages()
+{
+	echo -n "Sorting $pkg_file..."
+	cat $pkg_file | sort -u -o $pkg_file
+	echo " done!"
+}
+
+file_update_packages()
 {
 	local pkg_temp pkg_name
 	local pkg_file=$1
 	local pkg_list=`cat $pkg_file`
+	local new_flag=0
 	# browse packages on file
 	while read -r pkg_loop  ; do
 		pkg_temp=`echo $pkg_loop | grep -E '^ *#|^$'`
 		[ "$pkg_temp" != "" ] && continue
 		pkg_name=`echo $pkg_loop | cut -d'!' -f2`
 		file_insert_package $pkg_file $pkg_name
+		[ $? -ne 0 ] && new_flag=1
 	done < $pkg_file
+	# sort if list updated!
+	[ $new_flag -ne 0 ] && file_sort_packages
 }
 
-function view_file_package()
+view_file_package()
 {
 	local pkg_list pkg_file pkg_temp pkg_name dup_file
 	local do_select
@@ -283,20 +297,14 @@ function view_file_package()
 	# check request to update file
 	[ "$do_select" == "UPD" ] &&
 		file_update_packages $pkg_file && return
+	# check sort request
+	[ "$do_select" == "SOT" ] &&
+		file_sort_packages && return
 	# check request to remove duplicates in file
 	if [ "$do_select" == "DUP" ] ; then
 		[ ! -r "$dup_file" ] &&
 			error_exit "Cannot read '$dup_file'!\n\n"
 		file_remove_dups $pkg_file $dup_file
-		return
-	fi
-	# check sort request
-	if [ "$do_select" == "SOT" ]; then
-		# make sure no whitespace?
-		sed 's|[[:space:]]|_|g' -i $pkg_file
-		echo -n "Sorting (with uniq) $pkg_file..."
-		cat $pkg_file | uniq | sort -o $pkg_file
-		echo " done!"
 		return
 	fi
 	# check if list is empty
@@ -312,7 +320,7 @@ function view_file_package()
 	done
 }
 
-function process_command()
+process_command()
 {
 	local tool_cmd
 	local pkgs_txt=$SLACKTREE/PACKAGES.TXT
