Updated libmy1slack slacktest slackview
- preparing slackview for use with slackroot?

diff --git a/slackview b/slackview
--- a/slackview
+++ b/slackview
@@ -12,48 +12,63 @@ MY1_TOOLBASE=$(basename $0 .sh)
 MY1_TOOLPATH=$(cd $(dirname $0);pwd)
 MY1_TOOL_LIB="libmy1slack"
 # look for config file
-for config in $(pwd) $MY1_TOOLPATH $HOME; do
+for config in $(pwd) $HOME; do
 	config=$config/.$MY1_TOOLBASE
-	[[ ! -f $config ]] && continue
-	source $config ; break
+	[[ -r $config ]] && source $config && break
 done
 # look for my1slack library
-[[ -r "$MY1_TOOLPATH/$MY1_TOOL_LIB" ]] &&
-	source $MY1_TOOLPATH/$MY1_TOOL_LIB
+[[ -r "$MY1_TOOLPATH/$MY1_TOOL_LIB" ]] && source $MY1_TOOLPATH/$MY1_TOOL_LIB
 
-function pkg_db_check()
-{
-	local pkg_temp pkg_name=$1
-	pkg_temp="pkgbase_${pkg_name//-/_}"
-	[[ -z "${!pkg_temp}" ]] && pkg_db_install $pkg
-	[[ -z "${!pkg_temp}" ]] && pkg_db_package $pkg
-	[[ -z "${!pkg_temp}" ]] && return 1
-	return 0
-}
+# my1slack tool specific
+MY1_TOOL_LOG=${MY1_TOOL_LOG:="/tmp/${MY1_TOOLBASE}.log"}
+MY1_SLACKDIR=${MY1_SLACKDIR:="${SLACKROOTDIR}/${SLACKRELEASE}"}
+MY1_ROOT_DEF=${MY1_ROOT_DEF:="/opt/chroot32"}
+MY1_LIVE_DEF=${MY1_LIVE_DEF:="$(pwd)"}
+MY1_USER_DEF=${MY1_USER_DEF:="user"}
+# global options & settings
+MSG_THISHELP=$(cat <<SETHELPMSG
+Usage:
+  $MY1_TOOLBASE <command> [options]
+Commands:
+  find   : Find package(s) in mirror@installation
+         > --alien    : Find & list alien package(s)
+         > {pkg_name} : Find & display package info
+  file   : Manage File for package list
+         > --insert   : Insert package to list
+         > --delete   : Delete package from list
+         > --browse   : Browse packages on list
+         > --sort     : Sort packages on list
+         > --name     : Specify filename
+         > --pack     : Select official software set
+  help   : Show this help message
+Mirror Source:
+  $MY1_SLACKDIR
+Log File:
+  $MY1_TOOL_LOG
+SETHELPMSG
+)
 
 function view_alien_pkgs()
 {
-	local do_echo
+	local do_echo="YES"
 	# find installed
 	for pkg_base in $(ls $SLACKINSTLOG); do
 		pkg_name="${pkg_base%-*-*-*}"
 		# find if alien
 		if [[ "$(find_package $pkg_name)" == "" ]]; then
 			echo "Alien package: ${pkg_base%-*-*-*} ($pkg_base)"
-			do_echo="YES"
+			do_echo="NO"
 		fi
 	done
-	[[ "$do_echo" != "YES" ]] && echo "No alien package found!"
-	echo
+	[[ "$do_echo" == "YES" ]] && info_msg "No alien package found!\n"
 }
 
 function view_show_pkgs()
 {
-	for pkg in "$@"; do
-		pkg_db_check $pkg
-		[[ $? -ne 0 ]] &&
-			echo -e "Package '$pkg' not found!\n" && continue
-		show_info $pkg
+	for pkg_name in "$@"; do
+		show_info $pkg_name
+		[[ $? -eq 0 ]] && continue
+		warn_msg "Unknown package '$pkg_name'!\n"
 	done
 }
 
@@ -75,40 +90,43 @@ function view_find_package()
 	view_show_pkgs $pkg_list
 }
 
+function file_pack_part()
+{
+	local pkg_name=$1
+	local pkg_soft="$(get_packsoft $pkg_name)"
+	local pkg_part="${pkg_soft}!${pkg_name}"
+	echo -n $pkg_part
+}
+
 function file_insert_package()
 {
-	local pkg_temp pkg_test pkg_list
+	local pkg_list pkg_temp pkg_test
 	local pkg_file=$1
-	local pkg_name=$2
+	local pkg_part=$2
 	local ifs_save=$IFS
+	local pkg_name=${pkg_part#*!}
+	local pkg_soft=${pkg_part#%!${pkg_name}}
 	IFS=$'\n'
 	pkg_list=($(cat $pkg_file | grep "$pkg_name"))
 	IFS=$ifs_save
 	for (( x=0;x<${#pkg_list[@]};x++ )); do
 		pkg_temp=${pkg_list[$x]}
-		[[ "$pkg_temp" == "$pkg_name" ]] && pkg_test=${pkg_list[$x]} && break
-		pkg_temp=($(get_pkg_info ${pkg_list[$x]}))
-		[[ "${pkg_temp[0]}" == $pkg_name ]] && pkg_test=${pkg_list[$x]} && break
+		[[ "${pkg_temp#*!}" == "$pkg_name" ]] && pkg_test=$pkg_temp && break
 	done
-	pkg_temp=$(find_package $pkg_name)
 	if [[ "$pkg_test" == "" ]]; then
-		echo $pkg_temp >>$pkg_file
-		echo "Package '$pkg_temp' added to $pkg_file."
+		# insert
+		echo "$pkg_part" >>$pkg_file
+		return 0
 	else
-		# insert/update?
-		sed -i -e "\|^$pkg_test\$|c\\$pkg_temp" $pkg_file
-		if [[ $? -ne 0 ]]; then
-			echo "Error replacing package '$pkg_name'! [$pkg_temp]"
-		else
-			echo "Package '$pkg_name' updated in $pkg_file. [$pkg_temp]"
-		fi
+		# update
+		sed -i -e "\|^$pkg_test\$|c\\$pkg_part" $pkg_file
+		return $?
 	fi
-	echo
 }
 
 function file_remove_package()
 {
-	local pkg_temp pkg_list pkg_test
+	local pkg_list pkg_temp pkg_test
 	local pkg_file=$1
 	local pkg_name=$2
 	local ifs_save=$IFS
@@ -117,22 +135,16 @@ function file_remove_package()
 	IFS=$ifs_save
 	for (( x=0;x<${#pkg_list[@]};x++ )); do
 		pkg_temp=${pkg_list[$x]}
-		[[ "$pkg_temp" == "$pkg_name" ]] && pkg_test=${pkg_list[$x]} && break
-		pkg_temp=($(get_pkg_info ${pkg_list[$x]}))
-		[[ "${pkg_temp[0]}" == $pkg_name ]] && pkg_test=${pkg_list[$x]} && break
+		[[ "${pkg_temp#*!}" == "$pkg_name" ]] && pkg_test=$pkg_temp && break
 	done
 	if [[ "$pkg_test" == "" ]]; then
-		echo "Package '$pkg_name' not in file!"
+		# nothing to do
+		return 0
 	else
-		# remove?
+		# remove
 		sed -i -e "\|^$pkg_test\$|d" $pkg_file
-		if [[ $? -ne 0 ]]; then
-			echo "Error deleting package '$pkg_name'! [$pkg_test]"
-		else
-			echo "Package '$pkg_test' deleted from $pkg_file."
-		fi
+		return $?
 	fi
-	echo
 }
 
 function file_option_package()
@@ -142,138 +154,120 @@ function file_option_package()
 	local pkg_name=$2
 	local pkg_stat="INCLUDED"
 	# interactive
-	pkg_test="pkgbase_${pkg_name//-/_}"
-	[[ -z "${!pkg_test}" ]] && pkg_db_package $pkg_name
-	[[ -z "${!pkg_test}" ]] &&
-		echo "Package '$pkg_name' unknown!" && return
+	local pkg_base="$(find_package $pkg_name)"
+	[[ "$pkg_base" == "" ]] && echo "Package '$pkg_name' unknown!" && return
 	show_info $pkg_name
-	pkg_temp=$(find_package $pkg_name)
-	pkg_test=$(find_infile $pkg_file $pkg_name)
+	local ifs_save=$IFS
+	IFS=$'\n'
+	pkg_list=($(cat $pkg_file | grep "$pkg_name"))
+	IFS=$ifs_save
+	for (( x=0;x<${#pkg_list[@]};x++ )); do
+		pkg_temp=${pkg_list[$x]}
+		[[ "$${pkg_temp#*!}" == "$pkg_name" ]] && pkg_test=$pkg_temp && break
+	done
 	if [[ "$pkg_test" == "" ]]; then
 		pkg_stat="EXCLUDED"
 	else
-		comp_package $pkg_test $pkg_temp
-		[[ $? -ne 0 ]] &&
-			pkg_stat="INCLUDED ($pkg_test/$pkg_temp) [$?]"
+		pkg_test=$(find_package ${pkg_test#*!})
+		comp_package $pkg_test $pkg_base
+		[[ $? -ne 0 ]] && pkg_stat="INCLUDED ($pkg_test/$pkg_base) [$?]"
 	fi
-	echo -n "Status: $pkg_stat. "
+	echo -ne "\nStatus: $pkg_stat. "
 	read -n 1 -p "Command ([i]nsert/[d]elete/[*]): " do_select ; echo
 	if [[ "$do_select" == "i" ]]; then
-		file_insert_package $pkg_file $pkg_name
+		file_insert_package $pkg_file $(file_pack_part $pkg_name)
 	elif [[ "$do_select" == "d" ]]; then
 		file_remove_package $pkg_file $pkg_name
-	else
-		echo
 	fi
 }
 
 function file_browse_packages()
 {
-	local pkg_name pkg_temp pkg_test pkg_full
+	local pkg_name pkg_temp pkg_desc pkg_base
 	local opt_more opt_init="[p]revious/[n]ext/[q]uit"
-	local tmp_list pkg_list pkg_file=$1 do_select x y
-	shift ; pkg_list="$@" # list ignored for now
+	local pkg_list pkg_file=$1 do_select x y
 	# get all packages on file
 	local ifs_save=$IFS
 	IFS=$'\n'
-	tmp_list=($(cat $pkg_file))
+	pkg_list=($(cat $pkg_file))
 	IFS=$ifs_save
 	# browse packages on file
-	for (( x=0;x<${#tmp_list[@]}; )); do
-		pkg_full=${tmp_list[$x]}
-		pkg_test=""
-		pkg_temp=($(get_pkg_info $pkg_full))
-		pkg_name=${pkg_temp[0]}
-		echo -n "PACKAGE: ${pkg_full}"
-		[[ "${pkg_temp[1]}" == "${pkg_temp[0]}" ]] && pkg_name=$pkg_full &&
-			pkg_full=$(find_package $pkg_name) && pkg_test=" (${pkg_full})"
-		[[ "$pkg_full" == "" ]] && pkg_test=" (INVALID?)"
-		[[ "$pkg_test" != "" ]] && echo -n "$pkg_test"
+	for (( x=0;x<${#pkg_list[@]}; )); do
+		pkg_temp=${pkg_list[$x]}
+		pkg_name=${pkg_temp#*!}
+		pkg_base=$(find_package $pkg_name)
+		echo -n "PACKAGE: ${pkg_name} (${pkg_base})"
 		# try to show details
-		pkg_test="pkgdesc_${pkg_name//-/_}"
-		[[ -z "${!pkg_test}" ]] && pkg_db_package $pkg_name --all
-		if [[ -z "${!pkg_test}" ]] ; then
+		pkg_desc="$(find_package_desc $pkg_name)"
+		if [[ "$pkg_desc" == "" ]] ; then
 			echo -n " => "
 			opt_more=""
 		else
-			echo -e "\n\n${!pkg_test}\n"
+			echo -e "\n\n${pkg_desc}\n"
 			opt_more="[u]pdate/[d]elete/"
 		fi
 		# navigation options
 		read -n 1 -p "Command (${opt_more}${opt_init}): " do_select
 		echo ; echo
 		if [[ "$do_select" == "n" ]]; then
-			[[ $x -lt ${#tmp_list[@]}-1 ]] && (( x++ ))
+			[[ $x -lt ${#pkg_list[@]}-1 ]] && (( x++ ))
 		elif [[ "$do_select" == "p" ]]; then
 			[[ $x -gt 0 ]] && (( x-- ))
 		elif [[ "$do_select" == "u" ]]; then
 			[[ "$opt_more" == "" ]] && continue
-			(( y=x ))
-			file_insert_package $pkg_file $pkg_name
-			(( x=y ))
+			local pkg_part=$(file_pack_part $pkg_name)
+			file_insert_package $pkg_file $pkg_part 
+			if [[ $? -eq 0 ]] ; then echo "Package '$pkg_name' updated!"
+			else echo "Package '$pkg_name' update error!" ; fi
+			break;
 		elif [[ "$do_select" == "d" ]]; then
 			[[ "$opt_more" == "" ]] && continue
 			file_remove_package $pkg_file $pkg_name
+			if [[ $? -eq 0 ]] ; then echo "Package '$pkg_name' deleted!"
+			else echo "Package '$pkg_name' delete error!" ; fi
 			break;
 		elif [[ "$do_select" == "q" ]]; then
 			break;
 		fi
 	done
-	echo
 }
 
 function file_update_packages()
 {
-	local pkg_name pkg_temp pkg_test pkg_full
-	local tmp_list tmp_stat do_select x y
+	local pkg_list pkg_temp pkg_name pkg_base
+	local do_select x y
 	# get all packages on file
 	local ifs_save=$IFS
 	IFS=$'\n'
-	tmp_list=($(cat $pkg_file))
+	pkg_list=($(cat $pkg_file))
 	IFS=$ifs_save
 	# browse packages on file
-	for (( x=0;x<${#tmp_list[@]};x++ )); do
-		pkg_test=${tmp_list[$x]}
-		pkg_full="$pkg_test"
-		pkg_temp=($(get_pkg_info $pkg_full))
-		pkg_name=${pkg_temp[0]}
-		tmp_stat=""
-		echo -n "PACKAGE: ${pkg_full}"
-		[[ "${pkg_temp[1]}" == "${pkg_temp[0]}" ]] && pkg_name=$pkg_full &&
-			pkg_full=$(find_package $pkg_name) && tmp_stat="$pkg_full"
-		[[ "$pkg_full" == "" ]] && tmp_stat="INVALID"
-		[[ "$tmp_stat" != "" ]] && echo -n " ($tmp_stat)"
-		echo -n " => "
-		# update if not the same
-		if [[ "$tmp_stat" == "INVALID" ]]; then
-			read -n 1 -p "Options ([d]elete/[i]gnore/[q]uit): " do_select
-			if [[ "$do_select" == "d" ]]; then
-				echo -e "\bDeleted!"
-				(( y=x ))
-				file_remove_package $pkg_file $pkg_name
-				(( x=y ))
-			elif [[ "$do_select" == "i" ]]; then
-				echo -e "\bIgnored!"
-			elif [[ "$do_select" == "q" ]]; then
-				echo -e "\bAborted!"
-				break;
-			fi
-		elif [[ "$pkg_full" != "$pkg_test" ]]; then
-			echo " Updated!"
-			(( y=x ))
-			file_insert_package $pkg_file $pkg_name
-			(( x=y ))
+	for (( x=0;x<${#pkg_list[@]};x++ )); do
+		pkg_temp=${pkg_list[$x]}
+		pkg_name=${pkg_temp#*!}
+		pkg_base=$(find_package $pkg_name)
+		echo -n "PACKAGE: $pkg_name ($pkg_base) => "
+		if [[ "$pkg_base" == "" ]]; then
+			echo "INVALID!"
 		else
-			echo " OK!"
+			local pkg_part=$(file_pack_part $pkg_name)
+			if [[ "$pkg_temp" != "$pkg_part" ]]; then
+				(( y=x ))
+				file_insert_package $pkg_file $pkg_part
+				if [[ $? -eq 0 ]] ; then echo "Updated!"
+				else echo "Update error!" ; fi
+				(( x=y ))
+			else
+				echo " OK!"
+			fi
 		fi
 	done
-	echo
 }
 
 function view_file_package()
 {
 	local pkg_list pkg_file pkg_temp pkg_name
-	local do_select do_sort
+	local do_select
 	while [[ "$1" != "" ]]; do
 		case "$1" in
 			--select)
@@ -288,12 +282,12 @@ function view_file_package()
 			--update)
 				do_select="UPD"
 				;;
+			--sort)
+				do_select="SOT"
+				;;
 			--name)
 				shift
 				pkg_file="$1"
-				;;
-			--sort)
-				do_sort="YES"
 				;;
 			--pack)
 				shift
@@ -310,44 +304,42 @@ function view_file_package()
 		shift
 	done
 	# check package file - create if needed
-	[[ "$pkg_file" == "" ]] &&
-		echo -e "[ERROR] File name for package list NOT given!\n" && return
+	[[ "$pkg_file" == "" ]] && error_exit "No package list given!"
 	[[ ! -f "$pkg_file" ]] && touch "$pkg_file"
-	[[ ! -r "$pkg_file" ]] &&
-		echo -e "[ERROR] Cannot read file '$pkg_file'!\n" && return
+	[[ ! -r "$pkg_file" ]] && error_exit "Cannot read '$pkg_file'!"
 	# check request to update file
 	[[ "$do_select" == "UPD" ]] &&
 		file_update_packages $pkg_file && return
 	# check request to browse file
 	[[ "$do_select" == "CHK" ]] &&
-		file_browse_packages $pkg_file $pkg_list && return
+		file_browse_packages $pkg_file && return
+	# check sort request
+	if [[ "$do_select" == "SOT" ]]; then
+		echo -n "Sorting (with uniq) $pkg_file..."
+		cat $pkg_file | uniq | sort -o $pkg_file
+		echo " done!"
+		return
+	fi
 	# check if list is empty
 	[[ "$pkg_list" == "" ]] &&
-		echo -e "No package selected? Nothing to do!\n" && return
+		error_exit "No package selected? Nothing to do!"
 	# process the given package list
 	for pkg in $pkg_list; do
 		case $do_select in
-			YES) file_insert_package $pkg_file $pkg ;;
+			YES) file_insert_package $pkg_file $(file_pack_part $pkg) ;;
 			INV) file_remove_package $pkg_file $pkg ;;
 			*) file_option_package $pkg_file $pkg ;;
 		esac
 	done
-	# sort file if requested
-	if [[ "$do_sort" == "YES" ]]; then
-		# should be with software set!
-		echo -n "Sorting (with uniq) $pkg_file..."
-		cat $pkg_file | uniq | sort -o $pkg_file
-		echo " done!"
-	fi
 }
 
 function process_command()
 {
 	local tool_cmd
 	[[ ! -f $SLACKPKGFILE ]] &&
-		echo -e "File '$SLACKPKGFILE' not found! Aborting!\n" && exit 1
+		error_exit "File '$SLACKPKGFILE' not found! Aborting!"
 	[[ ! -d $SLACKINSTLOG ]] &&
-		echo -e "'$SLACKINSTLOG' not found! Not a slack? Aborting!\n" && exit 1
+		error_exit "'$SLACKINSTLOG' not found! Aborting!"
 	tool_cmd=$1; shift
 	case "$tool_cmd" in
 		find)
@@ -356,30 +348,8 @@ function process_command()
 		file)
 			view_file_package "$@"
 			;;
-		help|-h|--help)
-			echo "Usage:"
-			echo "  $MY1_TOOLBASE <command> [parameter]"
-			echo "Available commands:"
-			echo "  find   : Find package(s) in mirror@installation"
-			echo "         > --alien    : Find & list alien package(s)"
-			echo "         > {pkg_name} : Find & display package info"
-			echo "  file   : Manage File for package list"
-			echo "         > --select   : Insert package to list"
-			echo "         > --unselect : Delete package from list"
-			echo "         > --browse   : Browse packages on list"
-			echo "         > --name     : Specify filename"
-			echo "         > --pack     : Select official software set"
-			echo "         > --sort     : Sort package list"
-			echo "  help   : Show this help message"
-			echo "Mirror Source:"
-			echo "  ${SLACKROOTDIR}/${SLACKRELEASE}"
-			echo
-			exit 0
-			;;
 		*)
-			echo "Unknown command!"
-			echo
-			exit 1
+			echo -e "$MSG_THISHELP\n" && exit 0
 			;;
 	esac
 }
@@ -388,5 +358,6 @@ function process_command()
 
 echo -e "\n$MY1_TOOLBASE - $MY1_TOOLNAME ($MY1_TOOLVERS)\n"
 process_command "$@"
+echo ; exit 0
 
 # END MAIN SCRIPT
