Minor cleanup
- support for my1linux...

diff --git a/slackview b/slackview
--- a/slackview
+++ b/slackview
@@ -37,6 +37,7 @@ Commands:
          > --insert   : Insert package to list
          > --delete   : Delete package from list
          > --browse   : Browse packages on list
+         > --update   : Update packages on list
          > --sort     : Sort packages on list
          > --name     : Specify filename
          > --pack     : Select official software set
@@ -163,7 +164,7 @@ function file_option_package()
 	IFS=$ifs_save
 	for (( x=0;x<${#pkg_list[@]};x++ )); do
 		pkg_temp=${pkg_list[$x]}
-		[[ "$${pkg_temp#*!}" == "$pkg_name" ]] && pkg_test=$pkg_temp && break
+		[[ "${pkg_temp#*!}" == "$pkg_name" ]] && pkg_test=$pkg_temp && break
 	done
 	if [[ "$pkg_test" == "" ]]; then
 		pkg_stat="EXCLUDED"
@@ -246,21 +247,22 @@ function file_update_packages()
 		pkg_temp=${pkg_list[$x]}
 		pkg_name=${pkg_temp#*!}
 		pkg_base=$(find_package $pkg_name)
-		echo -n "PACKAGE: $pkg_name ($pkg_base) => "
+		echo -n "PACKAGE: "
 		if [[ "$pkg_base" == "" ]]; then
-			echo "INVALID!"
+			echo -n "[INVALID]"
 		else
 			local pkg_part=$(file_pack_part $pkg_name)
 			if [[ "$pkg_temp" != "$pkg_part" ]]; then
 				(( y=x ))
 				file_insert_package $pkg_file $pkg_part
-				if [[ $? -eq 0 ]] ; then echo "Updated!"
-				else echo "Update error!" ; fi
+				if [[ $? -eq 0 ]] ; then echo -n "[UPDATED]"
+				else echo -n "[ERROR]" ; fi
 				(( x=y ))
 			else
-				echo " OK!"
+				echo -n "[OK]"
 			fi
 		fi
+		echo " => $pkg_name ($pkg_base)"
 	done
 }
 
@@ -270,10 +272,10 @@ function view_file_package()
 	local do_select
 	while [[ "$1" != "" ]]; do
 		case "$1" in
-			--select)
+			--insert)
 				do_select="YES"
 				;;
-			--unselect)
+			--delete)
 				do_select="INV"
 				;;
 			--browse)
