Code-cleanup for slack2iso and added isohyrid feature

diff --git a/slack2iso b/slack2iso
--- a/slack2iso
+++ b/slack2iso
@@ -4,10 +4,6 @@
 # - written by azman@my1matrix.net
 # - a section from alien_bob's mirror_slackware_current.sh
 
-if [[ -d "$1" ]]; then
-	TARGETISO="$(cd $1;pwd)"
-fi
-TARGETISO=${TARGETISO:="$HOME/temp"}
 SLACKROOT=${SLACKROOT:="$(pwd)"}
 [[ -z "$SLACKARCH" ]] && [[ -n "$ARCH" ]] && SLACKARCH=$ARCH
 SLACKARCH=${SLACKARCH:="$(uname -m)"}
@@ -18,25 +14,38 @@ SLACKFULL=${SLACKFULL:="slackware${SLACKSUFX}"}
 SLACKVERS=${SLACKVERS:="13.37"}
 SLACKFULL="${SLACKFULL}-${SLACKVERS}"
 SLACKPATH="${SLACKROOT}/${SLACKFULL}"
-
 [[ ! -d "$SLACKPATH" ]] &&
 	echo "Path to Slackware '$SLACKPATH' not found!" && exit 1
+
+[[ -d "$1" ]] && ISOPATH="$(cd $1;pwd)"
+ISOPATH=${ISOPATH:="$HOME/temp"}
+ISOFILE=${ISOFILE:="${SLACKFULL}-install.iso"}
+
 MKISOFS=$(which mkisofs 2>/dev/null)
-[[ "$MKISOFS" == "" ]] &&
-	echo "Cannot find mkisofs! Aborting!" && exit 1
-[[ ! -d "$TARGETISO" ]] &&
-	echo "Creating target ISO path '$TARGETISO'... " && mkdir -p $TARGETISO
+[[ "$MKISOFS" == "" ]] && echo "Cannot find mkisofs! Aborting!" && exit 1
+[[ ! -d "$ISOPATH" ]] &&
+	echo "Creating target ISO path '$ISOPATH'... " && mkdir -p $ISOPATH
 
 cd $SLACKPATH
-echo -n "Creating ISO in '$TARGETISO' from '$SLACKPATH'... "
-$MKISOFS -o $TARGETISO/${SLACKFULL}-install.iso \
+echo -n "Creating ISO in '$ISOPATH' from '$SLACKPATH'... "
+$MKISOFS -o $ISOPATH/$ISOFILE \
 	-V "${SLACKFULL} Install DVD" \
-	-R -J -hide-rr-moved -hide-joliet-trans-tbl -d -N -v -v -no-emul-boot \
-	-boot-load-size 32 -boot-info-table -sort isolinux/iso.sort \
+	-A "${SLACKFULL} Install DVD (build $(date +%Y%m%d))" \
+	-R -J -hide-rr-moved -hide-joliet-trans-tbl -d -N -v \
+	-sort isolinux/iso.sort \
 	-b isolinux/isolinux.bin -c isolinux/isolinux.boot \
-	-A "${SLACKFULL} Install DVD (build $(date +%Y%m%d))" . \
-	> $TARGETISO/${SLACKFULL}-install_build.log 2>&1
+	-no-emul-boot -boot-load-size 32 -boot-info-table \
+	. > $ISOPATH/${SLACKFULL}-install_build.log 2>&1
 echo "done!"
 cd - >/dev/null
+
+ISOHYBRID=$(which isohybrid 2>/dev/null)
+if [[ -x "$ISOHYBRID" ]] ; then
+	cd $ISOPATH
+	echo -n "Making $ISOFILE in '$ISOPATH' an isohybrid... "
+	$ISOHYBRID $ISOFILE
+	echo "done!"
+	cd - >/dev/null
+fi
 
 exit 0
